IDuxFE/idux

commitlint.config.js
package.json
scripts/gen/index.ts
scripts/gen/template.ts
scripts/gen/tsconfig.json
scripts/utils/log.ts
tsconfig.json

feat(scripts): add gen script to create component template

---

scripts/gen/template.ts

This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/iduxfe/components/issues).

Apply fixes from CodeFactor

---

azure-pipelines.yml
package.json
packages/cdk/clipboard/__tests__/useClipboard.spec.ts
packages/cdk/clipboard/docs/index.zh-CN.md
packages/cdk/clipboard/index.ts
packages/cdk/clipboard/src/clipboard.ts
packages/cdk/clipboard/src/pendingCopy.ts
packages/cdk/clipboard/src/useClipboard.ts
packages/cdk/index.ts

feat(cdk:clipboard): support useClipboard

---

.github/pull_request_template.md
README.md
docs/contributing.zh.md
packages/components/button/demo/basic.md
scripts/gen/index.ts
scripts/gen/template.ts

docs: update 'zh-CN' to 'zh'

---

packages/components/core/logger/index.ts
packages/components/core/utils/isDevMode.ts

feat(comp:core): add logger

---

packages/cdk/clipboard/docs/index.zh.md
packages/components/button/demo/basic.md
packages/components/button/docs/index.zh.md
packages/components/icon/docs/index.zh.md

docs: update clipboard, button, icon components docs

---

jest.config.js
packages/components/button/__tests__/button.spec.ts
packages/components/button/demo/icon.md
packages/components/button/src/Button.vue

fix(comp:button): icon not work

---

packages/components/button/index.ts
packages/components/button/src/Button.vue
packages/components/icon/__tests__/icon.spec.ts
packages/components/icon/index.ts
packages/components/index.ts
scripts/gen/template.ts

refactor: add prefix for all components

---

packages/components/style/variable/border.less
packages/components/style/variable/font.less
packages/components/style/variable/shadow.less
packages/components/style/variable/spacing.less

refactor: update less variable name

---

.eslintrc.js
packages/cdk/clipboard/src/clipboard.ts
packages/cdk/index.ts
scripts/gulp/site/_site/docs/src/shared/CodeBox.vue
scripts/gulp/site/_site/docs/src/side-nav/Index.vue
scripts/gulp/site/generateSite.ts
scripts/gulp/site/template/code-box.html
scripts/gulp/site/template/router.html
scripts/gulp/site/template/title.html

docs: site link fix

---

tsconfig.json

fix: remove types in tsconfig.json

---

.eslintrc.js
packages/components/button/src/Button.vue
packages/components/button/src/ButtonGroup.vue
packages/components/icon/src/Icon.vue

fix(comp:button): set props default value

---

packages/components/icon/demo/Basic.vue
packages/components/icon/src/utils.ts
packages/components/icon/style/index.less

feat(comp:icon): support fill currentColo

---

packages/cdk/breakpoint/__tests__/mediaMatcher.spec.ts
packages/cdk/breakpoint/__tests__/observe.spec.ts
packages/cdk/breakpoint/demo/basic.md
packages/cdk/breakpoint/docs/index.zh.md
packages/cdk/breakpoint/index.ts
packages/cdk/breakpoint/src/breakpoints.ts
packages/cdk/breakpoint/src/index.ts
packages/cdk/breakpoint/src/mediaMatcher.ts
packages/cdk/breakpoint/src/observe.ts
packages/cdk/platform/demo/basic.md
packages/cdk/platform/docs/index.zh.md
packages/cdk/platform/index.ts
packages/cdk/platform/src/platform.ts

feat(cdk:breakpoint): add breakpoint system and observables

---

packages/components/icon/demo/Basic.vue
packages/components/icon/style/index.less

feat(comp:icon): add style

---

CONTRIBUTING.md
README.md
packages/components/index.ts
scripts/gen/index.ts

feat: gen script support auto import index

---

packages/components/button/docs/index.zh.md
packages/components/button/src/Button.vue
packages/components/button/style/mixin.less
packages/components/style/base.less
packages/components/style/default.less
packages/components/style/variable/color/color.less
scripts/gulp/site/template/example-split.html

style: sync design 4.0

---

.ls-lint.yml
docs/contributing.zh.md
packages/components/button/docs/index.zh.md

docs: add code guide in  contributing

---

.eslintrc.js

ci: update eslint rules

---

scripts/gulp/site/generateSite.ts

fix: gulp start with empty component dir

---

docs/contributing.zh.md
packages/cdk/utils/__tests__/typeof.spec.ts
packages/cdk/utils/convert.ts
packages/cdk/utils/typeof.ts
packages/components/badge/src/Badge.vue
packages/components/icon/src/Icon.vue

refactor(cdk:utils): isNumber renamed to isNumberic

---

docs/contributing.zh.md

docs: contributing.zh.md

---

scripts/gulp/site/_site/docs/src/index.less
scripts/gulp/site/_site/docs/src/styles/reset.less
scripts/gulp/site/_site/docs/src/styles/side-nav.less

docs: reset li style

---

packages/cdk/utils/__tests__/typeof.spec.ts
packages/cdk/utils/typeof.ts

add unified type check until functions
feat #77
when component developer develop an component that need check a variable‘ s type，he/her need to write a type check funcion
the developer just use the type check function that in ckd/utils/typeof

feat(cdk:utils): add type check util function

---

packages/cdk/utils/typeof.ts
packages/components/badge/src/types.ts
packages/components/button/index.ts
packages/components/button/src/types.ts
packages/components/divider/src/types.ts
packages/components/icon/index.ts
packages/components/icon/src/types.ts
packages/components/image/src/types.ts
scripts/gen/index.ts
scripts/gen/template.ts

refactor(comp:all): updalte all components ts definition

---

scripts/gulp/site/generateSite.ts

fix: vite traverse filename config

---

packages/components/divider/src/Divider.vue

fix(comp: divider): slots rerender

---

.ls-lint.yml
docs/i18n.zh.md
packages/components/i18n/__tests__/useI18n.spec.ts
packages/components/i18n/languages/en_US.ts
packages/components/i18n/languages/es_ES.ts
packages/components/i18n/languages/index.ts
packages/components/i18n/languages/zh_CN.ts
packages/components/i18n/languages/zh_TW.ts
packages/components/i18n/locales/en-US.ts
packages/components/i18n/locales/zh-CN.ts
packages/components/i18n/types.ts
packages/components/i18n/useI18n.ts

refactor(comp:i18n): update useI18n to useLocale

---

packages/cdk/utils/vNode.ts
packages/components/badge/src/Badge.vue
packages/components/badge/src/types.ts
packages/components/button/src/Button.vue
packages/components/divider/src/Divider.vue
packages/components/icon/src/Icon.vue
packages/components/space/src/Space.vue
packages/components/space/src/types.ts
packages/components/spin/src/Spin.vue
packages/components/spin/src/types.ts

fix(comp:all): slot dynamic load

---

packages/components/index.ts
scripts/gen/index.ts

refactor: script gen type structure

---

packages/components/badge/src/types.ts
packages/components/button/src/types.ts
packages/components/divider/src/types.ts
packages/components/icon/src/types.ts
packages/components/image/src/types.ts
packages/components/space/src/types.ts
packages/components/spin/src/types.ts
scripts/gen/template.ts

Update the template to make it more simpler.

refactor: script gen types template

---

CONTRIBUTING.md
docs/contributing.en.md
docs/contributing.zh.md

update contributing.zh and add contributing.en

docs: contribution

---

packages/components/image/index.ts

fix(comp: image): export type to fix vite error

---

packages/cdk/forms/docs/index.zh.md

docs(cdk:forms): add validators docs

---

packages/components/divider/docs/index.zh.md
packages/components/image/docs/index.zh.md
packages/components/space/docs/index.zh.md
packages/components/spin/docs/index.zh.md

docs: modify components' docs' type

---

packages/cdk/utils/__tests__/typeof.spec.ts
packages/cdk/utils/typeof.ts

feat(cdk:utils): add hasOwnProperty function

---

packages/components/badge/__tests__/__snapshots__/badge.spec.ts.snap
packages/components/badge/__tests__/badge.spec.ts
packages/components/badge/demo/Basic.vue
packages/components/badge/docs/index.zh.md
packages/components/badge/src/Badge.vue

fix(comp: badge): overflowCount not work (#134)

---

packages/cdk/forms/__tests__/abstractControl.spec.ts
packages/cdk/forms/src/controls/abstractControl.ts

feat(cdk:forms): add watchValue and watchStatus

---

packages/cdk/forms/__tests__/formControl.spec.ts
packages/cdk/forms/src/controls/abstractControl.ts
packages/cdk/forms/src/controls/formArray.ts
packages/cdk/forms/src/controls/formControl.ts
packages/cdk/forms/src/controls/formGroup.ts

feat(cdk:forms): setValue support configuration options

---

typings/global.d.ts

feat: add global types

---

packages/cdk/forms/__tests__/abstractControl.spec.ts
packages/cdk/forms/__tests__/formArray.spec.ts
packages/cdk/forms/__tests__/formControl.spec.ts
packages/cdk/forms/__tests__/formGroup.spec.ts
packages/cdk/forms/__tests__/typeof.spec.ts
packages/cdk/forms/__tests__/useForms.spec.ts
packages/cdk/forms/docs/index.zh.md
packages/cdk/forms/src/controls/abstractControl.ts
packages/cdk/forms/src/controls/formArray.ts
packages/cdk/forms/src/controls/formControl.ts
packages/cdk/forms/src/controls/formGroup.ts
packages/cdk/forms/src/controls/types.ts
packages/cdk/forms/src/useForms.ts

refactor(cdk:forms): update typescript defintions

---

packages/cdk/subject/__tests__/subject.spec.ts
packages/cdk/subject/demo/basic.md
packages/cdk/subject/docs/index.zh.md
packages/cdk/subject/index.ts
packages/cdk/subject/src/subject.ts
packages/cdk/subject/src/type.ts

feat(cdk: subject): add subject

---

packages/components/typography/src/typography.ts

style(comp: typography): modify code style

---

packages/components/badge/docs/index.zh.md
packages/components/rate/docs/index.zh.md
packages/components/rate/src/Rate.vue
packages/components/typography/__tests__/typography.spec.ts

docs: update docs and fix test warning

---

scripts/gen/index.ts

ci: fix gen script

---

scripts/vite/md/parseGlobalDocs.ts
scripts/vite/md/parsePackageDemo.ts
scripts/vite/md/parsePackageDocs.ts

fix: site work with windows

---

packages/components/core/utils/easingFunctions.ts
packages/components/style/motion/fade.less
packages/components/style/motion/move.less
packages/components/style/motion/slide.less
packages/components/style/motion/zoom.less
packages/components/style/variable/animation.less

feat(comp:style): add css transition

---

packages/components/checkbox/docs/index.zh.md
packages/components/checkbox/style/index.less

fix(comp: checkbox): doc and style

---

.gitignore

build: ignore old site files

---

packages/components/icon/src/utils.ts
site/docs/styles/code-box.less

refactor(comp:icons): set svg viewbox

---

packages/components/button/docs/index.zh.md
packages/components/button/style/mixin.less
packages/components/checkbox/docs/index.zh.md
packages/components/divider/style/index.less
packages/components/input/docs/index.zh.md
packages/components/style/default.less
packages/components/style/variable/border.less
packages/components/style/variable/color/color.less
packages/components/typography/docs/index.zh.md
site/docs/styles/code-box.less
site/docs/styles/markdown.less

refactor: color variable

---

packages/components/icon/__tests__/__snapshots__/icon.spec.ts.snap

test: fix icon test

---

packages/cdk/clipboard/__tests__/useClipboard.spec.ts
packages/cdk/overlay/__tests__/overlay.spec.ts
packages/cdk/overlay/src/useOverlay.ts
packages/cdk/utils/dom.ts
packages/cdk/utils/typeof.ts
packages/components/back-top/__test__/backTop.spec.ts
packages/components/back-top/src/BackTop.vue
packages/components/core/logger/index.ts
packages/components/core/utils/easingFunctions.ts
packages/components/core/utils/installComponent.ts
packages/components/i18n/useI18n.ts
packages/components/input/src/useAutoRows.ts
tests/utils.ts
typings/global.d.ts

refactor: update utils and test

---

packages/components/typography/__tests__/typography.spec.ts
packages/components/typography/src/typography.ts

fix(comp: typography): fix custom class

---

packages/cdk/overlay/demo/Portal.vue
packages/cdk/overlay/demo/portal.md
packages/cdk/overlay/docs/index.zh.md

docs(cdk: overlay): add overlay docs with portal

---

packages/cdk/breakpoint/docs/index.zh.md

docs(breakpoints): update breakpoints docs

---

.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/feature-request.zh.md
.github/pull_request_template.md
CONTRIBUTING.md
README.md
docs/contributing.en.md
docs/contributing.zh.md
docs/global-config.zh.md
packages/cdk/package.json
packages/components/button/demo/Block.vue
packages/components/button/demo/Danger.vue
packages/components/button/demo/Disabled.vue
packages/components/button/demo/Loding.vue
packages/components/button/demo/Mode.vue
packages/components/button/demo/Shape.vue
packages/components/button/demo/Size.vue
packages/components/package.json.backup
packages/components/typography/demo/Text.vue
packages/pro/package.json
scripts/vite/md/generateTitle.ts
site/docs/shared/CodeBox.vue

docs: update all github link

---

package.json
scripts/vite/mdPlugin.ts
vite.config.ts

refactor: add jsx support

---

packages/cdk/utils/__tests__/dom.spec.ts
packages/cdk/utils/dom.ts
packages/components/typography/__tests__/__snapshots__/typography.spec.ts.snap
packages/components/typography/__tests__/typography.spec.ts
packages/components/typography/src/typography.ts

refactor(comp: typography): modify code and test

---

README.md
azure-pipelines.yml
docs/contributing.en.md
docs/contributing.zh.md
package.json

ci: update azure-pipelines

---

packages/components/style/default.less

fix: default.less use a wrong variable

---

packages/cdk/utils/dom.ts

after a component is unMounted, we need to clear the rAF tasks to avoid memory leak.
there is no way to cancel a rAF task now.
add throttleRAF function. it returns a function with a cacel function. we can call this cancel function when a component is unMounted.

feat(utils: dom): add throttleRAF function

---

packages/cdk/overlay/demo/Portal.vue
packages/components/components.less
packages/components/core/config/__tests__/format.spec.ts
packages/components/core/config/defaultConfig.ts
packages/components/core/config/numFormatter.ts
packages/components/core/config/types.ts
packages/components/index.ts
packages/components/statistic/__tests__/__snapshots__/statistic.spec.ts.snap
packages/components/statistic/__tests__/statistic.spec.ts
packages/components/statistic/demo/Basic.vue
packages/components/statistic/demo/Unit.vue
packages/components/statistic/demo/basic.md
packages/components/statistic/demo/unit.md
packages/components/statistic/docs/index.zh.md
packages/components/statistic/index.ts
packages/components/statistic/src/Statistic.vue
packages/components/statistic/src/types.ts
packages/components/statistic/style/index.less
packages/components/style/default.less

fix #95
dont hava statistic compoenent
have the statistic compoenent

feat(comp: statistic): add statistic component

---

package.json
packages/components/affix/__tests__/__snapshots__/affix.spec.ts.snap
packages/components/input/__tests__/__snapshots__/input.spec.ts.snap
scripts/gulp/gulpfile.ts
scripts/gulp/tasks/site.ts

ci: fix input test and add gulp build task

---

azure-pipelines.yml

ci: update azure config

---

packages/components/affix/__tests__/affix.spec.ts

test of affix run failed
test of affix  run successful

ci: 修复affix的test

---

packages/cdk/breakpoint/__tests__/mediaMatcher.spec.ts
packages/cdk/breakpoint/__tests__/observe.spec.ts
packages/cdk/breakpoint/demo/Basic.vue
packages/cdk/breakpoint/src/breakpoints.ts

refactor(cdk:breakpoint): update Breakpoints keys

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/bug_report.zh.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/feature-request.zh.md
scripts/gen/index.ts
scripts/gen/template.ts

docs: update docs template

---

packages/components/back-top/style/index.less
packages/components/badge/style/index.less
packages/components/button/style/index.less
packages/components/checkbox/style/index.less
packages/components/image/style/index.less
packages/components/spin/style/index.less
packages/components/style/default.less
packages/components/style/variable/index.less
packages/components/style/variable/zindex.less

feat(comp:all): add zindex variable

---

packages/cdk/overlay/demo/Basic.vue
packages/cdk/overlay/demo/Portal.vue
packages/cdk/overlay/src/useOverlay.ts

refactor(cdk: overlay): fix dynamic problem

---

packages/components/message/__tests__/message.spec.ts

test(comp:message): shorten message duration time

---

packages/components/badge/style/index.less
packages/components/button/docs/index.zh.md
packages/components/checkbox/docs/index.zh.md
packages/components/core/config/defaultConfig.ts
packages/components/divider/style/index.less
packages/components/empty/docs/index.zh.md
packages/components/icon/src/icons.ts
packages/components/input/docs/index.zh.md
packages/components/message/__tests__/message.spec.ts
packages/components/message/src/types.ts
packages/components/progress/__tests__/progress.spec.ts
packages/components/progress/demo/circle.md
packages/components/progress/demo/dashboard.md
packages/components/progress/demo/gradient.md
packages/components/progress/demo/round.md
packages/components/progress/docs/index.zh.md
packages/components/progress/src/types.ts
packages/components/progress/src/useCommonLogic.ts
packages/components/progress/src/util.ts
packages/components/progress/style/index.less
packages/components/result/docs/index.zh.md
packages/components/spin/docs/index.zh.md
packages/components/style/default.less
packages/components/style/variable/font.less
packages/components/typography/docs/index.zh.md
site/docs/styles/global/code-box.less
site/docs/styles/highlight.less
site/docs/styles/markdown.less
site/docs/styles/reset.less

refactor(comp:all): update font size variable

---

package.json
packages/cdk/package.json
packages/cdk/utils/__tests__/dom.spec.ts
packages/cdk/utils/dom.ts

feat(cdk:utils): add resize listtener utils

---

packages/components/components.less
packages/components/index.ts
packages/components/style/default.less
packages/components/switch/__tests__/__snapshots__/switch.spec.ts.snap
packages/components/switch/__tests__/switch.spec.ts
packages/components/switch/demo/Basic.vue
packages/components/switch/demo/Disabled.vue
packages/components/switch/demo/Focus.vue
packages/components/switch/demo/Inner.vue
packages/components/switch/demo/Loading.vue
packages/components/switch/demo/Size.vue
packages/components/switch/demo/basic.md
packages/components/switch/demo/disabled.md
packages/components/switch/demo/focus.md
packages/components/switch/demo/inner.md
packages/components/switch/demo/loading.md
packages/components/switch/demo/size.md
packages/components/switch/docs/index.zh.md
packages/components/switch/index.ts
packages/components/switch/src/Switch.vue
packages/components/switch/src/types.ts
packages/components/switch/style/index.less

add switch component, test, demo

feat(comp:switch): add switch component

---

packages/cdk/breakpoint/src/observe.ts
packages/cdk/click-outside/__tests__/clickOutside.spec.ts
packages/cdk/clipboard/src/useClipboard.ts
packages/cdk/forms/__tests__/validators.spec.ts
packages/cdk/forms/src/controls/abstractControl.ts
packages/cdk/portal/__tests__/portal.spec.ts
packages/cdk/utils/__tests__/propTypes.spec.ts
packages/components/button/__tests__/buttonGroup.spec.ts
packages/components/button/src/Button.vue
packages/components/checkbox/docs/index.zh.md
packages/components/checkbox/src/checkboxSetup.ts
packages/components/checkbox/src/types.ts
packages/components/core/config/useGlobalConfig.ts
packages/components/core/utils/useAttrs.ts
packages/components/icon/src/utils.ts
packages/components/index.ts
packages/components/input/src/useAutoRows.ts
packages/components/space/__tests__/space.spec.ts
packages/components/switch/__tests__/switch.spec.ts
packages/components/switch/docs/index.zh.md
packages/components/switch/index.ts
packages/components/switch/src/Switch.vue
packages/components/switch/src/types.ts
packages/components/typography/__tests__/typography.spec.ts
scripts/vite/md/marked.ts
tsconfig.json

fix: test and lint

---

packages/components/switch/index.ts

fix(comp:switch): export type

---

scripts/gulp/site/index.ts

fix(scripts): make sure the directory is correct

---

.gitignore

refactor: add pnpm lock ignore

---

package.json

修复pnpm安装依赖问题，新增 `@babel/core` 移出安装依赖的警告

fix: dependencies warning

---

packages/cdk/click-outside/__tests__/clickOutside.spec.ts
packages/cdk/click-outside/demo/Basic.vue
packages/cdk/click-outside/docs/Index.zh.md
packages/cdk/click-outside/src/useClickOutside.ts
packages/cdk/utils/typeof.ts

fix(cdk: click-outside): fix click-outside bug

---

scripts/gen/generate.ts
scripts/gen/template.ts

refactor: add tsx template

---

packages/components/components.less
packages/components/index.ts
packages/site/src/iduxComponents.ts
scripts/gen/generate.ts
scripts/gen/template.ts

refactor: gen auto import

---

packages/components/components.less
packages/components/config/src/types.ts
packages/components/i18n/__tests__/useI18n.spec.ts
packages/components/index.ts
packages/components/input/__tests__/__snapshots__/textarea.spec.ts.snap
packages/components/input/docs/Index.zh.md
packages/components/radio/docs/Index.zh.md
packages/components/radio/index.ts
packages/site/src/iduxComponents.ts

fix: build error with radio

---

packages/components/affix/__tests__/affix.spec.ts
packages/components/badge/__tests__/badge.spec.ts
packages/components/button/__tests__/button.spec.ts
packages/components/card/__tests__/card.spec.ts
packages/components/checkbox/__tests__/checkbox.spec.ts
packages/components/checkbox/__tests__/checkboxGroup.spec.ts
packages/components/divider/__tests__/divider.spec.ts
packages/components/empty/__tests__/empty.spec.ts
packages/components/icon/__tests__/icon.spec.ts
packages/components/image/__tests__/image.spec.ts
packages/components/input/__tests__/input.spec.ts
packages/components/input/__tests__/textarea.spec.ts
packages/components/popover/__tests__/popover.spec.ts
packages/components/progress/__tests__/progress.spec.ts
packages/components/radio/__tests__/radio.spec.ts
packages/components/radio/__tests__/radioButton.spec.ts
packages/components/radio/__tests__/radioGroup.spec.ts
packages/components/rate/__tests__/rate.spec.ts
packages/components/result/__tests__/result.spec.ts
packages/components/spin/__tests__/spin.spec.ts
packages/components/statistic/__tests__/statistic.spec.ts
packages/components/switch/__tests__/switch.spec.ts
packages/components/timeline/__tests__/timeline.spec.ts
packages/components/timeline/__tests__/timelineItem.spec.ts
packages/components/title/__tests__/title.spec.ts
packages/components/tooltip/__tests__/tooltip.spec.ts
packages/components/typography/__tests__/typography.spec.ts
scripts/gen/template.ts

test: fix types

---

packages/components/popover/__tests__/popover.spec.ts
packages/components/tooltip/__tests__/tooltip.spec.ts
packages/components/typography/__tests__/typography.spec.ts

ci: fix lint error

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md

docs: update some template links in readme

---

packages/components/icon/src/utils.ts

fix(comp:icon): cached icons failed to load

---

package.json
scripts/gulp/taskHelpers.ts

build(scripts): fix execNodeTask in windows

---

packages/components/style/dark.less
packages/components/style/default.less
packages/components/style/variable/color/color.less

feat(comp:style): add dark color

---

packages/components/message/style/index.less
packages/components/style/motion/fade.less
packages/components/style/motion/move.less
packages/components/style/motion/slide.less
packages/components/style/motion/zoom.less
packages/components/style/variable/animation.less

delete the useless code in CSS transiton.

refactor(comp:style): delete the useless code in transition

---

packages/components/input/docs/Index.zh.md
packages/components/input/style/mixin.less
packages/components/result/docs/Index.zh.md
packages/components/style/default.less
packages/components/typography/docs/Index.zh.md
packages/components/typography/style/index.less
packages/site/src/styles/global/codebox.less
packages/site/src/styles/markdown.less

refactor(comp:style): @text-secondary-color to @text-color-secondary

---

packages/cdk/overlay/__tests__/overlay.spec.ts
packages/cdk/overlay/docs/Index.zh.md
packages/cdk/overlay/src/types.ts
packages/cdk/overlay/src/useOverlay.ts
packages/cdk/overlay/src/usePopperOptions.ts
packages/components/config/src/types.ts
packages/components/popover/docs/Index.zh.md
packages/components/select/__tests__/select.spec.ts
packages/components/select/src/useSelect.ts
packages/components/tooltip/docs/Index.zh.md
packages/components/tooltip/src/types.ts

refactor(cdk:overlay): performance and API optimization

---

packages/components/collapse/__tests__/collapse.spec.ts
packages/components/collapse/demo/Accordion.md
packages/components/collapse/demo/Accordion.vue
packages/components/collapse/demo/Basic.md
packages/components/collapse/demo/Basic.vue
packages/components/collapse/demo/Borderless.md
packages/components/collapse/demo/Borderless.vue
packages/components/collapse/demo/Custom.md
packages/components/collapse/demo/Custom.vue
packages/components/collapse/demo/Mix.md
packages/components/collapse/demo/Mix.vue
packages/components/collapse/docs/Index.en.md
packages/components/collapse/docs/Index.zh.md
packages/components/collapse/index.ts
packages/components/collapse/src/Collapse.vue
packages/components/collapse/src/CollapsePanel.vue
packages/components/collapse/src/CollapsePanelHeader.vue
packages/components/collapse/src/types.ts
packages/components/collapse/src/useCollpase.ts
packages/components/collapse/style/index.less
packages/components/components.less
packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/index.ts
packages/components/style/default.less
packages/site/src/iduxComponents.ts

feat(comp: collapse): add collapse component

---

packages/components/style/dark.less
packages/components/style/variable/color/color.less
packages/components/style/variable/color/colorPalette.less
packages/components/utils/src/colors.ts
packages/site/src/global/Colors.vue
packages/site/src/styles/global/colors.less

refactor(comp:style): update color

---

packages/cdk/portal/__tests__/__snapshots__/portal.spec.ts.snap
packages/cdk/portal/__tests__/portal.spec.ts
packages/components/affix/__tests__/__snapshots__/affix.spec.ts.snap
packages/components/back-top/__test__/__snapshots__/backTop.spec.ts.snap
packages/components/button/__tests__/__snapshots__/button.spec.ts.snap
packages/components/button/__tests__/__snapshots__/buttonGroup.spec.ts.snap
packages/components/card/__tests__/__snapshots__/card.spec.ts.snap
packages/components/collapse/__tests__/__snapshots__/collapse.spec.ts.snap
packages/components/collapse/__tests__/collapse.spec.ts
packages/components/collapse/src/Collapse.vue
packages/components/divider/__tests__/__snapshots__/divider.spec.ts.snap
packages/components/empty/__tests__/__snapshots__/empty.spec.ts.snap
packages/components/grid/__tests__/__snapshots__/grid.spec.ts.snap
packages/components/image/__tests__/__snapshots__/image.spec.ts.snap
packages/components/input/__tests__/__snapshots__/input.spec.ts.snap
packages/components/menu/__tests__/__snapshots__/menu.spec.ts.snap
packages/components/menu/__tests__/menu.spec.ts
packages/components/progress/__tests__/__snapshots__/progress.spec.ts.snap
packages/components/rate/__tests__/__snapshots__/rate.spec.ts.snap
packages/components/result/__tests__/__snapshots__/result.spec.ts.snap
packages/components/select/__tests__/__snapshots__/option.spec.ts.snap
packages/components/select/__tests__/__snapshots__/select.spec.ts.snap
packages/components/space/__tests__/__snapshots__/space.spec.ts.snap
packages/components/spin/__tests__/__snapshots__/spin.spec.ts.snap
packages/components/statistic/__tests__/__snapshots__/statistic.spec.ts.snap
packages/components/switch/__tests__/__snapshots__/switch.spec.ts.snap
packages/components/timeline/__tests__/__snapshots__/timeline.spec.ts.snap
packages/components/timeline/__tests__/__snapshots__/timelineItem.spec.ts.snap
packages/components/title/__tests__/__snapshots__/title.spec.ts.snap

test: fix snapshots style

---

packages/components/timeline/__tests__/__snapshots__/timeline.spec.ts.snap
packages/components/timeline/__tests__/__snapshots__/timelineItem.spec.ts.snap

test(comp:timeline): fix snapshots

---

packages/components/menu/style/menu.less
packages/site/src/App.vue
packages/site/src/layout/header/Index.vue
scripts/gulp/site/utils.ts

fix(comp:menu): add a::before

---

packages/components/anchor/__tests__/__snapshots__/anchor.spec.ts.snap
packages/components/anchor/__tests__/anchor.spec.ts
packages/components/anchor/demo/Basic.md
packages/components/anchor/demo/Basic.vue
packages/components/anchor/demo/Static.md
packages/components/anchor/demo/Static.vue
packages/components/anchor/demo/TargetOffset.md
packages/components/anchor/demo/TargetOffset.vue
packages/components/anchor/docs/Index.zh.md
packages/components/anchor/index.ts
packages/components/anchor/src/Anchor.vue
packages/components/anchor/src/Link.vue
packages/components/anchor/src/types.ts
packages/components/anchor/src/util.ts
packages/components/anchor/style/index.less
packages/components/components.less
packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/index.ts
packages/components/style/default.less
packages/components/utils/src/easingFunctions.ts
packages/site/src/iduxComponents.ts

feat(comp: anchor): add anchor component

---

packages/components/anchor/__tests__/__snapshots__/anchor.spec.ts.snap
packages/components/anchor/__tests__/anchor.spec.ts
packages/components/anchor/docs/Index.zh.md
packages/components/anchor/src/Anchor.vue
packages/components/anchor/src/Link.vue
packages/components/anchor/src/token.ts
packages/components/anchor/src/types.ts
packages/components/anchor/src/util.ts
packages/components/anchor/style/index.less
packages/components/config/src/types.ts
packages/components/menu/src/menu/Menu.vue
packages/components/menu/src/menu/MenuItem.vue
packages/components/menu/src/menu/MenuItemGroup.vue
packages/components/menu/src/sub-menu/SubMenu.vue
packages/components/menu/src/sub-menu/SubMenuOverlayContent.vue
packages/components/menu/src/types.ts
packages/components/progress/src/Circle.vue
packages/components/progress/src/Line.vue
packages/components/progress/src/Progress.vue
packages/components/progress/src/types.ts
packages/components/select/src/Option.vue
packages/components/select/src/OptionGroup.vue
packages/components/select/src/Select.vue
packages/components/select/src/types.ts
packages/components/style/default.less
scripts/gen/generate.ts
scripts/gen/template.ts

fix: build script

---

packages/site/src/main.ts
scripts/gen/generate.ts
scripts/gen/template.ts

docs: fix gen and add site scroll behavior

---

packages/cdk/overlay/index.ts
packages/cdk/overlay/src/types.ts

feat(cdk: overlay): add prop-types export

---

packages/cdk/utils/src/easings.ts

1. duration=0 and elapsed=0, return NaN
2. duration=0 and elapsed>0, return Infinity
when duration=0, return value of amountOfChange

fix: easing functions might return NaN or Infinity when duration=0

---

jest.config.js
packages/cdk/utils/src/dom.ts
packages/cdk/utils/src/scroll.ts
packages/cdk/utils/src/typeof.ts
packages/cdk/virtual-list/__tests__/__snapshots__/list.spec.ts.snap
packages/cdk/virtual-list/__tests__/list.spec.ts
packages/cdk/virtual-list/demo/Basic.md
packages/cdk/virtual-list/demo/Basic.vue
packages/cdk/virtual-list/demo/Switch.md
packages/cdk/virtual-list/demo/Switch.vue
packages/cdk/virtual-list/docs/Index.en.md
packages/cdk/virtual-list/docs/Index.zh.md
packages/cdk/virtual-list/index.ts
packages/cdk/virtual-list/src/filler.tsx
packages/cdk/virtual-list/src/item.tsx
packages/cdk/virtual-list/src/list.tsx
packages/cdk/virtual-list/src/scrollBar.tsx
packages/cdk/virtual-list/src/types.ts
packages/cdk/virtual-list/src/utils/useEvents.ts
packages/cdk/virtual-list/src/utils/useItem.ts
packages/cdk/virtual-list/src/utils/useScrollBar.ts
packages/cdk/virtual-list/src/utils/useScrollTo.ts
packages/components/dropdown/src/Dropdown.vue
packages/components/dropdown/src/DropdownButton.vue
packages/site/src/iduxCdk.ts
typings/global.d.ts

feat(cdk:virtual-list): add virtual-list

---

packages/components/checkbox/docs/Index.zh.md
packages/components/checkbox/style/index.less
packages/components/spin/demo/Basic.vue
packages/components/spin/demo/Icon.vue
packages/components/spin/demo/Size.md
packages/components/spin/demo/Size.vue
packages/components/spin/demo/Tip.vue
packages/components/spin/docs/Index.zh.md
packages/components/spin/style/index.less
packages/components/style/default.less

Refactor the style problem of checkbox and spin components

style: fix spin and checkbox style

---

packages/components/button/__tests__/__snapshots__/button.spec.ts.snap
packages/components/button/__tests__/__snapshots__/buttonGroup.spec.ts.snap
packages/components/button/docs/Index.zh.md
packages/components/button/src/Button.vue
packages/components/button/src/ButtonGroup.vue
packages/components/button/src/types.ts
packages/components/space/__tests__/__snapshots__/space.spec.ts.snap

feat(comp:button): add type props

---

packages/site/plugins/mdPlugin.ts
packages/site/plugins/transformIndexPlugin.ts
packages/site/vite.config.ts

build: add transform index html plugin

---

packages/components/checkbox/__tests__/checkbox.spec.ts

checkbox 组件的focus和blur方法未写测试案例
补充测试案例，并通过

refactor(comp:checkbox): add focus and blur test units

---

packages/cdk/forms/src/useValueAccessor.ts
packages/cdk/utils/src/props.ts
packages/components/input/__tests__/input.spec.ts
packages/components/input/__tests__/textarea.spec.ts
packages/components/input/demo/PrefixSuffix.vue
packages/components/input/docs/Index.zh.md
packages/components/input/src/Input.vue
packages/components/input/src/Textarea.vue
packages/components/input/src/types.ts
packages/components/input/src/useCommonBindings.ts

refactor(comp:input): remove emits

---

packages/components/config/src/types.ts
packages/components/form/src/Form.vue
packages/components/form/src/token.ts
packages/components/input/src/useAutoRows.ts
packages/components/menu/src/menu/useMenu.ts
packages/components/menu/src/token.ts
packages/components/pagination/src/Pagination.tsx
packages/components/pagination/src/Simple.vue
packages/components/radio/index.ts
packages/components/radio/src/types.ts
packages/components/result/src/Result.vue
packages/components/space/__tests__/space.spec.ts
packages/components/space/src/Space.tsx
packages/components/spin/index.ts
packages/components/spin/src/types.ts
packages/components/steps/index.ts
packages/components/steps/src/types.ts

fix(comp:config): move type

---

package.json

re https://github.com/vitejs/vite/issues/4139

build: lock vite version with ~v2.3.0

---

packages/site/src/iduxComponents.ts

fix: site components types

---

packages/components/header/__tests__/header.spec.ts
packages/components/header/demo/Extra.vue
packages/components/header/src/Header.tsx
packages/components/header/src/types.ts
packages/components/modal/__tests__/modal.spec.ts
packages/components/modal/docs/Index.zh.md
packages/components/modal/src/ModalHeader.tsx
packages/components/modal/src/types.ts

refactor(comp:header): 'extra' should support Vnode, not string array

---

packages/components/list/__tests__/__snapshots__/list.spec.ts.snap
packages/components/spin/index.ts
packages/components/spin/src/Spin.tsx

refactor(comp:spin): refactor code with tsx

---

scripts/gen/generate.ts

fix: generate private components script

---

packages/cdk/popper/__tests__/popper.spec.ts
packages/cdk/popper/demo/Basic.md
packages/cdk/popper/demo/Basic.vue
packages/cdk/popper/demo/Placement.md
packages/cdk/popper/demo/Placement.vue
packages/cdk/popper/demo/ScrollStrategy.md
packages/cdk/popper/demo/ScrollStrategy.vue
packages/cdk/popper/demo/Trigger.md
packages/cdk/popper/demo/Trigger.vue
packages/cdk/popper/docs/Index.en.md
packages/cdk/popper/docs/Index.zh.md
packages/cdk/popper/index.ts
packages/cdk/popper/src/hooks.ts
packages/cdk/popper/src/types.ts
packages/cdk/popper/src/usePopper.ts
packages/cdk/popper/src/utils.ts

feat(cdk: popper): add cdk popper

---

packages/components/style/variable/color/color.less
packages/components/style/variable/color/colorPalette.less

refactor(comp:style): update color base

---

packages/cdk/utils/src/vNode.ts

fix(cdk: utils): has slot

---

packages/components/affix/src/Affix.tsx
packages/components/anchor/__tests__/__snapshots__/anchor.spec.ts.snap

position is incorrect
position is correct

fix: fix affix wrapper style

---

packages/components/_private/overlay/src/Overlay.tsx
packages/components/popover/__tests__/__snapshots__/popover.spec.ts.snap
packages/components/popover/src/Popover.tsx
packages/components/tooltip/__tests__/__snapshots__/tooltip.spec.ts.snap
packages/components/tooltip/src/Tooltip.tsx

style(comp: overlay): optimize the code

---

packages/components/_private/overlay/__tests__/__snapshots__/overlay.spec.ts.snap
packages/components/_private/overlay/__tests__/overlay.spec.ts
packages/components/_private/overlay/src/Overlay.tsx
packages/components/_private/overlay/src/hooks.ts
packages/components/_private/overlay/src/types.ts
packages/components/_private/overlay/src/utils.ts

fix(comp:overlay): render test add slots

---

packages/cdk/popper/__tests__/popper.spec.ts
packages/cdk/popper/demo/Trigger.vue
packages/cdk/popper/src/hooks.ts
packages/cdk/popper/src/types.ts
packages/cdk/popper/src/usePopper.ts
packages/cdk/popper/src/utils.ts
packages/components/_private/overlay/index.ts
packages/components/_private/overlay/src/Overlay.tsx
packages/components/_private/overlay/src/types.ts
packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/popover/docs/Index.zh.md
packages/components/popover/src/Popover.tsx
packages/components/tooltip/docs/Index.zh.md
packages/components/tooltip/src/Tooltip.tsx
packages/components/tooltip/src/hooks.ts
packages/components/tooltip/src/types.ts

refactor(cdk:popper): rebuild delay props

---

packages/components/components.less
packages/components/index.ts
packages/components/table/demo/Basic.md
packages/components/table/demo/Basic.vue
packages/components/table/docs/Index.en.md
packages/components/table/docs/Index.zh.md
packages/components/table/index.ts
packages/components/table/src/Table.tsx
packages/components/table/src/token.ts
packages/components/table/src/types.ts
packages/components/table/style/index.less
packages/site/src/iduxComponents.ts

feat(comp:table): api design

---

packages/components/anchor/docs/Index.zh.md

docs: supplement anchor component documentation

---

packages/components/button/style/mixin.less

refactor(comp:button): remove repeat style

---

packages/site/plugins/md/parsePackageDemo.ts
packages/site/plugins/md/template.ts
packages/site/src/components/global/CodeBox.vue

feat: site add code copy function

---

packages/components/anchor/docs/Index.zh.md
packages/components/button/style/mixin.less
packages/components/components.less
packages/components/index.ts
packages/components/table/demo/Basic.md
packages/components/table/demo/Basic.vue
packages/components/table/docs/Index.en.md
packages/components/table/docs/Index.zh.md
packages/components/table/index.ts
packages/components/table/src/Table.tsx
packages/components/table/src/token.ts
packages/components/table/src/types.ts
packages/components/table/style/index.less
packages/site/plugins/md/parsePackageDemo.ts
packages/site/plugins/md/template.ts
packages/site/src/components/global/CodeBox.vue
packages/site/src/iduxComponents.ts

feat(comp:table): code rebase

---

packages/components/table/src/main/head/HeadCol.tsx
packages/components/table/src/types.ts
packages/components/table/style/index.less
packages/components/table/style/size.less

feat(comp:table): update style

---

packages/components/style/variable/color/color.less

refactor(comp:style): reset color variable

---

packages/components/table/docs/Index.zh.md
packages/components/table/src/Table.tsx
packages/components/table/src/composables/useColumns.ts
packages/components/table/src/composables/useDataSource.ts
packages/components/table/src/main/body/BodyRow.tsx
packages/components/table/src/types.ts
packages/site/plugins/md/marked.ts

feat(comp:table): support childrenKey in expandable

---

packages/components/components.less
packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/drawer/__tests__/drawer.spec.ts
packages/components/drawer/demo/Basic.md
packages/components/drawer/demo/Basic.vue
packages/components/drawer/demo/MultiDrawer.md
packages/components/drawer/demo/MultiDrawer.vue
packages/components/drawer/demo/NoTitle.md
packages/components/drawer/demo/NoTitle.vue
packages/components/drawer/demo/Placement.md
packages/components/drawer/demo/Placement.vue
packages/components/drawer/demo/Slot.md
packages/components/drawer/demo/Slot.vue
packages/components/drawer/demo/WidthAndHeight.md
packages/components/drawer/demo/WidthAndHeight.vue
packages/components/drawer/docs/Index.en.md
packages/components/drawer/docs/Index.zh.md
packages/components/drawer/index.ts
packages/components/drawer/src/Drawer.tsx
packages/components/drawer/src/DrawerBody.tsx
packages/components/drawer/src/DrawerWrapper.tsx
packages/components/drawer/src/token.ts
packages/components/drawer/src/types.ts
packages/components/drawer/style/index.less
packages/components/index.ts
packages/site/src/iduxComponents.ts

feat(comp:drawer): add drawer component

feat(comp:drawer): add drawer component

---

packages/components/table/demo/Fixed.vue
packages/components/table/demo/Server.vue
packages/components/table/src/composables/useColumns.ts
packages/components/table/src/composables/useScroll.ts
packages/components/table/src/main/ColGroup.tsx
packages/components/table/src/main/FixedHolder.tsx
packages/components/table/src/main/MainTable.tsx
packages/components/table/src/main/body/Body.tsx
packages/components/table/src/main/body/BodyCol.tsx
packages/components/table/src/main/body/BodyColExpandable.tsx
packages/components/table/src/main/body/BodyCollSelectable.tsx
packages/components/table/src/main/body/BodyRow.tsx
packages/components/table/src/main/body/BodyRowSingle.tsx
packages/components/table/src/main/head/HeadCol.tsx
packages/components/table/src/main/head/HeadColExpandable.tsx
packages/components/table/src/main/head/HeadColSelectable.tsx
packages/components/table/src/main/head/HeadRow.tsx
packages/components/table/style/fixed.less
packages/components/table/style/index.less
packages/components/table/style/radius.less
packages/components/table/style/size.less

fix(comp:table): fix fixed column style

---

packages/components/checkbox/src/Checkbox.tsx
packages/components/checkbox/src/CheckboxGroup.tsx
packages/components/form/demo/Basic.vue
packages/components/form/demo/Coordinated.vue
packages/components/form/demo/DynamicItem.vue
packages/components/form/demo/Message.vue
packages/components/form/demo/Nest.vue
packages/components/form/demo/Register.vue
packages/components/form/demo/Search.vue
packages/components/form/docs/Index.zh.md
packages/components/form/index.ts
packages/components/form/src/FormItem.tsx
packages/components/form/src/token.ts
packages/components/index.ts
packages/components/input/docs/Index.zh.md
packages/components/input/src/useCommonBindings.ts
packages/components/radio/src/Radio.tsx
packages/components/radio/src/RadioGroup.tsx
packages/components/select/docs/Index.zh.md
packages/components/select/src/useSelect.ts
packages/components/switch/src/Switch.tsx
packages/components/textarea/docs/Index.zh.md

feat(comp: form): support default control

---

packages/components/form/src/token.ts
packages/components/modal/src/types.ts
packages/components/style/themes/default.less
packages/components/table/demo/ColSpanRowSpan.md
packages/components/table/demo/ColSpanRowSpan.vue
packages/components/table/demo/Expandable.md
packages/components/table/demo/Fixed.md
packages/components/table/demo/HeadGroup.md
packages/components/table/demo/HeadGroup.vue
packages/components/table/demo/Selectable.md
packages/components/table/demo/SelectableOptions.md
packages/components/table/demo/SelectableOptions.vue
packages/components/table/demo/Server.md
packages/components/table/demo/Server.vue
packages/components/table/src/main/body/BodyRow.tsx
packages/components/table/style/fixed.less
packages/components/table/style/index.less

docs(comp: table): update demo

---

packages/components/icon/src/utils.ts

refactor: remove unused code

---

packages/components/drawer/src/DrawerBody.tsx
packages/components/drawer/style/index.less

fix(comp:drawer): rename placement classname (#450)

---

packages/components/spin/__tests__/__snapshots__/spin.spec.ts.snap
packages/components/spin/demo/Basic.vue
packages/components/spin/demo/Icon.vue
packages/components/spin/demo/Size.vue
packages/components/spin/demo/Tip.vue
packages/components/spin/src/Spin.tsx
packages/components/spin/style/index.less

spin的icon样式无效
1. spin icon样式正常
2. 遮罩层不增加背景颜色，只改透明度

fix(comp: spin): fix icon style not work

---

packages/components/checkbox/__tests__/__snapshots__/checkbox.spec.ts.snap
packages/components/checkbox/__tests__/__snapshots__/checkboxGroup.spec.ts.snap
packages/components/checkbox/__tests__/checkbox.spec.ts
packages/components/checkbox/__tests__/checkboxGroup.spec.ts
packages/components/checkbox/demo/Basic.vue
packages/components/checkbox/demo/Button.md
packages/components/checkbox/demo/Button.vue
packages/components/checkbox/demo/Disabled.md
packages/components/checkbox/demo/Disabled.vue
packages/components/checkbox/demo/FocusBlur.md
packages/components/checkbox/demo/FocusBlur.vue
packages/components/checkbox/demo/Gap.md
packages/components/checkbox/demo/Gap.vue
packages/components/checkbox/demo/Group.md
packages/components/checkbox/demo/Indeterminate.md
packages/components/checkbox/demo/Indeterminate.vue
packages/components/checkbox/demo/Size.md
packages/components/checkbox/demo/Size.vue
packages/components/checkbox/demo/TrueFalse.md
packages/components/checkbox/docs/Index.zh.md
packages/components/checkbox/index.ts
packages/components/checkbox/src/Checkbox.tsx
packages/components/checkbox/src/CheckboxGroup.tsx
packages/components/checkbox/src/types.ts
packages/components/checkbox/style/index.less
packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/menu/docs/Index.zh.md
packages/components/style/mixins/size.less
packages/components/style/themes/default.less

1. checkbox新增buttoned属性、size属性； checkboxGroup新增buttoned、size、gap属性
2. 整体优化checkbox样式

feat(comp:checkbox): add new props & refactor style

---

packages/components/stepper/docs/Index.zh.md

docs(comp:stepper): update props types

---

.husky/commit-msg
.husky/pre-commit
commitlint.config.js
package.json

refactor: update husky

---

packages/components/layout/demo/Breakpoint.md
packages/components/layout/demo/Collapsed.md
packages/components/layout/demo/OutSider.md
packages/components/layout/demo/Placement.md
packages/components/layout/demo/Placement.vue
packages/components/layout/demo/Trigger.md
packages/components/layout/demo/Trigger.vue
packages/components/layout/style/index.less
packages/components/style/themes/default.less

1. 优化layout组件自带trigger收缩状态下的样式
2. 优化layout组件demo

refactor: 优化layout组件样式和demo

---

packages/components/form/style/status.less

fix(comp:textarea): textarea turns red when invaild(#401)

---

packages/cdk/forms/src/utils.ts
packages/components/checkbox/__tests__/checkbox.spec.ts
packages/components/input/__tests__/input.spec.ts
packages/components/input/src/useCommonBindings.ts
packages/components/radio/__tests__/radio.spec.ts
packages/components/rate/__tests__/rate.spec.ts
packages/components/switch/__tests__/switch.spec.ts

fix(comp:input): support controlled value

---

packages/components/table/demo/Virtual.vue
packages/components/table/docs/Index.zh.md
packages/components/table/src/composables/useDataSource.ts
packages/components/table/src/composables/useScroll.ts
packages/components/table/src/composables/useTableLayout.ts
packages/components/table/src/main/MainTable.tsx
packages/components/table/src/types.ts
packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap
packages/components/tree/__tests__/tree.spec.ts
packages/components/tree/docs/Index.zh.md
packages/components/tree/src/Tree.tsx
packages/components/tree/src/node/Expand.tsx
packages/components/tree/src/node/TreeNode.tsx
packages/components/tree/src/types.ts
packages/components/tree/style/index.less
packages/components/tree/style/themes/default.less

refactor(comp:table,tree): update with vitrul scroll

---

packages/components/button/src/Button.tsx
packages/components/checkbox/src/Checkbox.tsx
packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/form/demo/Register.vue
packages/components/form/docs/Index.zh.md
packages/components/form/index.ts
packages/components/form/src/token.ts
packages/components/input/src/Input.tsx
packages/components/radio/src/Radio.tsx
packages/components/rate/__tests__/__snapshots__/rate.spec.ts.snap
packages/components/rate/demo/Size.md
packages/components/rate/demo/Size.vue
packages/components/rate/docs/Index.zh.md
packages/components/rate/src/Rate.tsx
packages/components/rate/src/types.ts
packages/components/rate/style/index.less
packages/components/rate/style/themes/default.less
packages/components/switch/demo/Size.vue
packages/components/switch/src/Switch.tsx
packages/components/switch/src/types.ts
packages/components/switch/style/themes/default.less
packages/components/time-picker/src/TimePicker.tsx
packages/components/time-picker/src/hooks.ts

feat(comp:form): formsize supported for the form components

---

packages/components/_private/overlay/src/Overlay.tsx

fix(comp:_private/overlay): warn: Maximum recursive updates exceeded

---

packages/components/select/src/composables/useOverlayProps.ts

fix(comp:selelct): sync overlay width when opened

---

packages/components/pagination/src/Simple.tsx

fix(comp:pagination): controlled input can't change value

---

packages/components/select/__tests__/select.spec.ts
packages/components/select/src/Select.tsx
packages/components/select/src/composables/useActiveState.ts
packages/components/select/src/composables/useInputState.ts
packages/components/select/src/composables/useOverlayProps.ts
packages/components/select/src/composables/useSelectedState.ts
packages/components/select/src/content/Content.tsx
packages/components/select/src/content/Option.tsx
packages/components/select/src/token.ts
packages/components/select/src/trigger/Input.tsx
packages/components/select/src/utils/generateOption.ts

refactor(comp: select): code style

---

packages/components/tabs/__tests__/__snapshots__/tabs.spec.ts.snap
packages/components/tabs/__tests__/tabs.spec.ts
packages/components/tabs/demo/Placement.md
packages/components/tabs/demo/Placement.vue
packages/components/tabs/docs/Index.zh.md
packages/components/tabs/index.ts
packages/components/tabs/src/TabNav.tsx
packages/components/tabs/src/Tabs.tsx
packages/components/tabs/src/composables/useOffset.ts
packages/components/tabs/src/composables/useSize.ts
packages/components/tabs/src/tokens.ts
packages/components/tabs/src/types.ts
packages/components/tabs/style/index.less
packages/components/tabs/style/themes/default.less

refactor(comp: tabs): add the bottom and end options to the placement attribute

---

packages/components/anchor/src/Anchor.tsx
packages/components/anchor/src/AnchorLink.tsx

feat(comp:anchor): update prefixCls type

---

packages/components/avatar/__tests__/avatar.spec.ts
packages/components/avatar/src/Avatar.tsx

feat(comp:avatar): suport prefixCls

---

packages/components/collapse/src/Collapse.tsx
packages/components/collapse/src/CollapsePanel.tsx

feat(comp:collapse): suport prefixCls

---

packages/components/header/src/Header.tsx

feat(comp:header): suport prefixCls

---

packages/components/layout/src/Layout.tsx
packages/components/layout/src/LayoutContent.tsx
packages/components/layout/src/LayoutFooter.tsx
packages/components/layout/src/LayoutHeader.tsx
packages/components/layout/src/LayoutSider.tsx
packages/components/layout/src/Trigger.tsx

feat(comp:layout): suport prefixCls

---

packages/components/form/docs/Index.zh.md

docs(comp: form): update form component labelAlign props

---

packages/components/popover/src/Popover.tsx

feat(comp:popover): suport prefixCls

---

packages/components/pagination/src/Item.tsx
packages/components/pagination/src/Jumper.tsx
packages/components/pagination/src/Pagination.tsx
packages/components/pagination/src/Simple.tsx
packages/components/pagination/src/Sizes.tsx
packages/components/pagination/src/Total.tsx
packages/components/pagination/src/token.ts

feat(comp:pagination): suport prefixCls

---

packages/components/spin/src/Spin.tsx

feat(comp:spin): suport prefixCls

---

packages/components/stepper/src/Stepper.tsx
packages/components/stepper/src/StepperItem.tsx

feat(comp:stepper): suport prefixCls

---

packages/components/tooltip/src/Tooltip.tsx

feat(comp:tooltip): suport prefixCls

---

packages/components/alert/src/composables/useCloseable.ts
packages/components/alert/src/types.ts

当全局配置alert组件`closable`的默认值为`true`时，业务代码里设置alert组件的`closable`为`false`不生效

fix(comp:alert): fix the failure of closable configuration

---

packages/components/table/demo/Expandable.vue
packages/components/table/demo/Selectable.vue
packages/components/table/demo/Sortable.vue
packages/components/table/demo/SortableOrderBy.vue
packages/components/table/demo/Virtual.vue
packages/components/table/docs/Index.zh.md
packages/components/table/src/composables/usePagination.ts
packages/components/table/src/types.ts

feat(comp:table): pagination supports boolean types

---

package.json
packages/components/components.less
packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/i18n/src/locales/en-US.ts
packages/components/i18n/src/locales/zh-CN.ts
packages/components/i18n/src/types.ts
packages/components/index.ts
packages/components/popconfirm/demo/Basic.md
packages/components/popconfirm/demo/Basic.vue
packages/components/popconfirm/demo/Placement.md
packages/components/popconfirm/demo/Placement.vue
packages/components/popconfirm/demo/Trigger.md
packages/components/popconfirm/demo/Trigger.vue
packages/components/popconfirm/docs/Index.en.md
packages/components/popconfirm/docs/Index.zh.md
packages/components/popconfirm/index.ts
packages/components/popconfirm/src/Popconfirm.tsx
packages/components/popconfirm/src/PopconfirmFooter.tsx
packages/components/popconfirm/src/token.ts
packages/components/popconfirm/src/types.ts
packages/components/popconfirm/style/index.less
packages/components/popconfirm/style/index.ts
packages/components/popconfirm/style/themes/default.less
packages/components/popover/src/Popover.tsx
packages/components/style/variable/prefix.less
packages/components/tooltip/src/Tooltip.tsx

feat(comp:popconfirm): add popconfirm component

---

packages/components/config/src/dateConfig.ts

feat(comp:config): update date config

---

azure-pipelines.yml

ci: update azure pipelines

---

packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap
packages/components/tree/__tests__/tree.spec.ts
packages/components/tree/docs/Index.zh.md
packages/components/tree/src/composables/useCheckable.ts
packages/components/tree/src/composables/useDataSource.ts
packages/components/tree/src/node/Content.tsx
packages/components/tree/src/node/TreeNode.tsx
packages/components/tree/src/types.ts

feat(comp:tree): add labelKey props

---

package.json
packages/components/popconfirm/__tests__/__snapshots__/popconfirm.spec.ts.snap
packages/components/popconfirm/__tests__/popconfirm.spec.ts
packages/components/popconfirm/src/Popconfirm.tsx
packages/components/popconfirm/src/PopconfirmFooter.tsx
packages/components/popconfirm/src/types.ts

test(comp:popconfirm): add test

---

packages/components/input-number/src/useInputNumber.ts

fix(comp:input-number): step calculation error when value is NaN

---

packages/pro/layout/docs/Index.zh.md

docs(comp:layoutpro): 修改部分文档

---

packages/components/input-number/src/InputNumber.tsx
packages/components/input-number/src/useInputNumber.ts

fix(comp:input-number): use form Control to control disabled status

---

packages/components/button/style/index.less
packages/components/style/variable/prefix.less

buttonGroup中放置的button有间隔  (issue 501)
将buttonGroup中的button像左移了1px，是相邻的两个button重叠，激活时调整z-index，以及后一个button的border达到想要的效果
尽量使用同一种类型的button放在一个group里，不然会很怪。
本次提交使用的less不知道是否正确。

style(comp:button): modify the button's style to the button group (#501)

---

packages/components/tree/__tests__/tree.spec.ts
packages/components/tree/src/Tree.tsx
packages/components/tree/src/composables/useExpandable.ts

fix(comp:tree): modify the childrenKey causes the expand to fail

---

README.md
packages/cdk/package.json
packages/components/package.json
packages/pro/package.json
packages/site/src/docs/GettingStarted.zh.md
scripts/gulp/build/esbuildPlugin.ts
scripts/gulp/build/gulpUtils.ts
scripts/gulp/build/index.ts
scripts/gulp/icons/bin.js
scripts/gulp/site/utils.ts

docs: add getting started

---

packages/components/input-number/src/useInputNumber.ts

fix(comp:input-number): not displayed when value is zero

---

packages/components/config/src/dateConfig.ts
packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/date-picker/demo/Basic.md
packages/components/date-picker/demo/Basic.vue
packages/components/date-picker/demo/Disabled.md
packages/components/date-picker/demo/Disabled.vue
packages/components/date-picker/demo/DisabledDate.md
packages/components/date-picker/demo/DisabledDate.vue
packages/components/date-picker/demo/Format.md
packages/components/date-picker/demo/Format.vue
packages/components/date-picker/demo/FormatCustom.md
packages/components/date-picker/demo/FormatCustom.vue
packages/components/date-picker/src/DatePicker.tsx
packages/components/date-picker/src/composables/useInputState.ts
packages/components/date-picker/src/composables/usePanelState.ts
packages/components/date-picker/src/trigger/Trigger.tsx
packages/components/date-picker/src/types.ts
packages/components/default.less
packages/components/slider/style/themes/default.less
packages/components/time-picker/src/utils.ts
packages/components/time-picker/style/index.less
packages/components/time-picker/style/themes/default.less
packages/components/time-picker/style/themes/default.ts

fix(comp:time-picker,slider): style entry

docs: add date-picker demo

---

packages/components/tree/__tests__/tree.spec.ts
packages/components/tree/demo/CheckStrategy.vue
packages/components/tree/demo/Disabled.vue
packages/components/tree/demo/Virtual.vue
packages/components/tree/docs/Index.zh.md
packages/components/tree/src/composables/useExpandable.ts
packages/components/tree/src/types.ts

全部展开功能应该由expandedKeys进行驱动，让tree的api保持纯粹一点

feat(comp:tree): remove defaultExpandAll prop

---

packages/pro/layout/src/composables/useActiveKey.ts
packages/pro/layout/style/header.less
packages/pro/layout/style/index.less
packages/pro/layout/style/mixin.less
packages/pro/layout/style/sider.less

fix(pro: layout): fix layout style

---

packages/components/i18n/__tests__/useI18n.spec.ts
packages/components/i18n/index.ts
packages/components/i18n/src/locales/en-US.ts
packages/components/i18n/src/locales/index.ts
packages/components/i18n/src/locales/zh-CN.ts
packages/components/i18n/src/useI18n.ts
packages/site/src/docs/GettingStarted.zh.md
packages/site/src/docs/I18n.zh.md
packages/site/src/iduxInstall.ts

refactor(comp:i18n): update locales

---

packages/site/plugins/md/marked.ts
packages/site/plugins/md/parsePackageDocs.ts
packages/site/src/components/global/GlobalCodeBox.vue

fix: site menu style

---

packages/components/breadcrumb/__tests__/__snapshots__/breadcrumb.spec.ts.snap
packages/components/breadcrumb/__tests__/breadcrumb.spec.ts
packages/components/breadcrumb/demo/Basic.md
packages/components/breadcrumb/demo/Basic.vue
packages/components/breadcrumb/demo/Custom.md
packages/components/breadcrumb/demo/Custom.vue
packages/components/breadcrumb/demo/Dropdown.md
packages/components/breadcrumb/demo/Dropdown.vue
packages/components/breadcrumb/docs/Index.en.md
packages/components/breadcrumb/docs/Index.zh.md
packages/components/breadcrumb/index.ts
packages/components/breadcrumb/src/Breadcrumb.tsx
packages/components/breadcrumb/src/BreadcrumbItem.tsx
packages/components/breadcrumb/src/token.ts
packages/components/breadcrumb/src/types.ts
packages/components/breadcrumb/style/index.less
packages/components/breadcrumb/style/themes/default.less
packages/components/breadcrumb/style/themes/default.ts
packages/components/default.less
packages/components/index.ts
packages/components/slider/demo/InputNumber.md
packages/components/slider/index.ts
packages/components/style/variable/prefix.less
packages/components/types.d.ts

feat(comp:breadcrumb): add breadcrumb component (#71)

---

packages/components/message/src/MessageProvider.tsx
packages/components/notification/src/NotificationProvider.tsx

fix #576
The first animation do not work.
Work normally

fix(comp:message/notification): fix first animation

---

scripts/gen/generate.ts
scripts/gen/template.ts
scripts/gulp/icons/bin.js

ci: update gen script

---

README.zh.md
packages/components/carousel/index.ts
packages/components/types.d.ts
packages/site/src/docs/Introduce.en.md
scripts/gen/generate.ts

docs: add en RADEME.md

---

packages/components/icon/docs/Index.zh.md
packages/components/select/demo/CustomLabel.vue
packages/components/tag/demo/Icon.vue
packages/site/plugins/md/generateTitle.ts
packages/site/src/components/layout/footer/locales.ts
packages/site/src/components/layout/header/LayoutHeaderNavigation.vue
packages/site/src/components/views/home/Home.vue
packages/site/src/components/views/home/locales.ts

docs: corrected some typos

---

packages/components/select/docs/Index.zh.md
packages/components/select/src/types.ts

fix IDuxFE#642

---

packages/components/button/demo/Icon.md
packages/components/button/demo/Shape.md
packages/components/button/demo/Size.md
packages/components/button/style/index.less
packages/site/src/components/views/home/Home.vue

fix(comp:button): button-group display: inline-flex

---

packages/components/modal/demo/UseModal.md

docs(comp:modal): update useModal, fix #655

---

packages/site/package.json
packages/site/src/components/global/GlobalCodeBox.vue
packages/site/src/components/global/GlobalCodeSandbox.vue
packages/site/src/global/codesandbox.ts

feat: site add codesandbox support

---

.eslintrc.js
jest.config.js
package.json
packages/components/package.json
packages/components/time-picker/__tests__/timePicker.spec.ts
scripts/gulp/build/rollup.config.ts

build: remove dayjs

---

packages/components/form/style/status.less

fix(comp:form): invalid style of input

---

packages/components/modal/docs/Index.zh.md
packages/components/modal/src/ModalWrapper.tsx
packages/components/modal/src/types.ts

feat(comp:modal): add prop to control transition(#623)

---

package.json
packages/components/result/__tests__/result.spec.ts

ci: fix test

---

packages/cdk/a11y/demo/FocusMonitor.md
packages/cdk/a11y/demo/FocusMonitor.vue
packages/cdk/a11y/docs/Index.zh.md
packages/cdk/a11y/src/inputModalityDetector.ts
packages/cdk/popper/demo/Placement.md
packages/cdk/popper/docs/Index.en.md
packages/cdk/popper/docs/Index.zh.md
packages/components/utils/src/useFormElement.ts

docs(cdk:*): update docs and demo

---

packages/components/tabs/demo/Scroll.vue
packages/components/tabs/demo/Segment.vue
packages/components/tabs/style/index.less

refactor(comp: tabs): flex layout is used instead of grid layout

---

packages/components/anchor/__tests__/__snapshots__/anchor.spec.ts.snap
packages/components/anchor/src/Anchor.tsx
packages/components/anchor/style/index.less
packages/components/anchor/style/themes/default.variable.less

refactor(comp: anchor): extract less variable

---

package.json

update package.json engines node v12.0.0 to v16.0.0

fix(packaging): update node version

---

.ls-lint.yml
azure-pipelines.yml
packages/cdk/forms/__tests__/abstractControl.spec.ts
packages/cdk/forms/__tests__/formControl.spec.ts
packages/cdk/forms/__tests__/validators.spec.ts
packages/cdk/forms/demo/Basic.vue
packages/cdk/forms/docs/Index.zh.md
packages/cdk/forms/docs/Overview.zh.md
packages/cdk/forms/index.ts
packages/cdk/forms/src/controls.ts
packages/cdk/forms/src/messages/en-US.ts
packages/cdk/forms/src/messages/zh-CN.ts
packages/cdk/forms/src/types.ts
packages/cdk/forms/src/validators.ts
packages/components/form/demo/CustomizedValidation.md
packages/components/form/demo/Message.md
packages/components/form/demo/Message.vue
packages/components/form/src/FormItem.tsx
packages/components/space/src/types.ts
packages/components/time-picker/src/types.ts

feat(cdk:forms): add default messages

---

packages/components/menu/style/dark.less
packages/components/menu/style/index.less
packages/components/menu/style/menu.less
packages/components/tag/style/index.less

fix(comp:menu): remove border-bototm on horizontal mode

---

packages/components/typography/style/index.less

typography disable is true, child a label can not be grayed out
"fix #567"

fix(comp:typography): fix typography disabled style

---

packages/components/anchor/style/index.less
packages/components/anchor/style/themes/default.variable.less

在嵌套的情况下，由于之前anchor-link样式使用的是padding，要调整为每行之间的间距相等，比较麻烦且复杂
建议调整为margin

refactor(comp: anchor): update style

---

packages/components/notification/style/index.less
packages/components/notification/style/themes/default.variable.less

refactor(comp: notification): extract less variable

---

packages/components/_private/header/src/Header.tsx
packages/components/card/style/index.less
packages/components/card/style/themes/default.variable.less
packages/components/drawer/src/DrawerWrapper.tsx
packages/components/drawer/style/index.less
packages/components/drawer/style/themes/default.variable.less
packages/components/modal/style/index.less
packages/components/modal/style/themes/default.variable.less

refactor(comp:_private/header): default size set to 'sm'

---

packages/components/checkbox/style/index.less
packages/components/radio/style/index.less

fix the problem that checkbox and radio doesnot align with text in table
表格中的checkbox以及radio不居中
表格中的checkbox以及radio居中和文字对齐

fix(radio,checkbox): fix checkbox and radio aligin

---

packages/components/carousel/style/index.less
packages/components/carousel/style/themes/default.variable.less

refactor(comp: carousel): extract less variable

---

packages/components/index.ts
packages/components/table/index.ts
packages/components/table/src/Table.tsx
packages/components/table/src/composables/useColumns.ts
packages/components/table/src/main/body/BodyCell.tsx
packages/components/table/src/tableColumn.ts
packages/components/table/src/types.ts
packages/components/types.d.ts

表格支持通过IxTableColumn的语法糖去配置每个表格显示列
BREAKING CHANGE: fix:#650
fix #650

feat(comp:table): add TableColumn component

---

packages/components/menu/demo/Router.vue
packages/components/menu/demo/Slots.vue
packages/components/menu/docs/Index.zh.md
packages/components/menu/src/children/menu-sub/InlineContent.tsx
packages/components/menu/src/children/menu-sub/OverlayContent.tsx
packages/components/menu/src/composables/useDataSource.ts
packages/components/menu/style/dark.less
packages/components/menu/style/index.less
packages/components/menu/style/menu.less
packages/pro/layout/__tests__/__snapshots__/layoutPro.spec.ts.snap

refactor(comp:menu): component style update

---

packages/components/slider/src/useSlider.ts

feat(comp:slider): unify trigger conditions for change events

---

packages/cdk/scroll/__tests__/virtualScroll.spec.ts
packages/cdk/scroll/src/virtual/VirtualScroll.tsx
packages/cdk/scroll/src/virtual/composables/useScrollTo.ts
packages/cdk/scroll/src/virtual/composables/useScrollVisible.ts
packages/cdk/scroll/src/virtual/contents/ScrollBar.tsx

feat(cdk:scroll): show scrollbar when mouseenter

---

package.json
packages/components/_private/footer/__tests__/__snapshots__/footer.spec.ts.snap
packages/components/_private/footer/src/Footer.tsx
packages/components/modal/__tests__/modal.spec.ts
packages/components/popconfirm/__tests__/popconfirm.spec.ts

build: update @types/svgo to 2.6.1
确定在右，取消在左
svgo类型报错
确定在左，取消在右

feat(comp:footer): swap confirm and cancel btn

---

.all-contributorsrc
packages/site/src/docs/Contributors.en.md
packages/site/src/docs/Contributors.zh.md
packages/site/src/styles/docs/contributors.less
packages/site/src/styles/docs/index.less
packages/site/src/styles/index.less

docs: add all contributors

---

packages/components/grid/docs/Index.zh.md
packages/components/grid/index.ts
packages/components/grid/src/Col.tsx
packages/components/grid/src/Row.tsx
packages/components/grid/src/token.ts
packages/components/grid/src/types.ts
packages/components/grid/style/index.less
packages/components/space/__tests__/__snapshots__/space.spec.ts.snap
packages/components/space/__tests__/space.spec.ts
packages/components/space/src/Space.tsx
packages/components/space/style/index.less

feat(comp:space): add justify prop

---

packages/components/dropdown/demo/Basic.vue
packages/components/dropdown/demo/Button.vue
packages/components/dropdown/demo/Placement.vue
packages/components/dropdown/demo/Trigger.vue
packages/components/dropdown/docs/Index.zh.md
packages/components/input/src/useInput.ts
packages/components/menu/docs/Index.zh.md
packages/components/menu/src/composables/useSelected.ts
packages/components/menu/src/types.ts
packages/components/pagination/docs/Index.zh.md
packages/components/space/__tests__/__snapshots__/space.spec.ts.snap
packages/components/space/docs/Index.zh.md
packages/components/space/src/Space.tsx
packages/components/space/src/types.ts
packages/site/plugins/transformIndexPlugin.ts
packages/site/src/components/layout/footer/LayoutFooter.vue
packages/site/src/components/layout/header/LayoutHeaderLogo.vue
packages/site/src/components/views/home/locales.ts

fix(comp:space): remove default alian and justify

---

packages/components/select/__tests__/select.spec.ts
packages/components/select/src/composables/useOptions.ts

设置 labelKey 之后默认过滤函数无法过滤
根据配置的 labelKey 去获取字段，能够正常过滤

fix(comp:select): filter option exception (#750)

---

packages/components/_private/loading/__tests__/__snapshots__/loading.spec.ts.snap
packages/components/_private/loading/__tests__/loading.spec.ts
packages/components/_private/loading/index.ts
packages/components/_private/loading/src/Loading.tsx
packages/components/_private/loading/src/types.ts
packages/components/_private/loading/style/index.less
packages/components/_private/loading/style/themes/default.less
packages/components/_private/loading/style/themes/default.ts
packages/components/_private/loading/style/themes/default.variable.less
packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/default.less
packages/components/spin/__tests__/__snapshots__/spin.spec.ts.snap
packages/components/spin/__tests__/spin.spec.ts
packages/components/spin/demo/Icon.vue
packages/components/spin/docs/Index.zh.md
packages/components/spin/src/Spin.tsx
packages/components/spin/src/types.ts
packages/components/spin/style/index.less
packages/components/spin/style/themes/default.ts
packages/components/spin/style/themes/default.variable.less
packages/components/style/variable/prefix.less

feat(comp:loading): add private loading component
feat(comp:spin): add strokeWidth, radius prop
feat(comp:spin): add icon rotate animation, controlled by rotate prop
新增loading私有组件
部分重构spin组件，默认的loading改为内置Loading组件
新增图标的旋转动画，由rotate选项配置
新增 strokeWidth, radius配置，支持全局配置

refactor(comp:spin): modify default loading

---

packages/components/table/src/main/MainTable.tsx
packages/components/table/src/main/body/Body.tsx
packages/components/table/src/main/body/BodyRow.tsx
packages/components/table/src/main/body/RenderBodyRow.tsx

抽离展开列的渲染，BodyRow不再是多根节点组件
封装表格行渲染函数为独立可复用函数

refactor(comp:table): extract expanded row render

---

packages/cdk/forms/docs/Index.zh.md
packages/components/form/__tests__/__snapshots__/form.spec.ts.snap
packages/components/form/__tests__/form.spec.ts
packages/components/form/docs/Index.zh.md
packages/components/form/index.ts
packages/components/form/src/Form.tsx
packages/components/form/src/FormItem.tsx
packages/components/form/src/composables/useFormItem.ts
packages/components/form/src/token.ts
packages/components/form/src/types.ts
packages/components/form/style/index.less
packages/components/form/style/status.less
packages/components/menu/docs/Index.zh.md
packages/components/table/src/main/MainTable.tsx
packages/site/src/components/layout/header/LayoutHeaderSearchBox.vue

BREAKING CHANGE: `hasFeedback` was deprecated, please use `statusIcon` instead.  `extra` was
deprecated, please use `extraMessage` instead.

refactor(comp:form): api redesign and add test

---

packages/components/tabs/style/index.less

fix(comp: tabs): when scrolling style is wrong

---

packages/pro/layout/__tests__/layoutPro.spec.ts
packages/pro/layout/index.ts

ProLayout存在ProLayoutMenuData类型，应该去除，统一采用MenuData

refactor(comp:pro:layout): remove ProLayoutMenuData

---

packages/components/menu/src/Menu.tsx
packages/components/menu/src/contents/MenuItem.tsx
packages/components/menu/src/contents/MenuItemGroup.tsx
packages/components/menu/src/contents/menu-sub/MenuSub.tsx
packages/components/menu/src/token.ts

inject的mode有些多余，可以从props上获取，优化代码

refactor(comp:menu): optimize code about internal mode

---

packages/components/checkbox/__tests__/checkbox.spec.ts
packages/components/checkbox/__tests__/checkboxGroup.spec.ts
packages/components/checkbox/src/Checkbox.tsx

fix(comp: checkbox): onChange returned an error oldValue

---

packages/components/menu/demo/StateSwitching.vue
packages/components/menu/src/contents/MenuItem.tsx
packages/components/menu/src/contents/MenuItemGroup.tsx
packages/components/menu/src/contents/menu-sub/Label.tsx
packages/components/menu/src/contents/menu-sub/MenuSub.tsx
packages/components/menu/src/token.ts

fix(comp:menu): remove stopPropagation

---

packages/components/tree/src/composables/useDataSource.ts

fix(comp:tree): The expanded state of the first layer node is wrong

---

packages/cdk/forms/src/messages/zh-CN.ts

fix(cdk:forms): maxLength message

---

packages/components/input/src/useInput.ts
packages/components/select/src/composables/useInputState.ts

fix(comp:select): trige handleInput  when onCompositionEnd

---

packages/components/locales/src/langs/en-US.ts
packages/components/locales/src/langs/zh-CN.ts
packages/components/locales/src/types.ts
packages/components/select/__tests__/select.spec.ts
packages/components/select/src/Select.tsx
packages/components/select/src/composables/useSelectedState.ts
packages/components/select/src/content/Option.tsx

feat(comp:select): disable option when limited

---

packages/components/menu/__tests__/menu.spec.ts
packages/components/menu/src/composables/useExpanded.ts
packages/pro/layout/__tests__/__snapshots__/layoutPro.spec.ts.snap
packages/pro/layout/src/contents/Sider.tsx

fix(comp:menu): cache expandedKeys when collapse changed

---

packages/cdk/popper/docs/Index.zh.md
packages/components/affix/docs/Index.zh.md
packages/components/card/docs/Index.zh.md
packages/components/drawer/docs/Index.zh.md
packages/components/form/docs/Index.zh.md
packages/components/menu/docs/Index.zh.md
packages/components/modal/docs/Index.zh.md
packages/components/time-picker/docs/Index.zh.md
packages/components/transfer/docs/Index.zh.md

There are some document error in the page, I almost check out all the basic components and found these errors below. 💻 
Now they are all fixed, 🎉

docs(components): fix typos and string escape and comma, etc

---

packages/components/tabs/style/index.less

The tab content not vertically centered
Use line-height to fix this

fix(comp:tab): tab content is not vertically centered

---

packages/components/icon/style/index.less
packages/components/tabs/style/index.less

refactor(comp: icon): update style code

---

packages/components/pagination/__tests__/__snapshots__/pagination.spec.ts.snap
packages/components/select/__tests__/__snapshots__/select.spec.ts.snap
packages/components/select/src/trigger/Selector.tsx

fix(comp: select): placeholder and the input position are squeezed

---

packages/components/slider/src/useSlider.ts

fix(comp:slider): slid distance calculation error

---

packages/components/pagination/src/Pagination.tsx
packages/components/pagination/src/composables/useItems.ts
packages/components/pagination/src/composables/usePages.ts
packages/components/table/src/composables/useScroll.ts
packages/components/table/src/main/ColGroup.tsx
packages/components/table/src/main/FixedHolder.tsx
packages/components/table/src/main/body/Body.tsx
packages/components/table/src/main/body/BodyRowSingle.tsx
packages/components/table/style/fixed.less

fix(comp:table): empty style

---

packages/cdk/scroll/src/virtual/types.ts
packages/components/select/__tests__/__snapshots__/select.spec.ts.snap
packages/components/select/src/composables/useInputState.ts
packages/components/select/src/content/Content.tsx
packages/components/select/src/trigger/Input.tsx
packages/components/select/src/trigger/Selector.tsx
packages/components/select/src/trigger/Trigger.tsx
packages/components/select/src/types.ts
packages/components/select/style/index.less

fix(comp:select): sync input width on isComposing

---

packages/components/_private/overflow/__tests__/overflow.spec.ts
packages/components/_private/overflow/src/Overflow.tsx

refactor(comp: overflow): code spell error

---

packages/components/_private/overlay/src/Overlay.tsx
packages/components/_private/overlay/src/types.ts
packages/components/_private/selector/src/Selector.tsx
packages/components/_private/selector/src/contents/Input.tsx
packages/components/_private/selector/src/contents/Item.tsx
packages/components/_private/selector/src/types.ts
packages/components/date-picker/src/DatePicker.tsx
packages/components/select/docs/Index.zh.md
packages/components/select/src/Select.tsx
packages/components/select/src/types.ts
packages/components/time-picker/src/TimePicker.tsx
packages/components/time-picker/src/TimeRangePicker.tsx
packages/components/tree-select/src/TreeSelect.tsx

feat(comp:select): support setting autocomplete

---

packages/components/tree/__tests__/tree.spec.ts
packages/components/tree/src/composables/useDataSource.ts
packages/components/tree/src/composables/useExpandable.ts

fix(comp: tree): Asynchronous loading node hierarchy error

---

packages/components/space/style/index.less

```
<ix-menu
v-model:selectedKeys="selectedKeys"
v-model:expandedKeys="expandedKeys"
:dataSource="dataSource"
mode="inline"
>
<template #label="item">
<router-link :to="item.key">
<ix-space>
<span>{{ item.label }}</span>
</ix-space>
</router-link>
</template>
</ix-menu>
```
由于ix-space给了固定颜色，导致导航被选中时，颜色文字颜色无法根据导航的颜色改变，应该设置为inherit，继承父组件的color值

fix(comp: space): error color value in style

---

packages/components/comment/__tests__/__snapshots__/comment.spec.ts.snap
packages/components/comment/demo/Basic.vue
packages/components/comment/demo/Editor.vue
packages/components/comment/demo/List.vue
packages/components/comment/demo/Nested.vue
packages/components/comment/docs/Index.zh.md
packages/components/comment/src/Comment.tsx
packages/components/comment/src/types.ts
packages/components/comment/style/index.less

refactor(comp: comment): optimize code

---

packages/components/_private/input/src/Input.tsx
packages/components/_private/selector/src/Selector.tsx
packages/components/_private/selector/src/types.ts
packages/components/form/style/status.less
packages/components/input-number/style/themes/default.variable.less
packages/components/input/style/index.less
packages/components/input/style/themes/default.less
packages/components/input/style/themes/default.variable.less
packages/components/pagination/__tests__/__snapshots__/pagination.spec.ts.snap
packages/components/select/__tests__/__snapshots__/select.spec.ts.snap
packages/components/select/demo/Key.md
packages/components/select/demo/OverlayRender.vue
packages/components/select/src/Select.tsx
packages/components/select/src/content/Content.tsx
packages/components/tree-select/__tests__/__snapshots__/treeSelect.spec.ts.snap
packages/components/tree-select/src/TreeSelect.tsx
packages/components/tree-select/src/content/Content.tsx
packages/components/tree-select/src/types.ts

fix(comp:input): update style with selector

---

packages/cdk/scroll/__tests__/virtualScroll.spec.ts
packages/cdk/scroll/demo/Basic.vue
packages/cdk/scroll/demo/Switch.vue
packages/cdk/scroll/docs/Index.zh.md
packages/cdk/scroll/index.ts
packages/cdk/scroll/src/virtual/composables/useGetKey.ts
packages/cdk/scroll/src/virtual/types.ts
packages/components/_private/checkable-list/src/CheckableList.tsx
packages/components/_private/selector/src/Selector.tsx
packages/components/_private/selector/src/types.ts
packages/components/select/src/Select.tsx
packages/components/select/src/composables/useOverlayState.ts
packages/components/select/src/content/Content.tsx
packages/components/table/src/main/MainTable.tsx
packages/components/tree-select/src/TreeSelect.tsx
packages/components/tree/src/Tree.tsx
packages/components/utils/src/useKey.ts
scripts/gen/generate.ts
scripts/gen/template.ts

refactor(cdk: scroll): use getKey instand of itemKey

fix(comp: select): update overlay on selector resize

---

packages/components/tabs/__tests__/tabs.spec.ts
packages/components/tabs/docs/Index.zh.md
packages/components/tabs/src/Tab.tsx
packages/components/tabs/src/TabNav.tsx
packages/components/tabs/src/Tabs.tsx
packages/components/tabs/src/tokens.ts
packages/components/tabs/src/types.ts

feat(comp: tabs): selectedKey type changed to VKey

feat(comp: tabs): first tab is selected by default when no selectedKey

---

packages/components/message/demo/Content.vue
packages/components/message/style/index.less

fix(comp: message): align icon with text

---

packages/cdk/scroll/docs/Index.zh.md
packages/cdk/scroll/src/virtual/types.ts
packages/components/checkbox/__tests__/checkboxGroup.spec.ts
packages/components/checkbox/demo/Button.vue
packages/components/checkbox/demo/Gap.vue
packages/components/checkbox/demo/Group.vue
packages/components/checkbox/demo/Size.vue
packages/components/checkbox/docs/Index.zh.md
packages/components/checkbox/src/Checkbox.tsx
packages/components/checkbox/src/CheckboxGroup.tsx
packages/components/checkbox/src/types.ts
packages/components/radio/__tests__/radioGroup.spec.ts
packages/components/radio/demo/Buttoned.vue
packages/components/radio/demo/Gap.vue
packages/components/radio/demo/Group.vue
packages/components/radio/demo/Name.vue
packages/components/radio/demo/Size.vue
packages/components/radio/docs/Index.zh.md
packages/components/radio/src/Radio.tsx
packages/components/radio/src/RadioGroup.tsx
packages/components/radio/src/types.ts

refactor(comp: checkbox,radio): use value as the key

---

packages/components/menu/src/contents/menu-sub/OverlayContent.tsx

compare the other codes and  fix this issue.

fix(comp: menu): menu cannot show

---

packages/site/src/components/layout/header/LayoutHeaderSearchBox.vue

FIX: #873 
@idux/site不支持搜索
@idux/site支持搜索

feat: add site searcher

---

packages/components/_private/checkable-list/__tests__/__snapshots__/checkableList.spec.ts.snap
packages/components/_private/checkable-list/src/CheckableList.tsx
packages/components/_private/checkable-list/src/CheckableListItem.tsx
packages/components/_private/checkable-list/src/types.ts
packages/components/transfer/__tests__/__snapshots__/transfer.spec.ts.snap
packages/components/transfer/__tests__/__snapshots__/transferSlots.spec.ts.snap
packages/components/transfer/docs/Index.zh.md
packages/components/transfer/src/types.ts
packages/pro/transfer/docs/Index.zh.md
packages/pro/transfer/src/types.ts

feat(comp: transfer): add customAdditional

---

packages/components/alert/style/index.less
packages/components/back-top/style/themes/seer.variable.less

fix(comp: alert): align icon with text

---

scripts/gulp/build/esbuild.ts
scripts/gulp/build/index.ts
scripts/gulp/build/rollup.ts
scripts/gulp/build/utils.ts

build: build full.mjs

---

packages/components/tree-select/__tests__/treeSelect.spec.ts
packages/components/tree-select/docs/Index.zh.md
packages/components/tree-select/src/types.ts
packages/components/tree/__tests__/tree.spec.ts
packages/components/tree/docs/Index.zh.md
packages/components/tree/src/composables/useExpandable.ts
packages/components/tree/src/node/Expand.tsx
packages/components/tree/src/types.ts

feat(comp: tree): expandIcon add array type

---

.all-contributorsrc
packages/site/src/docs/Contributors.en.md
packages/site/src/docs/Contributors.zh.md

docs: update contributors

---

packages/components/_private/selector/style/index.less
packages/components/menu/docs/Index.zh.md
packages/components/switch/style/mixin.less
packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
packages/components/table/demo/Selectable.vue
packages/components/table/src/Table.tsx
packages/components/table/src/main/MainTable.tsx
packages/components/table/src/main/body/Body.tsx
packages/components/table/style/index.less
packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap

- table 在空数据的情况下，样式异样问题
- table 在仅有 1 行数据的时候，行高为 100 % 的问题
- switch 组件，在设置 labels 后的样式问题。
- selector 文本长度溢出时，异常显示问题。

fix(comp: table): update style with empty data

---

packages/components/select/__tests__/select.spec.ts
packages/components/select/src/composables/useGetOptionKey.ts

fix(comp:select): value key of select is 'value' by default

---

packages/components/locales/src/langs/en-US.ts
packages/components/locales/src/langs/zh-CN.ts
packages/components/locales/src/types.ts
packages/components/tree-select/__tests__/treeSelect.spec.ts
packages/components/tree-select/docs/Index.zh.md
packages/components/tree-select/src/TreeSelect.tsx
packages/components/tree-select/src/content/Content.tsx
packages/components/tree-select/src/token.ts
packages/components/tree-select/src/types.ts
packages/pro/tree/src/ProTree.tsx

BREAKING CHANGE: setExpandAll was deprecated, please use collapseAll and
expandAll instead.

feat(comp: tree-select): add expandAll and collapseAll methods

---

packages/cdk/forms/__tests__/formArray.spec.ts
packages/cdk/forms/__tests__/formGroup.spec.ts
packages/cdk/forms/docs/Index.zh.md
packages/cdk/forms/docs/Overview.zh.md
packages/cdk/forms/src/controls.ts
packages/cdk/forms/src/types.ts
packages/components/cascader/demo/Searchable.vue
packages/components/input/__tests__/input.spec.ts
packages/components/input/docs/Index.zh.md
packages/components/input/src/types.ts
packages/components/input/src/useInput.ts
packages/components/package.json
packages/components/select/demo/Searchable.vue
packages/components/select/demo/Server.vue
packages/components/select/demo/Size.vue
packages/components/table/demo/Server.vue
packages/components/textarea/__tests__/textarea.spec.ts
packages/components/textarea/docs/Index.zh.md
packages/components/textarea/src/types.ts
packages/components/tree-select/demo/Search.vue

* feat(comp: input,textarea): add trim prop
BREAKING CHANGE: `ValidatorOptions.trim` was deprecated, please use `trim` of `IxInput` or
`IxTextarea` instead.

feat(cdk: forms): getValue support skip disabled control

---

packages/components/_private/time-panel/__tests__/timeSelectorColumn.spec.ts
packages/components/_private/time-panel/src/TimePanelCell.tsx
packages/components/_private/time-panel/src/TimePanelColumn.tsx
packages/components/_private/time-panel/src/composables/useColumnEvents.ts
packages/components/_private/time-panel/style/index.less
packages/components/_private/time-panel/style/themes/default.variable.less
packages/components/date-picker/style/themes/default.variable.less
packages/components/time-picker/src/content/RangeContent.tsx
packages/components/time-picker/style/index.less
packages/components/time-picker/style/themes/default.variable.less

1. scrollbar is placed with same margin to each column
2. expand scroll intereactable area to fill the whole panel
3. remove time panel border in range pickers
4. replace separator with a vertical line when allowInput is not overlay
1. 时间选择面板滚动条位置距离文字不等距，样式不美观
2. 时间和日期范围选择的时间面板有边框
1. 将面板列分为内外两层，内层通过固定宽度达到滚动条排列整齐的目的，外层铺满整个面板使触发区域不留空白，通过外层的wheel和click事件控制内层滚动和点击触发。
2. 去掉默认样式中的边框颜色和宽度
3. 替换时间范围选择在不展示浮层内输入框时的分隔符为竖线，使其更加美观

refactor(comp:time-picker): optimize panel scroll

---

packages/components/_private/selector/style/index.less
packages/components/_private/selector/style/multiple.less
packages/components/_private/selector/style/single.less
packages/components/select/__tests__/select.spec.ts
packages/components/select/src/composables/useOptions.ts
packages/components/select/style/index.less

fix(comp: select): search error when group exists

---

package.json
packages/cdk/a11y/src/focusMonitor.ts
packages/cdk/index.ts
packages/cdk/package.json
packages/cdk/resize/demo/Basic.md
packages/cdk/resize/demo/Basic.vue
packages/cdk/resize/demo/Component.md
packages/cdk/resize/demo/Component.vue
packages/cdk/resize/demo/Function.md
packages/cdk/resize/demo/Function.vue
packages/cdk/resize/docs/Index.en.md
packages/cdk/resize/docs/Index.zh.md
packages/cdk/resize/index.ts
packages/cdk/resize/src/ResizeObserver.tsx
packages/cdk/resize/src/types.ts
packages/cdk/resize/src/useResizeObserver.ts
packages/cdk/resize/src/utils.ts
packages/cdk/scroll/src/virtual/contents/Holder.tsx
packages/cdk/types.d.ts
packages/cdk/utils/src/convert.ts
packages/cdk/utils/src/dom.ts
packages/components/_private/overflow/src/Item.tsx
packages/components/_private/overflow/src/Overflow.tsx
packages/components/_private/selector/src/Selector.tsx
packages/components/avatar/src/Avatar.tsx
packages/components/table/src/main/MainTable.tsx
packages/components/table/src/main/body/MeasureCell.tsx
packages/components/tabs/src/Tabs.tsx
tests/setup.ts

feat(cdk: resize): add useResizeObserver and CdkResizeObserver

---

packages/components/stepper/style/index.less

fix(comp:stepper): padding problem of left&right

---

packages/components/table/demo/Bordered.vue
packages/components/table/demo/SortableMultiple.md
packages/components/table/demo/SortableMultiple.vue
packages/components/table/demo/SortableOrderBy.md
packages/components/table/docs/Index.zh.md
packages/components/table/src/Table.tsx
packages/components/table/src/composables/useDataSource.ts
packages/components/table/src/composables/useSortable.ts
packages/components/table/src/main/body/BodyCell.tsx
packages/components/table/src/main/head/HeadCell.tsx
packages/components/table/src/main/head/triggers/SortableTrigger.tsx
packages/components/table/src/types.ts

feat(comp: table): support multiple sort

---

packages/components/modal/demo/Async.vue
packages/components/modal/style/index.less
packages/components/tabs/style/index.less

fix(comp: tabs): error style when nesting tabs

---

.github/pull_request_template.md
packages/components/table/src/composables/useDataSource.ts
packages/components/table/src/composables/useFilterable.ts
packages/components/table/src/main/head/HeadCell.tsx
packages/components/table/src/types.ts

fix(comp: table): controled filter works

---

packages/cdk/scroll/src/virtual/contents/Holder.tsx

test: fix warn 'Maximum recursive updates exceeded'

---

commitlint.config.js
package.json

- Requires too much repetitive typing
- No relevant scope specification prompt
- Friendly First, Supports fuzzy search and selection on the command line, reducing spelling repetitive.
- Provides good prompt and **can filter out matches against your git status cache**
I am the author of cz-git, I found that you have made strict commit message rules, I think it is very suitable to use cz-git. which can  your experience in development
- github: https://github.com/Zhengqbbb/cz-git
- website: https://cz-git.qbenben.com/
- 中文文档：https://cz-git.qbenben.com/zh/
`checkbox=1 cz` or `checkbox=1  cz-git`
Hope it can help you well,
Btw, it is also the first time for me to deal with complex paths. It is not well coding or if you have any …

refactor: use cz-git commitizen adapter

---

packages/components/tree-select/docs/Index.zh.md
packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap
packages/components/tree/__tests__/tree.spec.ts
packages/components/tree/demo/Search.vue
packages/components/tree/src/Tree.tsx
packages/components/tree/src/composables/useDataSource.ts
packages/components/tree/src/composables/useExpandable.ts
packages/components/tree/src/composables/useSearchable.ts
packages/components/tree/src/node/TreeNode.tsx
packages/components/tree/src/token.ts

feat(comp: tree): Don't show irrelevant nodes during search

---

packages/components/select/demo/AllowInput.md
packages/components/select/demo/Basic.md
packages/components/select/demo/Borderless.md
packages/components/select/demo/CustomLabel.md
packages/components/select/demo/Group.md
packages/components/select/demo/Key.md
packages/components/select/demo/MaxLabel.md
packages/components/select/demo/Multiple.md
packages/components/select/demo/OverlayRender.md
packages/components/select/demo/Searchable.md
packages/components/select/demo/SelectAll.md
packages/components/select/demo/SelectAll.vue
packages/components/select/demo/Server.md
packages/components/select/demo/Size.md
packages/components/select/demo/Virtual.md

docs(comp:select): add demo of select all

---

packages/components/watermark/src/types.ts
packages/components/watermark/style/themes/seer.less
packages/components/watermark/style/themes/seer.ts

```
content: { type: [String, Array] as PropType<string | string[]>, default: undefined, required: true },
```

fix(comp:watermark): prop content type error

---

packages/cdk/drag-drop/docs/Index.zh.md
packages/cdk/resize/demo/ResizableBasic.vue
packages/cdk/resize/demo/ResizableHandler.vue
packages/cdk/resize/docs/Index.zh.md
packages/components/grid/demo/Align.vue
packages/components/grid/demo/Gutter.vue
packages/components/grid/demo/Justify.vue
packages/components/grid/demo/Order.vue
packages/components/grid/demo/Stretch.vue
packages/pro/config/src/defaultConfig.ts
packages/pro/table/docs/Index.zh.md
packages/pro/table/src/ProTable.tsx
packages/pro/table/style/index.less

docs: update demos

---

packages/components/table/src/main/MainTable.tsx
packages/components/table/src/main/head/Head.tsx
packages/components/table/src/main/head/HeadCell.tsx
packages/components/table/src/types.ts
packages/pro/config/src/defaultConfig.ts
packages/pro/config/src/types.ts
packages/pro/table/demo/Basic.vue
packages/pro/table/demo/CustomHeader.vue
packages/pro/table/demo/Resizable.vue
packages/pro/table/docs/Index.zh.md
packages/pro/table/src/ProTable.tsx
packages/pro/table/src/ProTableLayoutTool.tsx
packages/pro/table/src/types.ts
packages/pro/table/style/index.less
packages/pro/table/style/themes/default.less
packages/pro/table/style/themes/seer.less
packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap

refactor(pro:table): modify the layout tool position

---

packages/components/tree/__tests__/tree.spec.ts
packages/components/tree/src/composables/useDataSource.ts

fix(comp:tree): data display error after search clearing

---

packages/components/button/style/index.less
packages/components/select/style/index.less

fix(comp:button): danger mode style error

---

packages/components/table/src/main/MainTable.tsx
packages/components/table/style/index.less
packages/components/table/style/themes/default.variable.less
packages/components/table/style/themes/seer.variable.less

目前未设置 scroll.width, 当表格 resieze 时，会有一些样式上的异常。

fix(comp:table): calculate the scroll postion when container resize

---

packages/components/time-picker/src/content/RangeContent.tsx

fix(comp:time-picker): fix time range input

---

package.json
packages/cdk/index.less
packages/cdk/resize/demo/ResizableBasic.vue
packages/cdk/resize/demo/ResizableHandler.vue
packages/cdk/resize/style/index.less
packages/cdk/scroll/__tests__/__snapshots__/virtualScroll.spec.ts.snap
packages/cdk/scroll/src/strategy/blockScrollStrategy.ts
packages/cdk/scroll/src/utils.ts
packages/cdk/scroll/src/virtual/VirtualScroll.tsx
packages/cdk/scroll/src/virtual/contents/Holder.tsx
packages/cdk/scroll/style/index.less
packages/components/style/variable/prefix.less
packages/components/table/style/index.less
packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap
packages/pro/table/style/index.less
packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap
packages/pro/tree/__tests__/__snapshots__/proTree.spec.ts.snap
packages/site/src/docs/GettingStarted.zh.md
packages/site/src/index.less
scripts/gulp/build/less.ts

refactor(cdk:*): support less

---

packages/components/carousel/__tests__/__snapshots__/carousel.spec.ts.snap
packages/components/carousel/src/Carousel.tsx
packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
packages/components/table/src/main/body/BodyCell.tsx

在 form 组件中使用 table 的展开功能时，会触发表单组件的 submit, 导致页面刷新。
需要给 button 添加一个 `type='button'`

fix(comp:table): set expandable trigger button type

---

packages/cdk/drag-drop/docs/Index.zh.md
packages/cdk/drag-drop/index.ts
packages/cdk/drag-drop/src/composables/useDraggable.ts
packages/cdk/drag-drop/src/draggable/Draggable.tsx
packages/cdk/drag-drop/style/index.less
packages/cdk/resize/demo/ResizableBasic.vue
packages/cdk/resize/demo/ResizableHandler.vue
packages/cdk/resize/docs/Index.zh.md
packages/cdk/resize/src/resizable/Resizable.tsx
packages/cdk/resize/src/resizable/ResizableHandler.tsx
packages/cdk/resize/src/resizable/token.ts
packages/cdk/resize/src/resizable/types.ts
packages/cdk/resize/src/resizable/useResizable.ts
packages/cdk/resize/style/index.less
packages/pro/table/src/contents/ResizableHeadCell.tsx

- resize 时卡顿
- 水平 resize 时，影响了高度。

fix(cdk:resize): performance problem

---

packages/components/menu/style/dark.less
packages/pro/layout/style/mixin.less
packages/pro/layout/style/themes/default.variable.less
packages/pro/layout/style/themes/seer.variable.less

fix(comp:menu): update hover style

---

packages/components/button/docs/Index.zh.md
packages/components/button/style/index.less
packages/components/button/style/mixin.less
packages/components/button/style/themes/default.variable.less
packages/components/button/style/themes/seer.variable.less
packages/components/table/docs/Index.zh.md

```
<IxButton mode="primary">主按钮</IxButton>
<IxButton icon="setting">默认按钮</IxButton>
```

fix(comp:button): style error

---

packages/cdk/drag-drop/demo/WithHandle.md
packages/cdk/drag-drop/demo/WithHandle.vue
packages/cdk/drag-drop/docs/Index.zh.md
packages/cdk/drag-drop/src/composables/useDraggable.ts
packages/cdk/drag-drop/src/composables/useDroppable.ts
packages/cdk/drag-drop/src/composables/withDragFree.ts
packages/cdk/drag-drop/src/composables/withDragHandle.ts
packages/cdk/drag-drop/src/types.ts
packages/cdk/drag-drop/style/index.less
packages/components/modal/demo/DraggableModal.md
packages/components/modal/demo/DraggableModal.vue
packages/components/modal/docs/Index.zh.md
packages/components/modal/src/ModalWrapper.tsx
packages/components/modal/src/types.ts

feat(cdk:drag-drop): add handle&reset api

feat(comp:modal): add draggable props (#905)

---

packages/cdk/drag-drop/demo/Basic.vue
packages/cdk/drag-drop/demo/MultipleTargets.vue
packages/cdk/drag-drop/demo/WithHandle.vue
packages/cdk/drag-drop/docs/Index.zh.md
packages/cdk/drag-drop/src/composables/useDraggable.ts
packages/cdk/drag-drop/src/composables/withDragHandle.ts
packages/cdk/drag-drop/src/types.ts
packages/cdk/drag-drop/style/index.less
packages/cdk/index.ts
packages/cdk/resize/demo/ResizableHandle.md
packages/cdk/resize/demo/ResizableHandle.vue
packages/cdk/resize/docs/Index.zh.md
packages/cdk/resize/index.ts
packages/cdk/resize/src/resizable/Resizable.tsx
packages/cdk/resize/src/resizable/ResizableHandle.tsx
packages/cdk/resize/src/resizable/types.ts
packages/cdk/resize/src/resizable/useResizable.ts
packages/cdk/resize/style/index.less
packages/cdk/types.d.ts
packages/components/modal/src/ModalWrapper.tsx
packages/pro/table/src/contents/ResizableHeadCell.tsx

refactor(cdk:drag-drop): code style

---

packages/components/select/src/Select.tsx

fix(comp:select): fix selected options display when filtered

---

packages/pro/layout/demo/Basic.vue
packages/pro/layout/demo/Collapsed.vue
packages/pro/layout/demo/Fixed.vue
packages/pro/layout/demo/Slots.vue
packages/pro/layout/demo/Theme.vue
packages/pro/layout/demo/Type.vue

docs(pro:layout): improve user reading experience

---

packages/components/carousel/src/composables/useAutoplay.ts
packages/components/modal/src/ModalWrapper.tsx
packages/components/style/themes/default.less
packages/components/style/themes/seer.less
packages/pro/layout/style/header.less
packages/pro/layout/style/mixin.less
packages/pro/layout/style/themes/default.variable.less
packages/pro/layout/style/themes/seer.variable.less

fix(pro:layout): update the scroll style on the dark theme

---

packages/cdk/portal/src/convertTarget.ts

FIXED: #949 
需要维护一份targetHashMap的缓存
删除targetHashMap，不维护缓存

fix(cdk:portal): remove targetHashMap

---

packages/components/carousel/src/Carousel.tsx
packages/components/carousel/src/composables/useStrategy.ts
packages/components/pagination/style/index.less

fix(comp:carousel): after click the same dot repeatedly, will not work

---

packages/components/card/docs/Index.zh.md
packages/pro/layout/docs/Index.zh.md
scripts/gen/style-variable/update.ts

docs: update less variables

---

packages/cdk/forms/__tests__/abstractControl.spec.ts
packages/cdk/forms/__tests__/validators.spec.ts
packages/cdk/forms/docs/Index.zh.md
packages/cdk/forms/src/controls.ts
packages/cdk/forms/src/messages/en-US.ts
packages/cdk/forms/src/messages/zh-CN.ts
packages/cdk/forms/src/types.ts
packages/cdk/forms/src/validators.ts
packages/components/form/demo/Message.vue
vitest.config.ts

feat(cdk:forms): add validator: range, rangeLength and update messages

---

packages/components/tree/src/Tree.tsx
packages/components/tree/src/node/TreeNode.tsx
packages/components/tree/src/token.ts

fix(comp:tree): style error after global showline is configured to true

---

packages/components/_private/checkable-list/__tests__/__snapshots__/checkableListItem.spec.ts.snap
packages/components/_private/checkable-list/src/CheckableList.tsx
packages/components/_private/checkable-list/src/CheckableListItem.tsx
packages/components/_private/checkable-list/style/index.less
packages/components/_private/checkable-list/style/themes/default.variable.less
packages/components/style/variable/prefix.less
packages/components/tree/style/themes/default.variable.less
packages/pro/transfer/src/content/ProTransferTree.tsx
packages/pro/transfer/style/index.less
packages/pro/transfer/style/themes/default.variable.less

穿梭框文字超长展示重叠
文字超长展示横向滚动条，删除按钮固定在右边

fix(pro:transfer): fix overflowed text style

---

packages/components/notification/index.ts
packages/pro/table/src/ProTable.tsx
packages/site/src/App.vue

配置了customAdditional的protable表格内容会显示不出

fix(pro:table): not working with customAdditional

---

packages/components/input-number/demo/Basic.vue
packages/components/input-number/docs/Index.zh.md
packages/components/input-number/src/InputNumber.tsx
packages/components/input-number/src/useInputNumber.ts
packages/components/input-number/style/index.less
packages/components/input-number/style/themes/default.variable.less

- 视觉未对齐
- slots失去了响应
- 调整视觉还原度
- 删除多余的 less 变量
- 修复ts类型
- slots移动位置可以实时响应

fix(comp:input-number): update control style

---

.npmrc
packages/components/alert/docs/Index.zh.md
packages/components/alert/src/Alert.tsx
packages/components/alert/src/types.ts
packages/components/input-number/src/InputNumber.tsx

feat(comp:alert): add onAfterClose

---

packages/components/transfer/src/types.ts
packages/components/tree/src/composables/useExpandable.ts
packages/pro/transfer/__tests__/proTransfer.spec.ts
packages/pro/transfer/demo/TreeLoadChildren.md
packages/pro/transfer/demo/TreeLoadChildren.vue
packages/pro/transfer/docs/Index.zh.md
packages/pro/transfer/src/ProTransfer.tsx
packages/pro/transfer/src/composables/useTransferData.ts
packages/pro/transfer/src/composables/useTransferTreeProps.ts
packages/pro/transfer/src/content/ProTransferTree.tsx
packages/pro/transfer/src/token.ts
packages/pro/transfer/src/types.ts
packages/pro/transfer/src/utils.ts

feat(pro:transfer): add tree loadChildren support

---

packages/components/_private/overflow/src/types.ts
packages/components/cascader/src/types.ts
packages/components/collapse/src/types.ts
packages/components/config/src/types.ts
packages/components/menu/src/types.ts
packages/components/select/src/types.ts
packages/components/stepper/src/types.ts
packages/components/table/src/types.ts
packages/components/tabs/src/types.ts
packages/components/tag/src/types.ts
packages/components/transfer/src/types.ts
packages/components/tree-select/src/types.ts
packages/components/tree/src/types.ts
packages/components/upload/src/types.ts
packages/pro/layout/src/types.ts
packages/pro/search/src/panel/SelectPanel.tsx
packages/pro/table/src/types.ts
packages/pro/transfer/src/ProTransfer.tsx
packages/pro/transfer/src/composables/useTransferTreeProps.ts
packages/pro/transfer/src/types.ts
packages/pro/tree/src/types.ts

refactor: resolve generics errors

---

packages/cdk/utils/src/props.ts
packages/components/table/docs/Index.zh.md

refactor(cdk:utils): remove readonly in props type

---

packages/cdk/drag-drop/demo/Basic.vue
packages/cdk/drag-drop/demo/MultipleTargets.vue

docs(cdk:drag-drop): add docs cursor

---

README.md
README.zh.md

the picture  link to npm@type  is not centered now
change the picture to center display
have a better display effect

docs: document display optimization

---

packages/components/icon/src/Icon.tsx

动态加载的图标，如果 svg 还未加载完成，就去修改 name, 会导致加载多个 svg

fix(comp:icon): name changes in a short time, multiple SVG are rendered

---

packages/components/watermark/demo/Basic.vue
packages/components/watermark/demo/Image.md
packages/components/watermark/demo/Image.vue
packages/components/watermark/docs/Index.zh.md
packages/components/watermark/src/Watermark.tsx
packages/components/watermark/src/composables/useAntiTamper.ts
packages/components/watermark/src/types.ts
packages/components/watermark/style/index.less

默认支持防水印篡改，可从前端有效避免恶意用户通过修改dom、样式等方式修改原水印
> 无法防御中间人篡改

feat(comp:watermark): add anti-tamper feature

---

packages/pro/search/src/searchItem/Segment.tsx
packages/pro/search/style/index.less
packages/pro/search/style/themes/default.variable.less

1. 标签撑开之后整体高度改变，影响整体下方布局
2. 激活状态下删除前置标签，overlay位置不更新
1. 撑开之后遮盖下方元素，不撑开最外围容器高度
2.  激活状态下删除前置标签，overlay位置更新，且重新聚焦

fix(pro:search): fix overflowed style to be overlap with elements below，fix overlay position update on item deleted

---

packages/components/switch/demo/Confirm.vue

first problem: When I try to cancel the switch status change by clicking cancel it failed
second problem: ths state changed when the switch blur
third problem: when I first click center button and the switch get out of control
corrected a small typo

docs(comp:switch): repair switch status

---

packages/components/menu/src/contents/menu-sub/MenuSub.tsx
packages/components/menu/src/contents/menu-sub/OverlayContent.tsx
packages/components/menu/style/index.less

fix #1013
对于子菜单，鼠标移出后快速移入，隐藏的节点又出现了
鼠标移出后快速移入，不会阻止菜单的隐藏。

fix(comp:menu): hover event cannot be triggered when animating

---

packages/components/table/__tests__/table.spec.ts
packages/components/table/docs/Index.zh.md
packages/components/table/src/composables/useColumns.ts
packages/components/table/src/main/body/BodyCell.tsx
packages/components/table/src/main/head/HeadCell.tsx
packages/components/table/src/types.ts
packages/components/table/src/utils/index.ts
packages/pro/table/src/types.ts
vitest.config.ts

feat(comp:table): ellipsis supports hidden the title

---

packages/cdk/popper/docs/Index.zh.md
packages/cdk/popper/src/hooks.ts
packages/cdk/popper/src/types.ts
packages/cdk/popper/src/usePopper.ts
packages/components/_private/overlay/src/Overlay.tsx
packages/components/_private/overlay/style/index.less
packages/components/_private/overlay/style/themes/default.variable.less
packages/components/dropdown/style/index.less
packages/components/form/__tests__/__snapshots__/form.spec.ts.snap
packages/components/form/__tests__/form.spec.ts
packages/components/form/demo/CustomizedValidation.vue
packages/components/form/demo/MessageTooltip.md
packages/components/form/demo/MessageTooltip.vue
packages/components/form/docs/Index.zh.md
packages/components/form/src/FormItem.tsx
packages/components/form/src/composables/useFormItem.ts
packages/components/form/src/types.ts
packages/components/form/style/index.less
packages/components/form/style/mixin.less
packages/components/form/style/status.less
packages/components/style/motion/fade.less
packages/components/tooltip/src/types.ts
packages/components/tooltip/src/useTooltipOverlay.ts
packages/components/tooltip/style/index.less

feat(comp:form): support for displaying message in tooltip

---

packages/pro/table/style/index.less

fix(comp:table): fix layout tool conflicts(#1010)

---

packages/cdk/forms/__tests__/abstractControl.spec.ts
packages/cdk/forms/__tests__/formArray.spec.ts
packages/cdk/forms/__tests__/formGroup.spec.ts
packages/cdk/forms/docs/Index.zh.md
packages/cdk/forms/src/controls.ts
packages/cdk/forms/src/validators.ts
packages/components/form/demo/Coordinated.vue

feat(cdk:forms): abstractControl support add or remove the validators

---

packages/components/tree-select/src/content/Content.tsx
packages/components/tree/__tests__/tree.spec.ts
packages/components/tree/docs/Index.zh.md
packages/components/tree/src/Tree.tsx
packages/components/tree/src/node/Content.tsx
packages/components/tree/src/node/TreeNode.tsx
packages/components/tree/src/token.ts
packages/components/tree/src/types.ts
packages/pro/tree/docs/Index.zh.md
packages/pro/tree/src/ProTree.tsx
packages/pro/tree/src/types.ts

feat(comp:tree): add checkOnClick prop

---

packages/pro/search/demo/ConvertToKeyword.md
packages/pro/search/demo/ConvertToKeyword.vue
packages/pro/search/demo/Invalid.md
packages/pro/search/demo/Invalid.vue
packages/pro/search/docs/Index.zh.md
packages/pro/search/index.ts
packages/pro/search/src/ProSearch.tsx
packages/pro/search/src/composables/useSearchItem.ts
packages/pro/search/src/composables/useSearchItemErrors.ts
packages/pro/search/src/composables/useSearchStates.ts
packages/pro/search/src/composables/useSegmentStates.ts
packages/pro/search/src/searchItem/SearchItem.tsx
packages/pro/search/src/segments/CreateSelectSegment.tsx
packages/pro/search/src/segments/createInputSegment.ts
packages/pro/search/src/types.ts
packages/pro/search/style/index.less
packages/pro/search/style/themes/default.variable.less

feat(pro:search): add validate function

---

packages/cdk/forms/src/utils.ts

fix(cdk:forms): the second argument to setValue is optional

---

scripts/gulp/build/apiParse.ts
scripts/gulp/build/index.ts
scripts/gulp/build/utils.ts

provide the api data exposed to idux-coder

build: add api-json build

---

scripts/gulp/build/apiParse.ts
scripts/gulp/build/index.ts
scripts/gulp/build/utils.ts

add parse anchor
add pro $extend
fix some bugs

build: update api-json build

---

scripts/gulp/build/rollup.ts

build: update rollup types

---

packages/components/date-picker/src/composables/useActiveValue.ts

日期范围面板 activeValue 合法性检测判断有问题，不应在起始日期的年小于结束日期的年时比对月份
修改以上问题

fix(comp:date-picker): fix date picker active value validation

---

packages/cdk/forms/src/utils.ts

refactor(cdk:forms): code optimization

---

packages/site/src/components/global/GlobalCodeBox.vue
packages/site/src/components/global/GlobalPlayground.vue

不支持从site跳转到playground
支持从site跳转到playground

feat: site add playground support

---

packages/cdk/forms/__tests__/formControl.spec.ts
packages/components/table/src/main/body/BodyCell.tsx
packages/components/table/style/index.less

fix(comp:table): the fixed column not work with ellipsis (#1081)

---

packages/pro/textarea/style/index.less

fix(pro:textarea): fix index column cell align-items

---

packages/components/form/style/index.less
packages/components/select/src/panel/Panel.tsx
packages/pro/table/index.ts

回退 #1032 的代码，解决 form-item 内容居中的问题。

fix(comp:form): the content of form-item is block

---

packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/input/docs/Api.zh.md
packages/components/input/src/types.ts
packages/components/input/src/useInput.ts
packages/components/textarea/docs/Api.zh.md

feat(comp:input): the trim supports global configuration

---

package.json
packages/cdk/types.d.ts
packages/components/table/docs/Api.zh.md
packages/pro/table/docs/Api.zh.md
packages/pro/table/src/ProTable.tsx
packages/pro/table/src/ProTableLayoutTool.tsx

- 支持 scrollTo
- 设置了禁止隐藏的列，不应该受选择全部的影响。

feat(pro:table): support scrollTo

---

packages/components/upload/src/types.ts

fix(comp:upload): action's type is wrong

---

packages/components/alert/demo/Loop.vue
packages/components/alert/demo/Pagination.vue
packages/components/pagination/__tests__/__snapshots__/pagination.spec.ts.snap
packages/components/pagination/src/Pagination.tsx
packages/components/pagination/src/contents/Jumper.tsx
packages/components/pagination/src/contents/Sizes.tsx
packages/components/pagination/src/token.ts
packages/components/pagination/style/index.less
packages/components/pagination/style/mixin.less
packages/components/pagination/style/themes/default.variable.less
packages/components/pagination/style/themes/seer.variable.less
packages/components/table/demo/AutoHeight.vue

fix(comp:pagination): sync design

---

packages/components/input/style/index.less

fix(comp:input): the clear icon should cover the suffix icon

---

packages/components/select/src/composables/usePanelActiveState.ts

select组件的datasource改变以及通过搜索过滤选项之后，active状态的选项没有改变
select组件的datasource改变以及通过搜索过滤选项之后，自动将当前active状态的选项改变为activeValue指向的选项，或者第一个选项（当的activeValue不存在时）

feat(comp:select): set first option active on search and options change

---

packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap
packages/components/tree/__tests__/tree.spec.ts

fix(comp:tree): fix tree unit tests

---

packages/components/table/docs/Theme.zh.md
packages/components/table/src/Table.tsx
packages/components/table/src/composables/useScroll.ts
packages/components/table/style/border.less
packages/components/table/style/index.less
packages/components/table/style/themes/default.variable.less
packages/pro/table/style/index.less

feat(comp:table): sync design

---

packages/components/select/src/composables/useSelectedState.ts

fix(comp:select): fix multipleLimit malfunction

---

packages/components/transfer/src/composables/useTransferData.ts
packages/pro/search/src/composables/useSearchStates.ts

fix(comp:transfer): fix onChange triggered timing
穿梭框以及复合搜索组件的onChange事件触发时机在实际value改变之前
将触发时机调整到改变之后

fix(pro:search): fix onChange triggered timing

---

packages/components/checkbox/style/index.less
packages/components/package.json
packages/components/style/variable/height.less
packages/components/table/docs/Theme.zh.md
packages/components/table/src/Table.tsx
packages/components/table/src/main/MainTable.tsx
packages/components/table/src/token.ts
packages/components/table/style/fixed.less
packages/components/table/style/index.less
packages/components/table/style/size.less
packages/components/table/style/themes/default.variable.less
packages/components/table/style/themes/seer.variable.less
packages/pro/package.json

fix(comp:table): sync design

---

packages/components/icon/src/dependencies.ts
packages/pro/tree/style/index.less

proTree 展开收起图标高度异常
修复以上问题，并在IDUX_ICON_DEPENDENCIES中添加 Collapse Uncollapse 图标

fix(pro:tree): collapse icon style error

---

packages/components/style/variable/height.less
packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
packages/components/table/__tests__/table.spec.ts
packages/components/table/src/main/MainTable.tsx
packages/components/table/src/main/body/Body.tsx
packages/components/table/src/main/body/BodyCell.tsx
packages/components/table/src/main/body/BodyRow.tsx
packages/components/table/src/main/head/Head.tsx
packages/components/table/src/main/head/HeadCell.tsx
packages/components/table/src/main/head/HeadRow.tsx
packages/components/table/style/index.less
packages/components/table/style/size.less
packages/components/table/style/themes/default.variable.less
packages/components/table/style/themes/seer.variable.less
packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap

- 调整了 cell 的一些 class 命名
- 为所有原始的 table 元素添加 class

fix(comp:table): sync design and add class to all table elements

---

packages/components/upload/__tests__/upload.spec.ts
packages/components/upload/docs/Api.zh.md
packages/components/upload/src/composables/useRequest.ts
packages/components/upload/src/types.ts

上传的文件通过onBeforeUpload取消后，文件状态仍然是 'selected'
上传的文件通过onBeforeUpload取消后，文件状态改为'cancel'

feat(comp:upload): add file status about upload cancel

---

packages/pro/search/demo/LoadOnVisible.md
packages/pro/search/demo/LoadOnVisible.vue
packages/pro/search/docs/Api.zh.md
packages/pro/search/src/panel/DatePickerPanel.tsx
packages/pro/search/src/panel/SelectPanel.tsx
packages/pro/search/src/searchItem/Segment.tsx
packages/pro/search/src/segments/CreateDatePickerSegment.tsx
packages/pro/search/src/segments/CreateDateRangePickerSegment.tsx
packages/pro/search/src/segments/CreateSelectSegment.tsx
packages/pro/search/src/segments/createCustomSegment.ts
packages/pro/search/src/types.ts

1. 全选不可配置
2. 业务需求，面板展开后加载数据
3. panelRenderer 由于 InputStyle 变化导致不必要的调用
1. 增加 selectField.fieldConfig.showSelectAll
2. 增加 onPanelVisibleChange
3. style 更新后操作dom设置style，不再直接传入computed变量

feat(comp:search) search select all configurable, add panelVisibleChange support 

---

packages/components/textarea/src/composables/useAutoRows.ts

Textarea组件 autoRows max 不起作用
修复以上问题

fix(comp:textarea): textarea autoRows max not working

---

packages/components/drawer/docs/Api.zh.md
packages/components/modal/docs/Api.zh.md
packages/components/table/docs/Api.zh.md
packages/components/table/src/main/body/BodyCell.tsx

docs(comp:table): add more description for emptyCell

---

packages/cdk/forms/src/messages/en-US.ts

为保证组件词条的专业性，检视并规范cdk下forms的英文词条

feat(cdk:forms): standardize English words for form verification

---

packages/components/table/src/composables/useScroll.ts
packages/components/table/src/main/MainTable.tsx
packages/components/table/style/index.less

数据异步加载等数据改变场景下，autoHeight不生效
修复以上问题

fix(comp:table): autoHeight not working when data changes

---

packages/cdk/scroll/__tests__/__snapshots__/virtualScroll.spec.ts.snap
packages/cdk/scroll/src/virtual/VirtualScroll.tsx
packages/cdk/scroll/src/virtual/composables/useScrollState.ts
packages/components/table/style/themes/seer.variable.less
packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap

refactor(cdk:scroll,comp:table): remove needless codes

---

packages/pro/search/src/ProSearch.tsx
packages/pro/search/src/types.ts
packages/pro/search/style/index.less

proSearch z-index 不正确，导致被遮挡
增加 z-index属性并改用 useZIndex 管理

feat(pro:search): add container zIndex support

---

packages/pro/table/src/ProTable.tsx
packages/pro/table/style/index.less

在某些场景下，thead 的高度计算错误，会导致 layout tool 的位置异常
layout tool 的位置不再根据 thead 的高度去计算。

fix(pro:table): pining the position of the layout tool

---

.eslintrc.js
packages/components/checkbox/src/Checkbox.tsx
packages/components/radio/src/Radio.tsx
packages/components/table/docs/Api.zh.md
packages/components/table/src/main/body/BodyCell.tsx
packages/components/table/src/types.ts
packages/components/table/style/index.less

- selectable 列支持自定义渲染单元格。
- 修复了 align 不生效的问题。

feat(comp:table): the selectable column supports custom cell

---

packages/components/_private/selector/src/Selector.tsx
packages/components/_private/selector/src/contents/Input.tsx
packages/components/_private/selector/src/token.ts
packages/components/cascader/__tests__/__snapshots__/cascader.spec.ts.snap
packages/components/pagination/__tests__/__snapshots__/pagination.spec.ts.snap
packages/components/select/__tests__/__snapshots__/select.spec.ts.snap
packages/components/tree-select/__tests__/__snapshots__/treeSelect.spec.ts.snap

selector组件，在allowInput为false时，使用中文输入法依然可以触发输入
修复以上问题

fix(comp:select): input shouldn't trigger when allowInput is false

---

packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/table/docs/Api.zh.md
packages/components/table/src/Table.tsx
packages/components/table/src/composables/useScrollOnChange.ts
packages/components/table/src/types.ts
packages/pro/table/src/types.ts

新增 scrollToTopOnChange 属性配置，支持在分页信息、筛选、排序变更之后滚动到顶部

feat(comp:table): add `scrollToTopOnChange` support

---

packages/components/button/__tests__/button.spec.ts
packages/components/button/src/Button.tsx
packages/components/button/style/index.less
packages/components/button/style/mixin.less

fix(comp:button): update the link button style

---

packages/cdk/forms/docs/Overview.zh.md

docs: fix error in forms cdk docs

---

packages/pro/layout/demo/Slots.vue
packages/pro/layout/demo/Theme.vue

点击【主题】和【插槽】demo中的导航栏按钮，会使得页面卡死
点击【主题】和【插槽】demo中的导航栏按钮，视窗会移动至demo位置
路由守卫中是否需要增加兜底机制防止无限循环？

fix(pro:layout): correct router-link's path (#1179)

---

packages/pro/layout/style/header.less

remove [display: flex] from [menu-vertical]
make 'header' type [pro-layout]'s menu normal

fix(pro:layout): remove [display: flex] from [menu-vertical] (#1178)

---

packages/components/tabs/demo/Scroll.vue
packages/components/tabs/src/Tabs.tsx
packages/components/tabs/src/composables/useOffset.ts
packages/components/tabs/src/composables/useSize.ts
packages/components/tabs/style/index.less
scripts/gulp/build/apiParse.ts

fix #1163
tab数量变化或者title改变时滚轮自适应出现

fix(comp:tabs): adaptive width when title changes

---

packages/pro/search/src/ProSearch.tsx

点击搜索按钮以及清除按钮会触发focus，弹出下拉框
修复以上问题

fix(pro:search): pro search btn click shoudn't trigger foucs

---

packages/components/table/src/composables/useScrollOnChange.ts
packages/components/transfer/demo/Remote.vue
packages/components/transfer/index.ts
packages/components/transfer/src/Transfer.tsx
packages/components/transfer/src/composables/useTransferData.ts
packages/components/transfer/src/composables/useTransferDataStrategies.ts
packages/components/transfer/src/composables/useTransferSelectState.ts
packages/components/transfer/src/content/Body.tsx
packages/components/transfer/src/token.ts
packages/components/transfer/src/types.ts
packages/pro/transfer/__tests__/proTransfer.spec.ts
packages/pro/transfer/demo/FlattenTree.md
packages/pro/transfer/demo/TreeCascaderStrategy.md
packages/pro/transfer/demo/TreeCascaderStrategy.vue
packages/pro/transfer/docs/Api.zh.md
packages/pro/transfer/src/ProTransfer.tsx
packages/pro/transfer/src/composables/useTransferTableProps.ts
packages/pro/transfer/src/composables/useTransferTreeProps.ts
packages/pro/transfer/src/composables/useTreeDataStrategy.ts
packages/pro/transfer/src/composables/useTreeDataStrategyContext.ts
packages/pro/transfer/src/content/ProTransferList.tsx
packages/pro/transfer/src/content/ProTransferTree.tsx
packages/pro/transfer/src/token.ts
packages/pro/transfer/src/types.ts
packages/pro/transfer/src/utils.ts
packages/pro/transfer/src/wrapper/TableTransferWrapper.tsx
packages/pro/transfer/src/wrapper/TreeTransferWrapper.tsx
packages/pro/transfer/style/index.less

feat(pro:transfer): add cascade strategy `off`

---

packages/cdk/forms/__tests__/abstractControl.spec.ts
packages/cdk/forms/__tests__/formArray.spec.ts
packages/cdk/forms/__tests__/formControl.spec.ts
packages/cdk/forms/__tests__/formGroup.spec.ts
packages/cdk/forms/__tests__/typeof.spec.ts
packages/cdk/forms/__tests__/utils.spec.ts
packages/cdk/forms/__tests__/validators.spec.ts
packages/cdk/forms/index.ts
packages/cdk/forms/src/models/abstractControl.ts
packages/cdk/forms/src/models/formArray.ts
packages/cdk/forms/src/models/formControl.ts
packages/cdk/forms/src/models/formGroup.ts
packages/cdk/forms/src/typeof.ts
packages/cdk/forms/src/types.ts
packages/cdk/forms/src/useForms.ts
packages/cdk/forms/src/utils.ts
packages/cdk/forms/src/validators.ts
packages/cdk/utils/src/typeof.ts
packages/components/form/src/composables/useFormItem.ts
packages/pro/form/docs/Index.zh.md
scripts/gulp/build/esbuild.ts
tests/setup.ts
tsconfig.json

refactor(cdk:forms): split the controls.ts

---

packages/cdk/drag-drop/src/composables/withDragHandle.ts

pointer 模式下具备 handle 的可拖拽容器阻止内部组件聚焦等问题
修复以上问题

fix(cdk:drag-drop): focus problem with pointer backend (#1202)

---

packages/components/watermark/demo/Custom.vue
packages/components/watermark/src/Watermark.tsx
packages/components/watermark/src/composables/useAntiTamper.ts

fix(comp:watermark): flickering problem

---

packages/components/cascader/style/index.less
packages/components/cascader/style/themes/default.variable.less

cascader选中和展开的option文字颜色为primary
修改颜色为 text-color
视觉检视

fix(comp:cascader): modify selected option text color

---

packages/components/switch/style/themes/seer.variable.less

switch存在box-shadow
seer皮肤下去掉box-shadow
视觉检视

fix(comp:switch): remove box-shadow for seer theme

---

packages/pro/textarea/src/ProTextarea.tsx
packages/pro/textarea/src/content/Content.tsx
packages/pro/textarea/src/token.ts
packages/pro/textarea/style/index.less

fix(pro:textarea): disabled not working

---

packages/components/_private/trigger/style/themes/default.variable.less
packages/components/form/style/themes/seer.variable.less
packages/components/style/themes/seer.less

style(comp:*): change text-disabled-color for seer theme

---

packages/components/textarea/__tests__/__snapshots__/textarea.spec.ts.snap
packages/components/textarea/src/composables/useAutoRows.ts
packages/components/textarea/src/composables/useLineHeight.ts

多行文本的行高与实际行高不一致，导致文字与行标不对其
修复以上问题

fix(comp:textarea): fix line-height to ensure height calculation

---

packages/cdk/version/index.ts
packages/components/version/index.ts
packages/pro/form/demo/Register.vue
packages/pro/version/index.ts
packages/site/src/components/views/home/Home.vue
packages/site/vite.config.ts
scripts/gulp/build/index.ts
scripts/gulp/build/rollup.ts
scripts/gulp/build/utils.ts
typings/global.d.ts

build: sync version

---

packages/site/src/docs/GettingStarted.zh.md

docs: add idux-coder into GettingStarted

---

packages/cdk/drag-drop/src/composables/withDragHandle.ts

fix(cdk:drag-drop): invalid handle (#1227)

---

packages/components/transfer/demo/CustomListBody.vue
packages/components/transfer/demo/CustomOperations.vue
packages/components/transfer/style/content.less
packages/components/transfer/style/themes/default.variable.less

1. 更新自定义列表内容的demo，符合seer规范
2. 修改Icon尺寸为16px
3. 修改clear-icon左边距
4. 修改自定义operations demo的按钮样式

fix(comp:transfer): update transfer style and demo

---

CHANGELOG.md
lerna.json
package.json
packages/cdk/CHANGELOG.md
packages/cdk/package.json
packages/components/CHANGELOG.md
packages/components/package.json
packages/components/tabs/__tests__/__snapshots__/tabs.spec.ts.snap
packages/pro/CHANGELOG.md
packages/pro/package.json
packages/site/CHANGELOG.md
packages/site/package.json
packages/site/src/docs/Changelog.zh.md

docs(release): publish v1.0.2

---

packages/components/transfer/demo/Searchable.md
packages/components/transfer/demo/Searchable.vue
packages/components/transfer/docs/Api.zh.md
packages/components/transfer/src/Transfer.tsx
packages/components/transfer/src/composables/useSearchPlaceholder.ts
packages/components/transfer/src/composables/useTransferBindings.ts
packages/components/transfer/src/content/Header.tsx
packages/components/transfer/src/types.ts
packages/pro/transfer/demo/TableMaxSelectedCnt.md
packages/pro/transfer/demo/TableMaxSelectedCnt.vue
packages/pro/transfer/src/types.ts
packages/pro/transfer/src/wrapper/TableTransferWrapper.tsx
packages/pro/transfer/src/wrapper/TreeTransferWrapper.tsx

新增 searchPlaceholder 属性
新增 表格穿梭框最大选中数量 demo

feat(*:transfer): add transfer searchPlaceholder prop; add table transfer max selected count demo

---

packages/components/input-number/style/index.less

style: input-number style error, when there is only suffix

---

packages/cdk/package.json

build: upgrade @floating-ui/dom

---

packages/components/slider/style/index.less
packages/components/slider/style/themes/default.variable.less
packages/components/stepper/src/StepperItem.tsx
packages/components/stepper/style/percent.less

1. 修改stepper中progress水平垂直不居中的问题
2. 修改stepper默认成功和失败的icon 为 success 和 info
3. 修改slider在vertical下dot的显示问题

fix(comp:stepper,comp:slider): fix stepper and slider styles

---

packages/components/button/docs/Theme.zh.md
packages/components/button/style/index.less
packages/components/button/style/mixin.less
packages/components/button/style/themes/default.variable.less
packages/components/button/style/themes/seer.variable.less
packages/components/style/themes/default.less
packages/components/style/themes/seer.less
packages/components/table/docs/Index.zh.md
packages/components/table/docs/Theme.zh.md
packages/components/table/src/main/body/BodyCell.tsx
packages/components/table/src/main/head/HeadCell.tsx
packages/components/table/src/utils/index.ts
packages/components/table/style/border.less
packages/components/table/style/fixed.less
packages/components/table/style/index.less
packages/components/table/style/size.less
packages/components/table/style/themes/default.less
packages/components/table/style/themes/default.variable.less
packages/components/table/style/themes/seer.less
packages/components/table/style/themes/seer.variable.less
packages/pro/table/style/index.less

- 表格配置 ellipsis 后，selectable 列显示省略号
- 表头分组的样式问题
- 支持 css variable
- 样式同步设计规范
- 修复 ellipsis  在 selectable, expandable 等列的样式问题

fix(comp:table): style update and ellipsis conflicts with column type

---

packages/pro/search/demo/MergeItems.md
packages/pro/search/demo/MergeItems.vue
packages/pro/search/src/composables/useFocusedState.ts

失去焦点时保留正在编辑的搜索条件
不再保留，失焦后重置
补充合并多个同类搜索项的demo
设计师需求补充

feat(pro:search): temp state is now cleared after blur, add merge items demo

---

packages/components/table/demo/Fixed.md
packages/components/table/demo/Fixed.vue
packages/components/table/src/composables/useColumns.ts
packages/components/table/src/main/ColGroup.tsx

fix(comp:table): resize column width with percentum not work

---

packages/components/_private/overlay/src/Overlay.tsx

overlay 在存在 arrow时，实际计算的offset没有考虑arrow的尺寸
修复以上问题

fix(comp:*): overlay offset with arrow should consider arrow size

---

packages/components/space/__tests__/space.spec.ts
packages/components/space/demo/Basic.vue
packages/components/space/demo/CustomSize.vue
packages/components/space/demo/Itemless.md
packages/components/space/demo/Itemless.vue
packages/components/space/demo/Size.vue
packages/components/space/demo/Vertical.vue
packages/components/space/demo/Wrap.vue
packages/components/space/docs/Api.zh.md
packages/components/space/src/Space.tsx
packages/components/space/src/types.ts
packages/components/space/style/index.less
packages/site/src/styles/themes/index.less

feat(comp:space): support itemless

---

packages/components/button/docs/Theme.zh.md
packages/components/button/style/index.less
packages/components/button/style/mixin.less
packages/components/button/style/themes/default.variable.less
packages/components/button/style/themes/seer.variable.less
packages/components/collapse/docs/Theme.zh.md
packages/components/collapse/style/index.less
packages/components/collapse/style/themes/default.variable.less
packages/components/header/demo/PrefixSuffix.vue
packages/components/header/style/index.less
packages/components/table/demo/TreeTable.vue
packages/components/table/docs/Theme.zh.md
packages/components/table/src/main/ColGroup.tsx
packages/components/table/style/size.less
packages/components/table/style/themes/default.variable.less

refactor: update css variable

---

package.json
packages/components/_private/loading/index.ts
packages/components/spin/src/Spin.tsx
packages/site/plugins/md/parseIndexDocs.ts
packages/site/src/components/global/GlobalTheme.vue
packages/site/src/components/layout/header/HeaderVersion.vue
packages/site/src/iduxInstall.ts
packages/site/vite.config.ts

docs: docs version supports switching

---

packages/site/index.html
packages/site/public/404.html
packages/site/src/components/views/home/Home.vue
packages/site/src/components/views/home/locales.ts
packages/site/src/docs/GlobalConfig.zh.md
packages/site/src/iduxInstall.ts
packages/site/src/main.ts
packages/site/vite.config.ts
typings/global.d.ts

build: base url supports configuration

---

packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap
packages/components/tree/src/Tree.tsx
packages/components/tree/style/index.less

tree的height在非virtual模式下不生效
修复以上问题

fix(comp:tree): height not working in non-virtual mode

---

packages/pro/transfer/src/composables/useTreeExpandedKeys.ts
packages/pro/transfer/src/wrapper/TreeTransferWrapper.tsx

refactor(pro:transfer): optimize tree expandedkeys sync performance

---

packages/components/date-picker/style/panel.less

选择年、月范围时，开始和结束的cell背景颜色比cell宽
修改背景实现方式，开始和结束的cell不再有溢出的选中背景

style(comp:date-picker): refactor year range in-range style

---

packages/components/button/style/index.less
packages/site/src/components/global/GlobalTheme.vue
packages/site/src/styles/themes/index.less

- text 和 link 的按钮，min-width 为 auto
- 修复 site 主题初次加载始终为 default 的问题

fix(comp:button): for text and link mode, the min-width is auto

---

packages/components/button/__tests__/__snapshots__/buttonGroup.spec.ts.snap
packages/components/button/__tests__/buttonGroup.spec.ts
packages/components/button/docs/Api.zh.md
packages/components/button/src/ButtonGroup.tsx
packages/components/button/src/types.ts
packages/components/button/style/index.less
packages/site/plugins/themePlugin.ts
packages/site/src/styles/themes/index.less

- ButtonGroup 使用 Space 实现，
- ButtonGroup 的 `gap` 即为 Space 的 `size`

feat(comp:button): the ButtonGroup extends Space

---

packages/components/button/demo/Danger.vue
packages/components/button/demo/Disabled.vue
packages/components/button/demo/Loding.vue
packages/components/button/demo/Mode.vue
packages/components/button/demo/Size.vue
packages/components/button/style/index.less

fix(comp:button): remove height for text and link mode

---

packages/components/alert/docs/Theme.zh.md
packages/components/alert/style/themes/default.variable.less
packages/components/alert/style/themes/seer.variable.less
packages/components/checkbox/style/index.less
packages/components/radio/docs/Theme.zh.md
packages/components/radio/style/index.less
packages/components/style/mixins/placeholder.less
packages/components/style/themes/default.less
packages/components/style/themes/seer.less
packages/components/table/docs/Theme.zh.md
packages/components/table/style/index.less
packages/components/table/style/themes/default.variable.less
packages/components/table/style/themes/seer.variable.less
packages/site/plugins/md/parseIndexDocs.ts
packages/site/src/styles/docs.less

style: update css variable

---

packages/components/form/demo/Basic.vue
packages/components/form/demo/Coordinated.vue
packages/components/form/demo/CustomizedValidation.vue
packages/components/form/demo/Layout.vue
packages/components/form/demo/Message.vue
packages/components/form/demo/MessageTooltip.vue
packages/components/form/demo/Nest.vue
packages/components/form/demo/Register.vue
packages/components/form/demo/Search.vue
packages/components/form/docs/Api.zh.md
packages/components/form/src/Form.tsx
packages/components/form/src/types.ts

- 新增 onSubmit 配置，默认会阻止掉表单的提交事件。

feat(comp:form): prevent the default submit event

---

packages/components/tree/style/index.less

fix(comp:tree): leafLineIcon style not alignment

---

packages/components/button/style/index.less

button-group内部嵌套button-group时，子级会被父级样式影响

fix(comp:button): button-group style error when nesting itself

---

packages/components/dropdown/demo/Button.vue
packages/components/dropdown/docs/Index.zh.md
packages/components/dropdown/docs/Theme.zh.md
packages/components/dropdown/style/index.less
packages/components/dropdown/style/themes/default.variable.less

fix(comp:dropdown): style update and css variable support

---

packages/components/alert/docs/Theme.zh.md
packages/components/checkbox/style/index.less
packages/components/layout/docs/Index.zh.md
packages/components/layout/docs/Theme.zh.md
packages/components/layout/src/LayoutSider.tsx
packages/components/layout/style/index.less
packages/components/layout/style/themes/default.variable.less
packages/components/layout/style/themes/seer.variable.less
packages/components/menu/docs/Theme.zh.md
packages/components/menu/style/themes/default.variable.less
packages/components/radio/style/index.less
packages/components/style/themes/default.less
packages/components/style/themes/seer.less
packages/components/table/docs/Theme.zh.md
packages/components/table/style/themes/default.variable.less

fix(comp:layout): style update and css vaiable support

---

packages/components/date-picker/style/index.less
packages/components/drawer/style/index.less
packages/components/modal/style/index.less
packages/components/time-picker/style/index.less

存在footer的组件，按钮在loading状态下不垂直居中
修复以上问题

fix(comp:*): footer buttons aren't aligned when loading

---

packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap
packages/components/tree/__tests__/tree.spec.ts
packages/components/tree/src/composables/useDataSource.ts
packages/pro/tree/__tests__/proTree.spec.ts

搜索没有匹配到且存在已展开节点时，全部节点被渲染
搜索没有匹配到且存在已展开节点时， 返回空

fix(comp:tree): all nodes should be hidden when search not matched

---

packages/components/button/docs/Theme.zh.md
packages/components/button/src/Button.tsx
packages/components/button/style/index.less
packages/components/button/style/mixin.less
packages/components/button/style/themes/default.variable.less
packages/components/button/style/themes/seer.variable.less
packages/components/date-picker/style/index.less
packages/components/drawer/style/index.less
packages/components/modal/style/index.less
packages/components/time-picker/style/index.less

fix(comp:button): style problems caused by line-height with loading

---

packages/components/dropdown/style/index.less
packages/components/menu/style/dark.less
packages/components/menu/style/index.less
packages/components/menu/style/light.less
packages/components/menu/style/mode.less
packages/components/menu/style/themes/default.variable.less
packages/components/table/docs/Theme.zh.md
packages/components/table/style/themes/seer.variable.less
packages/pro/layout/demo/Type.vue
packages/pro/layout/docs/Api.zh.md
packages/pro/layout/docs/Theme.zh.md
packages/pro/layout/src/types.ts
packages/pro/layout/style/dark.less
packages/pro/layout/style/header.less
packages/pro/layout/style/index.less
packages/pro/layout/style/light.less
packages/pro/layout/style/sider.less
packages/pro/layout/style/themes/default.variable.less
packages/pro/layout/style/themes/seer.variable.less
packages/site/src/styles/layout/header.less
packages/site/src/styles/theme.less

style(pro:layout): update css variable

---

packages/components/tabs/style/index.less

style(comp:tabs): modify style in line mode

---

packages/components/alert/style/themes/seer.variable.less
packages/components/dropdown/style/index.less
packages/components/types.d.ts
packages/pro/table/src/types.ts

- 在 dropdown 内的 menu 使用 dark 的时候，背景色会被覆盖
- 修复了 ProTableColumn 的类型错误
- Seer 主题下的 alert warring 文字颜色不正确

fix(comp:dropdown): update style with dark menu

---

packages/components/alert/docs/Theme.zh.md
packages/components/menu/docs/Api.zh.md
packages/components/menu/docs/Theme.zh.md
packages/components/table/__tests__/table.spec.ts
packages/components/table/docs/Api.zh.md
packages/components/table/src/main/body/Body.tsx

仅配置了 autoHeight, 但是没有配置 scroll 的时候，表头会消失

fix(comp:table): the head is hidden when with autoHeight and not scroll

---

packages/components/spin/style/index.less
packages/components/style/core/reset.less
packages/components/style/themes/default.less

- reset 里的 less 变量用 css variable 代替
- spin 组件里的 hsl 颜色用 rgba 代替

style: reset.less supports css variable

---

packages/pro/table/src/composables/useColumns.ts
packages/pro/table/src/contents/LayoutToolContent.tsx
packages/pro/table/src/contents/LayoutToolTree.tsx
packages/pro/table/style/index.less

- 列的 visible 配置修改，没有触发 onColumnsChange

fix(pro:table): column visible change should be trigger onColumnsChange

---

packages/pro/table/src/ProTable.tsx
packages/pro/table/src/composables/useResizable.ts

fix(pro:table): resizable not work

---

packages/pro/tree/demo/Basic.vue
packages/pro/tree/style/index.less

fix(pro:tree): expandIcon style error without header

---

packages/components/button/__tests__/__snapshots__/buttonGroup.spec.ts.snap
packages/components/button/docs/Api.zh.md
packages/components/button/src/ButtonGroup.tsx
packages/components/button/src/types.ts
packages/components/button/style/index.less

refactor(comp:button): the default align is center

---

packages/cdk/popper/__tests__/__snapshots__/popper.spec.ts.snap
packages/cdk/popper/src/convertOptions.ts

fix(cdk:popper): shift middleware does not work on the arrow

---

packages/components/checkbox/style/index.less

fix(comp:checkbox): style error when disabled

---

packages/pro/table/src/types.ts

fix(pro:table): wrong type of ellipsis

---

packages/components/progress/__tests__/__snapshots__/progress.spec.ts.snap
packages/components/progress/demo/Segment.vue
packages/components/progress/src/Circle.tsx
packages/components/progress/src/Line.tsx

trailColor not work
trailColor works fine
update docs
before:
now:

fix(comp:progress): trailColor not work

---

packages/components/empty/demo/Image.md
packages/components/empty/demo/Image.vue
packages/components/empty/docs/Api.zh.md
packages/components/empty/src/types.ts
packages/components/empty/style/index.less
packages/components/table/style/themes/seer.variable.less
packages/pro/table/style/index.less

fix(comp:empty): style update with icon

---

packages/pro/layout/__tests__/__snapshots__/layoutPro.spec.ts.snap
packages/pro/layout/__tests__/layoutPro.spec.ts
packages/pro/layout/docs/Api.zh.md
packages/pro/layout/src/contents/Logo.tsx
packages/pro/layout/src/types.ts

fix(pro:layout): the dom still renders without the logo

---

packages/components/button/src/Button.tsx
packages/components/button/style/index.less
packages/components/button/style/mixin.less
packages/components/icon/src/dependencies.ts

- 按钮的 dispaly 从 inline-flex => inline-block, 解决在 Space 组件内的行高问题。
- 移除 focus 样式，同步设计规范。

fix(comp:button): display to inline-block and remove focus style

---

packages/components/alert/docs/Theme.zh.md
packages/components/alert/style/themes/default.variable.less
packages/components/checkbox/style/index.less
packages/components/empty/docs/Theme.zh.md
packages/components/empty/style/themes/default.variable.less
packages/components/form/docs/Theme.zh.md
packages/components/form/style/themes/default.variable.less
packages/components/input/docs/Theme.zh.md
packages/components/input/style/themes/default.variable.less
packages/components/radio/style/index.less
packages/components/style/mixins/placeholder.less
packages/components/style/themes/default.less
packages/components/style/themes/seer.less
packages/components/table/docs/Theme.zh.md
packages/components/table/style/themes/default.variable.less
packages/components/tooltip/docs/Theme.zh.md
packages/components/tooltip/style/themes/default.variable.less
packages/components/tooltip/style/themes/seer.variable.less

- 禁用的文字颜色降低一个等级 
- placeholder 的颜色与禁用相同

fix(comp:*): the text color variable update

---

packages/cdk/package.json
packages/components/_private/overlay/style/index.less

1. 更新floating-ui版本
2. 修改reference-hidden下浮层隐藏样式，增加opacity: 0;

fix(cdk:popper): update floating-ui to fix position error under scale

---

packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/tabs/__tests__/__snapshots__/tabs.spec.ts.snap
packages/components/tabs/__tests__/tabs.spec.ts
packages/components/tabs/demo/Size.md
packages/components/tabs/demo/Size.vue
packages/components/tabs/docs/Api.zh.md
packages/components/tabs/docs/Theme.zh.md
packages/components/tabs/index.ts
packages/components/tabs/src/InternalTabs.tsx
packages/components/tabs/src/types.ts
packages/components/tabs/style/index.less
packages/components/tabs/style/themes/default.variable.less
packages/components/tabs/style/themes/seer.variable.less

feat(comp:tabs): add size props, default value is md

---

packages/cdk/breakpoint/src/mediaQuery.ts

query shouldn't be destroyed when same query is used elsewhere
同时在两个组件中注册useBreakpoints，并使用相同的query，其中一个组件卸载会导致另外组件中监听不到breakpoints变化
修复以上问题，增加引用次数逻辑，引用次数降为0才销毁

fix(cdk:breakpoint): query unexpectedly destroyed

---

packages/cdk/package.json
packages/components/package.json
packages/pro/package.json
scripts/gulp/build/utils.ts

使用vue-cli创建一个vue3项目，按照文档方式引入组件，发现样式不生效，没有被引入
https://cli.vuejs.org/zh/guide/build-targets.html#vue-vs-js-ts-%E5%85%A5%E5%8F%A3%E6%96%87%E4%BB%B6
正常引入

fix: failed to import style file, in webpack project

---

packages/components/date-picker/src/composables/useTriggerProps.ts
packages/components/time-picker/src/composables/useTriggerProps.ts

时间范围以及日期范围选择，值为空数组时可以显示清除图标并清除
修改以上问题，空数组和undefined都视为空

Fix picker range clearable

---

packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/table/demo/EditRows.vue
packages/components/table/demo/Indexable.md
packages/components/table/demo/Indexable.vue
packages/components/table/docs/Api.zh.md
packages/components/table/index.ts
packages/components/table/src/composables/useColumns.ts
packages/components/table/src/main/body/BodyCell.tsx
packages/components/table/src/types.ts
packages/components/table/style/size.less
packages/pro/config/src/defaultConfig.ts
packages/pro/config/src/types.ts
packages/pro/table/docs/Api.zh.md
packages/pro/table/src/types.ts
packages/pro/table/style/index.less
packages/site/src/docs/GettingStarted.zh.md
packages/site/src/docs/GlobalConfig.zh.md

- 序号列的序号计算不正确
- 按照分页的算法去计算序号。
- 普通Table 也支持序号列。

fix(comp:table): incorrect serial number

---

packages/components/drawer/src/DrawerWrapper.tsx
packages/components/menu/src/contents/menu-sub/MenuSub.tsx
packages/components/modal/src/ModalWrapper.tsx

- 动画还未结束前就销毁了组件（例如：路由发生改变），会产生报错。

fix(comp:modal): reading contains after onmounted causes an exception

---

packages/pro/search/src/ProSearch.tsx

搜索项在非聚焦时隐藏样式缺少了overflow:hidden，导致页面内容被遮挡
修改以上问题

fix(pro:search): search items covers dom content when bluerd

---

packages/components/cascader/src/Cascader.tsx
packages/components/cascader/style/index.less
packages/components/dropdown/src/Dropdown.tsx
packages/components/dropdown/style/index.less
packages/components/menu/src/contents/menu-sub/MenuSub.tsx
packages/components/menu/style/index.less
packages/components/select/src/Select.tsx
packages/components/select/style/index.less
packages/components/style/motion/slide.less
packages/components/style/themes/default.less
packages/components/style/variable/animation.less
packages/components/tree-select/src/TreeSelect.tsx
packages/components/tree-select/style/index.less

为 dropdown, menu, cascader,select, tree-select 等组件添加 slide-up 动画

refactor(comp:*): use slide-up animation

---

packages/components/table/src/composables/useFilterable.ts
packages/components/table/src/composables/useSortable.ts
packages/components/table/src/main/head/HeadCell.tsx

- vue2 的版本在异步获取 columns 时，sorter 和 filter 不能正常工作。
- 兼容 vue2 的版本

fix(comp:table): sort and filter not work with async columns

---

packages/components/table/index.ts
packages/pro/table/src/ProTable.tsx
packages/pro/table/src/types.ts

fix(pro:table): emptyCell is not declared in props

---

packages/components/anchor/docs/Index.zh.md
packages/components/anchor/docs/Theme.zh.md
packages/components/anchor/style/index.less
packages/components/anchor/style/themes/default.variable.less
packages/components/anchor/style/themes/seer.variable.less

fix(comp:anchor): style update and css variable support

---

packages/components/back-top/demo/Basic.vue
packages/components/back-top/demo/Custom.vue
packages/components/back-top/docs/Index.zh.md
packages/components/back-top/docs/Theme.zh.md
packages/components/back-top/style/index.less
packages/components/back-top/style/themes/default.variable.less
packages/components/back-top/style/themes/seer.variable.less
packages/components/style/themes/default.less

fix(comp:back-top): style update and css variable support

---

packages/components/_private/overlay/src/Overlay.tsx
packages/components/anchor/style/index.less

- 快速切换 Menu 的子菜单，会导致定位异常
- https://github.com/IDuxFE/idux/pull/1304 导致的问题，回退代码

fix(comp:overlay): quick switch visible causes positioning error

---

packages/components/input-number/style/index.less

fix(comp:input-number): buttons of inc and dec are not hidden by default

---

packages/cdk/breakpoint/src/breakpoints.ts
packages/cdk/resize/src/resizable/types.ts
packages/components/collapse/style/index.less
packages/components/header/style/index.less
packages/components/loading-bar/src/types.ts
packages/components/notification/src/types.ts
packages/components/pagination/style/index.less
packages/pro/search/src/types/searchFields.ts
packages/pro/tree/style/index.less

- 移除了 header 的背景色
- 移除 pagination 的 disabled 状态下的背景色
- ProTree 的 header 高度最小 40px

fix(comp:header): remove breakground-color

---

packages/cdk/forms/__tests__/abstractControl.spec.ts
packages/cdk/forms/demo/Basic.vue
packages/cdk/forms/docs/Api.zh.md
packages/cdk/forms/src/models/abstractControl.ts
packages/cdk/forms/src/types.ts
packages/components/form/demo/Register.vue
packages/components/menu/style/themes/default.variable.less
packages/components/menu/style/themes/seer.variable.less

- disabled 支持配置一个函数，以支持需要动态禁用的场景

feat(cdk:forms): the disabled of ValidatorOptions support function

---

commitlint.config.js
packages/site/src/components/global/GlobalTheme.vue

官网右下角这个按钮，形状变形了并且图标也没居中。
修改了 css 样式之后
提交 commit 信息的时候，描述里面没有和 docs 相关的，所以 commit 一直报错。所以在 commitlint 里面添加了 docs，但是我觉得这样不太合理。

fix(docs):  setting btn's icon is not centered

---

packages/cdk/forms/__tests__/abstractControl.spec.ts
packages/cdk/forms/__tests__/formControl.spec.ts
packages/cdk/forms/__tests__/validators.spec.ts
packages/cdk/forms/docs/Api.zh.md
packages/cdk/forms/src/messages/en-US.ts
packages/cdk/forms/src/validators.ts
packages/components/form/demo/Message.md
packages/components/form/demo/Message.vue
packages/components/form/demo/Register.vue

Validators.setMessages 新增第二个参数，以更好的支持 i18n

feat(cdk:forms): the setMessages supports setting locale for i18n

---

packages/site/src/styles/app.less

点击标题旁的锚链接，是突然跳过去的
点击标题旁的锚链接，平滑的滚动到顶部

feat(docs): make scroll smooth

---

packages/components/tree/style/index.less

fix(comp:tree): incorrect style when node is selected

---

packages/components/cascader/src/Cascader.tsx
packages/components/dropdown/src/Dropdown.tsx
packages/components/menu/style/index.less
packages/components/select/src/Select.tsx
packages/components/style/motion/slide.less
packages/components/tree-select/src/TreeSelect.tsx

- 根据浮层的位置自动调整 slide  动画的位置和方向。

fix(comp:*): use a smarter slide animation

---

packages/components/_private/collapse-transition/style/index.less
packages/components/date-picker/src/composables/useOverlayProps.ts
packages/components/style/motion/slide.less
packages/components/style/themes/default.less
packages/components/style/themes/seer.less
packages/components/style/variable/animation.less
packages/components/time-picker/src/composables/useOverlayProps.ts
packages/pro/search/src/ProSearch.tsx
packages/pro/search/src/composables/useCommonOverlayProps.ts

- 更新所以动画的时间
- 浮层类面板组件都统一使用 slide-auto 动画

refactor(comp:*): update transition duration

---

packages/components/table/src/composables/useScroll.ts

fix(comp:table): onScroll not work

---

packages/components/notification/src/types.ts

refactor(comp:notification): remove key in props

---

packages/components/table/__tests__/table.spec.ts
packages/components/table/src/composables/useDataSource.ts
packages/components/table/src/composables/usePagination.ts
packages/components/table/src/composables/useScrollOnChange.ts

fix(comp:table): the size of pagination cannot be overridden

---

packages/pro/search/src/searchItem/Segment.tsx

when segment panel renders as empty, overlayOpended state change will cause overlay to blink
当面板渲染函数返回空的时候，overlayOpend还为true，导致面板的展开状态实际有多种情况：
1. 面板渲染为空， overlayOpened true
2. 面板渲染不空， overlayOpened false
导致在数据响应变化过程中由于两个状态变化的时机不统一，而面板的显示可能会存在闪烁的情况
修复以上问题
用一个变量保存面板的渲染是否为空，overlayOpened 状态合并判断面板的渲染结果

fix(pro:search): segment panel overlay shouldn't blink

---

packages/components/tree-select/style/index.less
packages/components/tree/style/index.less
packages/pro/transfer/style/index.less
packages/pro/tree/style/index.less

样式权重比较混乱，经常容易改动引发
优化样式权重，加上前缀：
1. 组件特定状态样式为`.ix-tree.ix-tree-[status]`，
2. 组件内部元素样式为`.ix-tree .ix-tree-[status]`

refactor(comp:tree): optimize styles

---

packages/components/_private/empty/__tests__/__snapshots__/empty.spec.ts.snap
packages/components/empty/__tests__/__snapshots__/empty.spec.ts.snap
packages/components/empty/src/Images.tsx
packages/components/empty/style/index.less

- 解决带有渐变的 svg 图标在同时渲染多个时，可能存在 id 冲突的问题。
- 移除了 imgae 100% height 的样式

fix(comp:empty): resolve id conflicts in svg

---

packages/components/input/demo/Addon.vue
packages/components/select/style/index.less
packages/pro/table/style/index.less

- Select 的分组 label 的字体为 10px => 12px
- ProTable 的布局设置的样式问题

fix: component style update

---

packages/components/menu/docs/Theme.zh.md
packages/components/menu/style/themes/default.variable.less

style(comp:menu): modify menu item hover background color

---

packages/components/date-picker/docs/Theme.zh.md
packages/components/date-picker/style/themes/seer.variable.less

修改面板头部的按钮（年月选择，向前向后）字体大小为12px
视觉检视问题

style(comp:date-picker): modify header btn font-size for seer

---

packages/components/table/docs/Theme.zh.md
packages/components/table/style/fixed.less
packages/components/table/style/index.less
packages/components/table/style/themes/seer.variable.less

1. 去掉seer主题下选中的行的背景颜色
2. 修改固定列的阴影颜色，降低透明度到12%
视觉检视问题

style(comp:table): remove selected row's background color，decrease fixed column's box-shadow opacity

---

packages/components/dropdown/docs/Theme.zh.md
packages/components/dropdown/style/index.less
packages/components/dropdown/style/themes/default.variable.less
packages/components/dropdown/style/themes/seer.variable.less

下拉菜单无边距
为在dropdown中的menu增加padding，padding大小与select一致
视觉检视问题

style(comp:dropdown): add padding to menu within dropdown

---

packages/components/stepper/style/index.less

步骤条的连线，由于border-radius的存在，dashed不起作用
去掉border-radius

fix(comp:stepper): stepper tail dashed style isn't working

---

packages/components/transfer/demo/CustomHeaderLabelSuffix.vue
packages/components/transfer/src/composables/usePagination.ts
packages/components/transfer/style/content.less

1. 分页没有快速跳转
2. 头部的后缀没有垂直居中
3. demo中的后缀加号图标尺寸应该是16px
修复以上问题

fix(comp:transfer): pagination should enable quick jumper, meanwhile fix header suffix style

---

packages/pro/tree/demo/Basic.vue

docs(pro:tree): modify demo style

---

packages/components/pagination/docs/Theme.zh.md
packages/components/pagination/style/index.less
packages/components/pagination/style/themes/default.variable.less
packages/components/pagination/style/themes/seer.variable.less

add color variable to modify colors of total,sizes,jumper for seer theme
新增less 变量控制 total、sizes、jumper 的颜色，并调整 seer 主题中三者的颜色
视觉检视问题

style(comp:pagination): add color variable for total,sizes,jumper

---

packages/pro/transfer/__tests__/proTransfer.spec.ts

ci(pro:transfer): fix test errors

---

packages/components/_private/mask/style/themes/default.variable.less
packages/components/desc/docs/Theme.zh.md
packages/components/modal/demo/Footer.vue
packages/components/modal/docs/Index.zh.md
packages/components/modal/docs/Theme.zh.md
packages/components/modal/src/ModalWrapper.tsx
packages/components/modal/style/index.less
packages/components/modal/style/themes/default.variable.less
packages/components/modal/style/themes/seer.variable.less
packages/components/style/themes/default.less
packages/pro/tree/docs/Theme.zh.md

fix(comp:modal): style update and css variable support

---

packages/components/drawer/docs/Index.zh.md
packages/components/drawer/style/index.less

refactor(comp:drawer): show theme variables in docs

---

packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
packages/components/table/demo/Server.vue
packages/components/table/demo/TreeTable.vue
packages/components/table/docs/Api.zh.md
packages/components/table/src/composables/useSelectable.ts
packages/components/table/src/main/body/BodyCell.tsx

- 展开列叶子节点的 `indent` 配置不生效
- 对于后端分页的场景，已经选中的数据，再切换页面后，没有被缓存，onChange 回调的数据中丢失。

fix(comp:table): the indent not work and selected records not cached

---

packages/pro/search/demo/CustomLabel.md
packages/pro/search/demo/CustomLabel.vue
packages/pro/search/docs/Api.zh.md
packages/pro/search/src/ProSearch.tsx
packages/pro/search/src/composables/useSearchItem.ts
packages/pro/search/src/panel/SelectPanel.tsx
packages/pro/search/src/searchItem/SearchItem.tsx
packages/pro/search/src/searchItem/Segment.tsx
packages/pro/search/src/segments/CreateCascaderSegment.tsx
packages/pro/search/src/segments/CreateNameSegment.tsx
packages/pro/search/src/segments/CreateOperatorSegment.tsx
packages/pro/search/src/token.ts
packages/pro/search/src/types/proSearch.ts
packages/pro/search/src/types/searchFields.ts
packages/pro/search/src/types/segment.ts

新增 `customNameLabel` 和 `searchField.customOperatorLabel` ，用来自定义 name 和 操作符 下拉选择框 label

feat(pro:search): add `customNameLabel` and `customOperatorLabel`

---

packages/cdk/forms/src/models/abstractControl.ts

fix(cdk:forms): disabled according to status

---

package.json
packages/cdk/package.json
packages/components/package.json
packages/pro/package.json
packages/site/package.json

ci: add clean script

---

packages/components/cascader/__tests__/cascader.spec.ts
packages/components/cascader/src/Cascader.tsx

IxCascader 的 onChange 失效
修复以上问题
补充测试用例

fix(comp:cascader): onChange not working

---

packages/components/select/src/Select.tsx
packages/components/select/src/composables/useKeyboardEvents.ts

- 开启 searchable 和 multiple 
- 输入搜索内容
- 选中任意选项
导致搜索内容清空
搜索内容不清空

fix(comp:select): searchable with multiple works abnormally

---

packages/components/date-picker/style/panel.less
packages/components/date-picker/style/themes/default.variable.less
packages/components/date-picker/style/themes/seer.variable.less

修改 date-picker panel 的 header 中 方向按钮的 font-size 为 16px
去掉范围选择面板的分割线

style(comp:date-picker): update date-picker header and separator style

---

packages/components/select/src/composables/usePanelActiveState.ts

panel 的 activeValue 属性无法被赋值为 undefined，即设置激活状态的选项为空
修复以上问题

fix(comp:select): panel active value couldn't be set as undefined

---

packages/cdk/scroll/src/virtual/composables/useScrollPlacement.ts

某些情况下(例如浏览器缩放), 会导致 scrollTop 出现小数，newScrollTop 始终小于 maxScrollHeight
所以对 newScrollTop 进行了向上取整，避免此种情况的出现。

fix(cdk:scroll): the onScrolledBottom is not triggered

---

packages/components/button/docs/Theme.zh.md
packages/components/date-picker/docs/Theme.zh.md
packages/components/header/docs/Theme.zh.md
packages/components/popconfirm/docs/Theme.zh.md
packages/components/table/docs/Theme.zh.md
packages/components/table/style/themes/seer.variable.less
packages/components/timeline/docs/Theme.zh.md
packages/pro/search/docs/Theme.zh.md

fix(comp:table): fixed column background color error is selected

---

packages/components/tabs/src/contents/TabNavWrapper.tsx

fix(comp:tabs): more pane should hidden when empty data

---

CHANGELOG.md
lerna.json
packages/cdk/CHANGELOG.md
packages/cdk/package.json
packages/components/CHANGELOG.md
packages/components/package.json
packages/pro/CHANGELOG.md
packages/pro/package.json
packages/site/CHANGELOG.md
packages/site/package.json
packages/site/src/docs/Changelog.zh.md

docs(release): publish v1.6.1

---

packages/pro/search/docs/Api.zh.md

docs(pro:search): add docs for new API after 1.6.0

---

packages/pro/search/src/components/quickSelect/QuickSelectItem.tsx

有操作符的搜索项，在快捷选择面板中选中之后不会触发更新
修复以上问题，快捷选择面板中选中后不做任何校验判断，全部触发更新

fix(pro:search): all items triggered by quickselect should be updated

---

packages/components/tabs/src/composables/useSizeObservable.ts

- 在 `type='line'` 模式下，`dataSource` 动态变化的时候，选中的下划线偏移位置不正确。

fix(comp:tabs): incorrect offset of the selected bar with dynamic tabs

---

packages/components/style/mixins/reset.less
packages/components/style/themes/default.less
packages/components/style/themes/seer.less
packages/components/table/style/index.less
packages/pro/search/src/ProSearch.tsx
packages/pro/search/style/quick-select.less

- 在 reset-scroll 中新增了迷你滚动条的 class 名：.ix-scroll-min
- scroll 的变量由 less => css variable

feat(comp:style): add min scroll and css variable support

---

packages/components/popconfirm/style/index.less

- 同步设计规范，调整了 title 和 cotent 的边距

fix(comp:popconfirm): sync design

---

packages/components/tabs/docs/Api.zh.md
packages/components/tabs/src/Tabs.tsx
packages/components/tabs/src/composables/useSizeObservable.ts
packages/components/tabs/src/contents/TabNav.tsx
packages/components/tabs/src/contents/TabNavWrapper.tsx
packages/components/tabs/src/tokens.ts
packages/components/tabs/style/index.less

- 文档中的滑动 Demo 有 bug, 更多浮层展开后没有数据
- 新增了 addIcon 的插槽
- 更多浮层展开数据显示正常

feat(comp:tabs): support addIcon slot

---

CHANGELOG.md
lerna.json
packages/cdk/CHANGELOG.md
packages/cdk/package.json
packages/components/CHANGELOG.md
packages/components/package.json
packages/pro/CHANGELOG.md
packages/pro/package.json
packages/site/CHANGELOG.md
packages/site/package.json
packages/site/src/docs/Changelog.zh.md

docs(release): publish v1.7.0

---

packages/components/form/style/themes/default.variable.less

fix(comp:form): the disabled color using css variable

---

CHANGELOG.md
lerna.json
packages/cdk/CHANGELOG.md
packages/cdk/package.json
packages/components/CHANGELOG.md
packages/components/package.json
packages/pro/CHANGELOG.md
packages/pro/package.json
packages/site/CHANGELOG.md
packages/site/package.json
packages/site/src/docs/Changelog.zh.md

docs(release): publish v1.7.1

---

packages/components/icon/src/dependencies.ts

fix(comp:image): fix comp:image issue: icon [file-image] load failed

---

packages/components/tree/style/index.less

拖动目标节点样式使用box-shadow会导致遮盖问题
改为使用::after元素的border

fix(comp:tree): change drop node box-shadow to border

---

packages/cdk/forms/demo/CustomForm.vue
packages/components/tree/style/index.less

- 样式优先级问题，还有 :not() 选择器的兼容性问题。

fix(comp:tree): improve browser compatibility

---

packages/components/config/src/seerConfig.ts

seer 主题的树展开收起图标不符合设计规范
增加树展开收起图标的全局配置

style(comp:tree): update expandIcon global config for seer

---

packages/components/carousel/style/index.less

轮播图切换点击的区域太小
利用伪元素扩大可点击区域，最小16px，最大32px

fix(comp:carousel): dot clickable area is too small

---

packages/pro/search/demo/Custom.vue
packages/pro/search/demo/MultiSegment.md
packages/pro/search/demo/MultiSegment.vue
packages/pro/search/docs/Api.zh.md
packages/pro/search/src/ProSearch.tsx
packages/pro/search/src/components/NameSelectOverlay.tsx
packages/pro/search/src/components/SearchItem.tsx
packages/pro/search/src/components/quickSelect/QuickSelectItem.tsx
packages/pro/search/src/components/quickSelect/QuickSelectShortcut.tsx
packages/pro/search/src/components/segment/Segment.tsx
packages/pro/search/src/composables/useActiveSegment.ts
packages/pro/search/src/composables/useResolvedSearchFields.ts
packages/pro/search/src/composables/useSearchItem.ts
packages/pro/search/src/composables/useSearchStateWatcher.ts
packages/pro/search/src/composables/useSearchStates.ts
packages/pro/search/src/composables/useSegmentStates.ts
packages/pro/search/src/segments/CreateCascaderSegment.tsx
packages/pro/search/src/segments/CreateDatePickerSegment.tsx
packages/pro/search/src/segments/CreateDateRangePickerSegment.tsx
packages/pro/search/src/segments/CreateSelectSegment.tsx
packages/pro/search/src/segments/CreateTreeSelectSegment.tsx
packages/pro/search/src/segments/createCustomSegment.ts
packages/pro/search/src/segments/createInputSegment.ts
packages/pro/search/src/token.ts
packages/pro/search/src/types/searchFields.ts
packages/pro/search/src/types/segment.ts

feat(pro:search): add visible and extends for custom field config
新增 `multiSegment` 类型搜索项
自定义搜索项类型配置新增 visible配置输入段的显示隐藏

feat(pro:search): add `mutiSegment` field

---

packages/pro/index.ts
packages/pro/search/demo/CustomShortcuts.md
packages/pro/search/demo/CustomShortcuts.vue
packages/pro/search/demo/QuickSelect.md
packages/pro/search/docs/Api.zh.md
packages/pro/search/index.ts
packages/pro/search/src/components/quickSelect/QuickSelectPanel.tsx
packages/pro/search/src/components/quickSelect/QuickSelectShortcut.tsx
packages/pro/search/src/types/quickSelectPanel.ts
packages/pro/search/style/quick-select.less
packages/pro/types.d.ts

快捷面板shortcuts不支持自定义
增加插槽：`shortcuts`, `shortcuts`, `shortcutLabel`, `shortcutIcon` 支持自定义shortcuts
增加 `IxProSearchShortcut` 组件暴露，方便自定义shortcuts

feat(pro:search): add IxProSearchShortcut comp and shortcut slots

---

packages/site/src/components/global/GlobalSetting.vue

[docs] 文档内部导航跳转会卡一下，体验不好
fix #1538
既然是懒加载，那就加一个progress来缓解焦虑。。。

fix(docs): add loadingBar to show progress

---

packages/components/checkbox/__tests__/checkbox.spec.ts
packages/components/checkbox/demo/Fieldset.md
packages/components/checkbox/demo/Fieldset.vue
packages/components/checkbox/docs/Api.zh.md
packages/components/checkbox/docs/Theme.zh.md
packages/components/checkbox/src/Checkbox.tsx
packages/components/checkbox/style/index.less
packages/components/checkbox/style/themes/default.variable.less
packages/components/form/demo/Basic.vue
packages/components/form/demo/Coordinated.vue
packages/components/form/demo/Message.vue
packages/components/form/demo/Register.vue
packages/components/form/demo/Search.vue
packages/components/form/docs/Theme.zh.md
packages/components/radio/__tests__/radioGroup.spec.ts
packages/components/radio/demo/Fieldset.md
packages/components/radio/demo/Fieldset.vue
packages/components/radio/docs/Api.zh.md
packages/components/radio/docs/Theme.zh.md
packages/components/radio/src/RadioGroup.tsx
packages/components/radio/style/index.less
packages/components/radio/style/themes/default.variable.less
packages/components/radio/style/themes/seer.variable.less
packages/pro/textarea/docs/Theme.zh.md

- checkbox 和 radio-group 组件支持 fieldset 插槽

feat(comp:checkbox,radio): support fieldset slot

---

packages/components/cascader/docs/Api.zh.md
packages/components/cascader/src/Cascader.tsx
packages/components/cascader/src/types.ts
packages/components/table/demo/ScrollLoad.md
packages/components/table/demo/ScrollLoad.vue
packages/components/tree-select/docs/Api.zh.md
packages/components/tree-select/src/TreeSelect.tsx
packages/components/tree-select/src/content/Content.tsx
packages/components/tree-select/src/types.ts

- tree-select: 新增 searchPlaceholder 和 spin 配置
- cascader: 新增 searchPlaceholder 配置

feat(comp:tree-select): support searchPlaceholder and spin 

---

packages/components/table/docs/Api.zh.md
packages/components/table/src/main/head/triggers/FilterableTrigger.tsx
packages/components/table/src/types.ts

- customMenu 新增了 ` { selectedKeys: VKey[]; setSelectedKeys: (value: VKey[]) => void }` 两个参数

fix(comp:table): the customMenu of filterable add parameters

---

packages/site/package.json

vue-router 4.0.0版本的esm打包后文件存在问题
升级vue-router

docs: site vue-router version outdated

---

packages/components/config/src/defaultConfig.ts
packages/components/transfer/__tests__/__snapshots__/transfer.spec.ts.snap
packages/components/transfer/__tests__/__snapshots__/transferSlots.spec.ts.snap
packages/components/transfer/docs/Api.zh.md
packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap

fix(comp:transfer): transfer header clear icon error

---

packages/components/modal/style/themes/seer.variable.less

style(comp:modal): change body icon size to 40px for seer theme

---

packages/pro/search/style/quick-select.less

style(pro:search): update quick select panel style

---

packages/components/modal/demo/Type.vue

docs(comp:modal): update typed modal demo

---

packages/components/table/style/index.less
packages/components/table/style/size.less

表格头部的筛选和排序trigger的间距不正确
修复以上问题

fix(comp:table): header sort and filter trigger size not right

---

packages/components/select/style/themes/default.variable.less

多选下被分组的选项左边距不正确，应当和分组标题对齐
修复以上问题

style(comp:select): modify multiple select grouped option padding

---

packages/components/date-picker/demo/Shortcuts.md
packages/components/date-picker/demo/Shortcuts.vue
packages/components/date-picker/demo/ShortcutsWithTime.md
packages/components/date-picker/demo/ShortcutsWithTime.vue

docs(comp:date-picker): add shortcuts demo

---

packages/components/pagination/src/Pagination.tsx

fix(comp:pagination): sizeChanger should be supported for simple mode

---

packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap
packages/components/tree/__tests__/tree.spec.ts
packages/components/tree/src/composables/useDataSource.ts
packages/components/tree/src/composables/useExpandable.ts
packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap

树节点的禁用没有考虑级联，即父节点禁用或者全部子节点禁用，在级联非off的情况下应当同时为禁用
修复以上问题

fix(comp:tree): tree node disabled should be cascade

---

packages/components/divider/style/index.less

style(comp:divider): remove divider label indent

---

packages/pro/table/style/index.less

高级表格布局工具的树节点label距离多选框为8px
根据规范，修改为4px

style(pro:table): change layout tool item padding

---

packages/components/dropdown/demo/Basic.vue
packages/components/dropdown/demo/Button.vue

docs(comp:dropdown): add rotate animation to demos

---

packages/components/config/src/defaultConfig.ts

fix(comp:upload): default icon config not right

---

packages/components/dropdown/demo/Basic.vue
packages/components/dropdown/demo/Button.vue

docs(comp:dropdown): arrow rotate direction error

---

packages/components/alert/__tests__/__snapshots__/alert.spec.ts.snap
packages/components/config/src/defaultConfig.ts

warning类型的alert图标不正确，应当为 exclamation-circle
修复以上问题

fix(comp:alert): modify warning icon to `'exclamation-circle'`

---

packages/pro/config/src/defaultConfig.ts
packages/pro/config/src/types.ts
packages/pro/search/demo/Size.md
packages/pro/search/demo/Size.vue
packages/pro/search/index.ts
packages/pro/search/src/ProSearch.tsx
packages/pro/search/src/types/proSearch.ts
packages/pro/search/style/index.less
packages/pro/search/style/mixin.less
packages/pro/search/style/themes/default.variable.less

高级搜索新增 size 属性配置，支持 `md` 和 `sm`。

feat(pro:search): add `size` prop

---

packages/components/table/docs/Api.zh.md
packages/components/table/src/main/body/BodyCell.tsx
packages/components/table/src/types.ts

表格的selectable列的customCell自定义渲染参数增加 record 和 rowIndex，方便根据实际数据进行提示等自定义

feat(comp:table): supports record for customCell of selectable column

---

packages/components/radio/src/RadioGroup.tsx

fix(comp:radio): remove unnecessory console statement

---

packages/components/config/src/seerConfig.ts

fix(comp:stepper): modify size config to `'sm'` for seer theme

---

packages/components/config/src/seerConfig.ts

fix(comp:config): modify seer global config

---

packages/components/config/src/defaultConfig.ts
packages/components/text/__tests__/__snapshots__/text.spec.ts.snap

fix(comp:text): copy icon of default global config error

---

packages/components/radio/style/index.less

单选框的圆点位置是固定写死的，导致大尺寸下位置不正常
位置改为calc百分比计算

fix(comp:radio): radio dot size and position shouldn't be constant

---

packages/pro/search/style/mixin.less

fix(pro:search): placeholder not vertially centered

---

packages/components/config/src/seerConfig.ts

修改 seer 主题的全局配置，使表格的展开收起按钮和树的展开收起按钮一致

style(comp:table): modify table expandable icon global config for seer

---

packages/components/table/demo/NestedTable.vue

嵌套表格使用了children字段保存子表格数据，和childrenKey一致导致和内部的树表格逻辑冲突，demo展示不正常
修复嵌套表格的demo

docs(comp:table): fix nested table demo

---

packages/components/upload/src/composables/useUploadControl.ts

fix(comp:upload): remove unecessary console log statement

---

packages/components/table/docs/Api.zh.md
packages/components/table/src/Table.tsx
packages/components/table/src/other/Pagination.tsx

feat(comp:table): add `pagination` slot

---

packages/components/config/src/defaultConfig.ts
packages/components/config/src/seerConfig.ts
packages/components/config/src/types.ts
packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
packages/components/table/__tests__/table.spec.ts
packages/components/table/src/composables/useColumns.ts
packages/components/table/src/composables/useDataSource.ts
packages/components/table/src/main/body/BodyCell.tsx
packages/components/table/src/main/body/BodyRow.tsx
packages/components/table/src/main/body/RenderBodyRow.tsx
packages/components/table/src/types.ts
packages/components/table/style/expandable.less
packages/components/table/style/index.less
packages/components/table/style/selectable.less
packages/components/table/style/size.less
packages/components/table/style/themes/default.variable.less
packages/components/table/style/triggers.less

支持对树型数据的展示添加连线
`TableColumnExpandable` 新增 `showLine` 属性配置是否显示连线
提交涉及到了expandableCell的部分dom和css修改

feat(comp:table): support `expandable.showLine` for tree data

---

packages/pro/locales/src/langs/en-US.ts
packages/pro/locales/src/langs/zh-CN.ts
packages/pro/locales/src/types.ts
packages/pro/search/demo/Basic.vue
packages/pro/search/demo/RemoteSearch.vue
packages/pro/search/docs/Api.zh.md
packages/pro/search/src/ProSearch.tsx
packages/pro/search/src/composables/useResolvedSearchFields.ts
packages/pro/search/src/segments/CreateSelectSegment.tsx
packages/pro/search/src/types/searchFields.ts

高级搜索的select类型搜索项支持配置 `concludeAllSelected`，将全部选中的value解析成 `"全部"`

feat(pro:search): support `concludeAllSelected` for select field

---

packages/pro/search/src/ProSearch.tsx

fix(pro:search): overflowd item count is incorrect

---

packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
packages/components/table/src/main/body/BodyCell.tsx
packages/components/table/style/expandable.less
packages/components/table/style/size.less
packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap

展开收起列的文字没有垂直居中对齐
修复以上问题，给展开收起列的文字包裹一个span并配置vertical-aligin: middle

fix(comp:table): expandable cell text not vertial aligned

---

packages/components/date-picker/docs/Api.zh.md
packages/components/upload/docs/Api.zh.md
packages/pro/search/docs/Api.zh.md

docs: update componet docs

---

packages/components/desc/src/Desc.tsx

fix #1710
Using the header slot header component does not take effect
Using the header slot header component  take effect

fix(comp:desc): header component does not take effect

---

packages/cdk/drag-drop/style/index.less

fix(cdk:drag-drop): remove user-select none style

---

packages/components/button/style/index.less

按钮禁用时会触发hover等事件
按钮禁用时不触发hover等事件

fix(comp:button): pointer event none when btn is disabled

---

packages/components/desc/__tests__/__snapshots__/descriptions.spec.ts.snap
packages/components/desc/src/Desc.tsx
packages/components/desc/style/index.less

fix(comp:desc): use div to wrap header slot

---

packages/components/dark.full.css
packages/components/default.full.css
packages/components/table/docs/Theme.zh.md
packages/components/table/style/index.less
packages/components/table/style/size.less
packages/components/table/theme/dark.css
packages/components/table/theme/default.css
packages/components/table/theme/default.ts
packages/components/table/theme/tokens.ts
packages/site/src/docs/CustomizeTheme.zh.md

表格行高的实现是通过一个固定高度来实现最小高度的，不符合设计要求
改用上下边距加文字行高来构成基础行高
修改原来的rowPaddingxxx主题token为 cellPaddingxxx
新增 bodyCellVerticalAlign 主题变量

feat(comp:table): change rowHeight theme tokens to paddings

---

packages/components/modal/src/ModalBody.tsx

confirm模式的modal的icon与warning模式的不一致
confirm模式的modal的icon与warning模式的一致

fix(comp:modal): adjust the icon of the modal that confirm the mode

---

packages/components/modal/style/index.less

modal中的icon lineheight不对并且未垂直居中
modal中的icon lineheight比icon高度上下多4px并垂直居中

fix(comp:modal): fix adjust modal icon height

---

packages/components/skeleton/theme/default.ts
packages/components/skeleton/theme/index.ts
packages/components/table/theme/default.ts
packages/components/table/theme/index.ts
packages/components/theme/src/themeTokens/dark/presetTokens.ts
packages/components/theme/src/themeTokens/shared/extendedTokens/getExtendedColorTokens.ts
packages/pro/search/style/index.less
packages/pro/search/style/variables.less
packages/pro/search/theme/default.ts
packages/pro/search/theme/tokens.ts
packages/pro/textarea/demo/Basic.vue
packages/pro/textarea/style/index.less
packages/pro/textarea/theme/default.ts
packages/pro/textarea/theme/tokens.ts

feat: modify disable color theme tokens

---

packages/cdk/forms/docs/Api.zh.md
packages/cdk/forms/src/models/abstractControl.ts
packages/cdk/forms/src/models/formArray.ts
packages/cdk/forms/src/models/formControl.ts
packages/cdk/forms/src/models/formGroup.ts
packages/cdk/forms/src/types.ts
packages/components/form/demo/InteractionsTrigger.md
packages/components/form/demo/InteractionsTrigger.vue
packages/components/form/demo/Register.vue
packages/components/form/src/composables/public.ts

新增 trigger ‘interactions’
当没有输入的值并且处于失焦状态，blur后校验
当有输入的值，或者校验非法时，change后校验

feat(cdk:forms): add `interactions` trigger

---

packages/cdk/forms/src/models/abstractControl.ts
packages/components/form/demo/InteractionsTrigger.vue

trigger 为 interactions 时表现不正常
修复以上问题

fix(cdk:forms): interactions trigger dosen't work

---

packages/components/select/style/index.less
packages/pro/search/style/panel.less

selectOptionFontSize 主题变量 引用错误
修改 `--ix-select-font-size` 为 `--ix-select-option-font-size`

fix(comp:select): selectOptionFontSize theme var reference error

---

packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
packages/components/table/demo/AutoHeight.vue
packages/components/table/demo/Basic.vue
packages/components/table/demo/Expandable.vue
packages/components/table/demo/VirtualBoth.vue
packages/components/table/demo/VirtualHorizontal.vue
packages/components/table/src/Table.tsx
packages/components/table/src/composables/useScroll.ts
packages/components/table/src/main/MainTable.tsx
packages/components/table/src/main/body/Body.tsx
packages/components/table/src/main/body/BodyRowSingle.tsx
packages/components/table/src/main/body/RenderBodyRow.tsx
packages/components/table/style/fixed.less
packages/components/table/style/size.less
packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap

表格数据为空的时候，依然展示分页
开启横向虚拟滚动时，空状态展示异常，表格横向滚动条消失
数据为空的时候不应该展示分页
修复虚拟滚动下的空状态展示问题

fix(comp:table): pagination should hide when data empty

---

packages/components/header/docs/Theme.zh.md
packages/components/header/style/index.less
packages/components/header/theme/dark.css
packages/components/header/theme/default.css
packages/components/header/theme/default.ts
packages/components/header/theme/tokens.ts

修改header组件的竖线样式，去掉圆角，宽度改为2px，右边距离文字改为6px
提供barBorderRadius、barMarginRight主题变量

fix(comp:head): modify header bar style

---

packages/cdk/popper/__tests__/__snapshots__/popper.spec.ts.snap
packages/cdk/popper/docs/Api.zh.md
packages/cdk/popper/src/composables/useOptions.ts

修改popper的默认placement为bottomStart

fix(cdk:popper): modify default placement to `bottomStart`

---

packages/components/upload/src/composables/useUploadControl.ts

在 maxCount 是 1 的时候，新选中的文件应该替换掉原本的文件并且触发上传，但是没有触发上传
修复以上问题

fix(comp:upload): file is not uploaded when maxCount is 1

---

packages/components/config/src/defaultConfig.ts

IxUpload组件文件移除按钮图标不正确
改为 'close'

fix(comp:upload): file remove icon should be 'close'

---

packages/components/tabs/style/index.less

fix(comp:tabs): tabs segment mod nav font-weight should be normal

---

packages/components/alert/theme/tokens.ts
packages/components/theme/src/themeTokens/shared/derivedTokens/getDerivedColorTokens.ts
packages/components/theme/src/themeTokens/shared/getBasicTokens.ts

fix(comp): modify offline color token

---

packages/components/timeline/theme/default.ts

IxTimeLine的内容区底部margin为20，不符合设计稿
修改 contentMarginBottom 为 marginSizeLg，即16px

fix(comp:timeline): modify contentMarginBottom to marginSizeLg

---

packages/components/tag/theme/default.ts
packages/components/tag/theme/index.ts
packages/components/tag/theme/tokens.ts

标签的背景颜色不符合设计稿
修改标签的填充背景颜色
新增 bgColorNormal 主题token，用来修改标签的默认背景颜色

fix(comp:tag): modify tag normal bg color

---

packages/pro/search/style/panel.less
packages/pro/search/style/quick-select.less
packages/pro/search/style/variables.less

ProSearch 的间距相关样式均为硬编码
快捷面板的间距不符合设计稿
替换间距相关的样式，使用主题css变量
修改快捷面板的部分间距

fix(pro:search): replace spacing with theme tokens

---

packages/components/tree/src/Tree.tsx
packages/components/tree/src/node/Expand.tsx

fix(comp:tree): virtual treeNode slots not passed

---

packages/components/empty/demo/Content.vue

1. empty组件的demo中，p标签与按钮下间距不对
2. 按钮组件尺寸不是40px
1. empty组件的demo中，p标签与按钮下间距为20px
2. 按钮组件尺寸是40px

fix(comp:empty): change empty slot demo style

---

packages/components/header/style/index.less

header标签左侧的竖条，高度不对
竖条永远比文字矮,整体居中

fix(comp:header): change bar height

---

packages/components/table/demo/TreeTable.vue

树表格的demo中，表头居右了
树表格的demo中，表头居左

fix(comp:table): set table head align left

---

packages/components/modal/demo/Type.vue

model的demo中，p标签与footer有下间距
p标签与footer无下间距

fix(comp:modal): set demo margin bottom 0px

---

packages/components/dropdown/demo/Basic.vue
packages/components/dropdown/demo/Button.vue

droup down 的demo中icon未对齐
droup down 的demo中icon对齐

fix(comp:dropdown): demo icon vertical center

---

packages/components/collapse/style/index.less

fix(comp:collapse): change header margin right

---

packages/components/tag/style/index.less

tag组件的左右间距为7px（减去了border的1px）
设置tag组件的左右间距为8px

fix(comp:tag): change tag padding x to 8px

---

packages/components/_private/date-panel/src/panel-body/PanelCell.tsx
packages/components/upload/src/composables/useFileSelect.ts
packages/pro/search/src/components/quickSelect/QuickSelectItem.tsx
packages/pro/search/src/composables/useSearchItem.ts

build: fix lint errors

---

packages/pro/search/style/quick-select.less

fix(pro:search): quick select panel search bar overflows

---

packages/components/collapse/docs/Theme.zh.md
packages/components/collapse/theme/dark.css
packages/components/collapse/theme/default.css
packages/components/dark.full.css
packages/components/default.full.css
packages/components/tag/docs/Theme.zh.md
packages/components/tag/theme/dark.css
packages/components/tag/theme/default.css

docs(comp): update theme docs

---

packages/components/dark.full.css
packages/components/default.full.css
packages/components/select/docs/Theme.zh.md
packages/components/select/theme/dark.css
packages/components/select/theme/default.css
packages/components/select/theme/default.ts

optionGroupMargin  的单位不正确
修复以上问题

fix(comp:select): theme token optionGroupMargin unit error

---

packages/components/_private/selector/src/composables/useInputState.ts

下拉框由单选变多选时，有个输入框宽度太大
下拉框由单选变多选时，有个输入框宽度正常

fix(comp:select): when  input change multiply model input width is error

---

packages/components/tree/style/index.less
packages/components/tree/style/mixin.less
packages/components/tree/theme/default.ts
packages/components/tree/theme/tokens.ts

fix(comp:tree): modify tree line spacing

---

packages/components/tree-select/theme/default.ts
packages/pro/transfer/style/index.less
packages/pro/tree/demo/Basic.vue
packages/pro/tree/style/variables.less

调整过树组件连线间距之后，涉及到该组件的节点间距表现不正常
修复以上问题

style(pro:transfer,tree): modify tree node horizontal padding

---

packages/components/header/style/index.less

header组件的竖条，在有description的时候，和title不对齐
修复以上问题

fix(comp:header): header bar should aligned top

---

packages/components/table/style/expandable.less
packages/components/table/style/size.less

fix(comp:table): tree table line doesn't appear normally

---

packages/site/src/docs/V1ToV2.zh.md

docs: update deprecated API list

---

packages/cdk/forms/src/models/abstractControl.ts
packages/components/icon/src/Icon.tsx

cdk form 和 icon 疑似存在内存泄漏
修复以上问题

fix(cdk:form,comp:icon): fix suspected memory leak

---

packages/components/theme/src/themeTokens/shared/color/getBaseColors.ts

fix(comp:theme): base color turquoise not correct

---

packages/pro/tree/src/ProTree.tsx
packages/pro/tree/style/index.less

1. 展开收起过程中，会出现横向滚动条
2. 当collapsedWidth 过小时，会出现展开收起图表不居中的问题
1. 展开收起的动画过程中，将overflow变为hidden
2. 收起状态时，头部的对齐方式改为水平居中

fix(pro:tree): optimize collapse transition apperance

---

tea.yaml

> Decentralized technology protocol that enables OSS developers to be rewarded for their software contributions
https://app.tea.xyz/sign-up?r=H76_yCoegsc 
追加贡献者方式：在codeOwners字段追加贡献者的tea id，并在quorum +1 即可享受项目分成

chore: claim TEA tokens

---

packages/components/theme/src/composables/useThemeProvider.ts
packages/components/theme/src/composables/useTokenRegister.ts
packages/components/theme/src/useThemeToken.ts
packages/components/theme/src/utils/tokenToCss.ts

用户需要自定义业务token时，不希望使用 --ix 前缀，而使用单独的前缀，但现在不支持
支持自定义注册的token的变量前缀

feat(comp:theme): supports prefix for token register

---

packages/components/tour/src/composables/useActiveStep.ts
packages/components/tour/src/composables/useStepChange.ts

在 tour 组件实例创建之后异步添加的step，不能正常显示
修复以上问题

fix(comp:tour): async appended steps doesn't work

---

packages/components/tour/demo/TargetDisabled.md
packages/components/tour/demo/TargetDisabled.vue
packages/components/tour/docs/Api.zh.md
packages/components/tour/src/Mask.tsx
packages/components/tour/src/composables/useActiveStep.ts
packages/components/tour/src/types.ts
packages/components/tour/style/index.less

支持通过 `targetDisabled` 或者 `step.targetDisabled` 禁用点击区域

feat(comp:tour): supports `targetDisabled`

---

packages/components/dark.full.css
packages/components/default.full.css
packages/components/tour/docs/Theme.zh.md
packages/components/tour/theme/dark.css
packages/components/tour/theme/default.css

docs(comp:tour): update theme doc

---

packages/components/input/style/index.less
packages/components/input/style/mixin.less
packages/components/selector/style/multiple.less

IxInput 组件的 addon 中渲染的 select 组件，其样式不正常
修复以上问题

fix(comp:input): select style component within input addon isn't correct

---

packages/components/list/__tests__/__snapshots__/list.spec.ts.snap
packages/components/spin/__tests__/__snapshots__/spin.spec.ts.snap
packages/components/spin/docs/Theme.zh.md
packages/components/spin/src/Spin.tsx
packages/components/spin/style/index.less
packages/components/spin/theme/dark.css
packages/components/spin/theme/default.css
packages/components/spin/theme/default.ts
packages/components/spin/theme/tokens.ts
packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap

通过 useSpin 创建的spin，其背景颜色不正确
1. 修改原本通过opacity实现的spin背景为背景颜色，并提供主题变量配置
2. 修改通过 useSpin 创建的 spin 背景颜色，和直接使用 IxSpin 一致

fix(comp:spin): spin mask background color isn't correct

---

packages/pro/tag-select/src/content/TagSelectPanel.tsx

fix(pro:tag-select): max exceeded alert content error

---

packages/components/dark.full.css
packages/components/default.full.css
packages/components/modal/docs/Theme.zh.md
packages/components/modal/style/index.less
packages/components/modal/theme/dark.css
packages/components/modal/theme/default.css
packages/components/modal/theme/default.ts
packages/components/modal/theme/tokens.ts

modal的title没有配置word-break，遇到过长的文字例如路径，会无法换行出现横向滚动条
新增 wordBreak 主题token配置 word-break 行为，默认为 break-word

fix(comp:modal): modal title should have word break

---

packages/components/breadcrumb/theme/default.ts

fix(comp:breadcrumb): modify breadcrumb fontSize to fontSizeMd

---

packages/pro/textarea/docs/Api.zh.md
packages/pro/textarea/src/ProTextarea.tsx
packages/pro/textarea/src/composables/useRowsCounts.ts
packages/pro/textarea/src/types.ts

feat(pro:textarea): add rows prop

---

packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
packages/components/table/src/main/body/BodyCell.tsx
packages/components/table/src/main/body/RenderBodyCells.tsx
packages/components/table/src/types.ts
packages/components/table/style/border.less
packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap

fix(comp:table): table cell border missing when row span included

---

packages/pro/table/src/contents/LayoutToolContent.tsx

高级表格，将某一列修改为固定到列首或列尾后，列的顺序没有变化
修改固定位置后，顺序应该变化，即固定到列首则顺序提前到首部，固定到列尾则顺序调整到尾部

fix(pro:table): column sequence should change after fixed changed

---

packages/components/table/src/main/MainTable.tsx

表格列的 colSpan 和 rowSpan 函数接收的参数并不是原始数据对象
修复以上问题

fix(comp:table): rowSpan and colSpan param error

---

packages/components/table/src/composables/useScroll.ts

表格的固定列在初始渲染或者因为resize导致固定列状态变化后，阴影没有展示
修复以上问题

fix(comp:table): fixed column shadow are displayed after resize

---

packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap
packages/pro/transfer/__tests__/proTransfer.spec.ts
packages/pro/transfer/demo/TreeTable.md
packages/pro/transfer/demo/TreeTable.vue
packages/pro/transfer/docs/Api.zh.md
packages/pro/transfer/src/composables/useTransferTableProps.ts
packages/pro/transfer/src/composables/useTreeContext.ts
packages/pro/transfer/src/content/ProTransferTable.tsx
packages/pro/transfer/src/content/RenderRemovableLabel.tsx
packages/pro/transfer/src/token.ts
packages/pro/transfer/src/types.ts
packages/pro/transfer/src/wrapper/TableTransferWrapper.tsx
packages/pro/transfer/src/wrapper/TreeTransferWrapper.tsx
packages/pro/transfer/style/index.less

新增 `'tree-table'` 类型的 穿梭框，即树表格穿梭框

feat(pro:transfer): supports tree-table type transfer

---

packages/components/config/src/defaultConfig.ts

alert info 类型的图标为 bulb
调整为 info-circle

fix(comp:alert): modify alert info type icon to info-circle

---

packages/components/utils/src/useTreeCheckState.ts
packages/pro/transfer/src/composables/useTransferTableProps.ts
packages/pro/transfer/src/content/RenderRemovableLabel.tsx

rafactor(pro:transfer): tree-table trnasfer remove not working

---

packages/components/tabs/src/Tabs.tsx
packages/components/tabs/src/contents/MoreSelectPane.tsx
packages/components/tabs/src/tokens.ts

tabs 的所有面板中的选中的tab项，没有展示选中的状态样式
修复以上问题

fix(comp:tabs): all tabs panel should have selected state

---

packages/components/table/src/composables/useSelectable.ts

当表格数据是空的时候，全选的checkbox是勾选状态
不应该被勾选

fix(comp:table): select all shouldn't be checked when empty

---

.npmrc

ci: set link-workspace-packages to true

---

packages/pro/tag-select/demo/Validate.md
packages/pro/tag-select/demo/Validate.vue
packages/pro/tag-select/docs/Api.zh.md
packages/pro/tag-select/src/composables/usePanelActiveState.ts
packages/pro/tag-select/src/composables/useTagData.ts
packages/pro/tag-select/src/content/TagDataEditPanel.tsx
packages/pro/tag-select/src/content/TagSelectOption.tsx
packages/pro/tag-select/src/content/TagSelectPanel.tsx
packages/pro/tag-select/src/token.ts
packages/pro/tag-select/src/types.ts

add `tagLabelValidator` prop
新增 `tagLabelValidator` 支持标签的创建和修改的输入校验

fix(pro:tag-select): tag data edit and create should be validated

---

packages/components/control-trigger/docs/Api.zh.md
packages/pro/tag-select/docs/Api.zh.md

docs: update controTrigger and tagSelect docs

---

packages/components/control-trigger/docs/Api.zh.md
packages/pro/tag-select/docs/Api.zh.md
packages/pro/tag-select/src/content/TagDataEditPanel.tsx

docs: pro tag select indicator clor

---

packages/components/table/demo/EditRowValidator.vue
packages/components/table/src/composables/useSelectable.ts

当所有选项都被禁用的时候且没有被勾选时，全选的勾选框显示勾选状态
不应该显示勾选

fix(comp:table): select all check state isn't displayed correctly

---

packages/cdk/scroll/src/virtual/composables/useScrollPlacement.ts

虚拟滚动，当已经滚动到最底部的时候，横向的滚动会不断触发 scrolledBottom 事件
修复以上问题

fix(cdk:scroll): virtual horizontal scroll triggers scrolledBottom

---

packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/image/__tests__/imageViewer.spec.ts
packages/components/image/docs/Api.zh.md
packages/components/image/src/ImageViewer.tsx
packages/components/image/src/types.ts

新增 `IxImage` 的图片预览的拖拽功能
可以通过全局配置改变，默认 true

feat(comp:image): add dnd sortable support for image viewer

---

packages/components/modal/__tests__/modal.spec.ts
packages/components/modal/src/ModalWrapper.tsx
packages/components/modal/style/index.less

使用 cdk/dnd 中的 CdkDndMovable 重构拖拽功能，替换掉原来的 cdk/drag-drop

fix(comp:modal): modal draggable is now refactored with `cdk/dnd`

---

packages/cdk/dnd/src/composables/useDndSortable/useDndSortable.ts
packages/cdk/dnd/src/sortable/DndSortable.tsx
packages/cdk/dnd/src/sortable/DndSortableItem.tsx
packages/cdk/dnd/src/types/sortable.ts
packages/cdk/dnd/src/utils/callEventHandler.ts
packages/components/select/demo/DndSortable.vue
packages/components/select/src/panel/Option.tsx
packages/components/select/src/panel/Panel.tsx
packages/components/select/src/types.ts
packages/components/select/style/index.less
packages/components/tabs/src/Tabs.tsx
packages/components/tabs/src/contents/MoreSelectPane.tsx
packages/components/tabs/src/contents/TabNavWrapper.tsx
packages/components/tabs/src/types.ts
packages/components/tabs/style/index.less

refactor: update tabs and select dnd codes

---

packages/cdk/dnd/src/sortable/DndSortableItem.tsx

refactor: dnd indicator mark parent doesn't work

---

packages/cdk/dnd/src/indicator/DndBoxIndicator.tsx
packages/cdk/dnd/src/movable/DndMovableHandle.tsx
packages/cdk/dnd/src/sortable/DndSortableHandle.tsx

fix(cdk:dnd): exported components should have name

---

packages/components/transfer/src/composables/useTransferData.ts
packages/components/tree-select/demo/Virtual.vue
packages/components/tree/demo/Virtual.vue
packages/pro/transfer/src/composables/useTransferTreeProps.ts
packages/pro/transfer/src/composables/useTreeDataStrategy.ts

树穿梭框在大数据量下存在严重的卡顿现象
优化树穿梭框性能
1. 优化树穿梭框数据处理策略中的数据分割逻辑，只有在当前源数据变化的时候（比如远程的分页，搜索），才需要与缓存的选中数据进行合并处理
2. 树穿梭框，disabled函数直接取了响应式变量，会导致大量数据下频繁触发响应式变量的依赖收集逻辑，消耗大量性能
3. 基础穿梭框的数据处理逻辑中，也有同问题2的问题

fix(pro:transfer): optimize tree transfer performance

---

packages/components/table/src/composables/useSelectable.ts
packages/components/utils/src/useTreeCheckState.ts

表格，反选当前页的数据，会清除掉其他已选的数据
修复以上问题

fix(comp:table): deselecting page removes all other selections

---

packages/components/_private/footer/src/Footer.tsx
packages/components/_private/footer/src/types.ts
packages/components/config/src/defaultConfig.ts
packages/components/config/src/types.ts
packages/components/modal/demo/Loading.md
packages/components/modal/demo/Loading.vue
packages/components/modal/docs/Api.zh.md
packages/components/modal/src/Modal.tsx
packages/components/modal/src/ModalBody.tsx
packages/components/modal/src/ModalWrapper.tsx
packages/components/modal/src/token.ts
packages/components/modal/src/types.ts

modal 支持内置的 spin
1. spin 可以配置是否覆盖全部弹窗
2. spin开启时，禁用footer中的按钮

feat(comp:modal): add `spin` support for modal

---

packages/cdk/scroll/src/virtual/VirtualScroll.tsx
packages/cdk/scroll/src/virtual/composables/useScrollState.ts

当开启了模拟滚动模式和纵向虚拟滚动，没有开启横向虚拟滚动，且列表最初没有横向的滚动时，修改列表数据，使其在横向出现滚动溢出，横向虚拟滚动始终无法出现
修复以上问题

fix(cdk:scroll): simulated horizontal scrollbar is not displayed

---

packages/components/transfer/src/list/List.tsx
packages/components/transfer/style/list.less

解决由穿梭框的样式导致的虚拟滚动失效问题
@sallerli1 @coolyuantao

fix(comp:transfer): configuring virtual scrolling does not take effect

---

packages/components/textarea/src/composables/useAutoRows.ts

fix(comp:textarea): the minRows in autoRows does not work

---

packages/components/timeline/demo/Label.vue
packages/components/timeline/docs/Api.zh.md
packages/components/timeline/src/TimelineItem.tsx
packages/components/timeline/src/types.ts
packages/components/timeline/style/index.less

Some scenarios require the display of time text above the content; an API should be added to support this functionality.

feat(comp:timeline): support `labelPlacement` for timeline

---

packages/components/input-number/docs/Api.zh.md
packages/components/input-number/src/types.ts
packages/components/input-number/src/useInputNumber.ts

新增 `formatter` prop，用于将数字格式化为显示的文字

feat(comp:input-number): add `formatter` prop to format number display

---

packages/cdk/dnd/demo/Movable.vue
packages/cdk/dnd/docs/Api.zh.md
packages/cdk/dnd/src/composables/useDndMovable/useDndMovable.ts
packages/cdk/dnd/src/composables/useDndMovable/useMovablePosition.ts
packages/cdk/dnd/src/composables/useDndMovable/useResolvedOptions.ts
packages/cdk/dnd/src/movable/DndMovable.tsx
packages/cdk/dnd/src/types/comp/movable.ts
packages/cdk/dnd/src/types/movable.ts

`useDndMovable` 新增 `offset` 和 `onOffsetChange` 属性，用于受控控制移动的偏移量
`CdkDndMovable` 新增受控属性 `offset` 和 `onOffsetChange` 属性，用于受控控制移动的偏移量

feat(cdk:dnd): add support for controlled offset prop

---

scripts/gulp/build/utils.ts

fix: set the correct api.json path

---

packages/components/pagination/__tests__/pagination.spec.ts
packages/components/pagination/src/composables/useJumpTo.ts

- simple 模式下，输入一个异常的页码，没有任何反应
- 输入异常的页码，会回退到正确的页码。

fix(comp:pagination): enter an incorrect page, the display is abnormal

---

packages/pro/search/demo/DateRangeShortcut.md
packages/pro/search/demo/DateRangeShortcut.vue
packages/pro/search/src/ProSearch.tsx
packages/pro/search/src/components/quickSelect/QuickSelectItem.tsx
packages/pro/search/src/components/segment/Segment.tsx
packages/pro/search/src/composables/useResolvedSearchFields.ts
packages/pro/search/src/panel/DatePickerPanel.tsx
packages/pro/search/src/segments/CreateDateRangePickerSegment.tsx
packages/pro/search/src/types/panels.ts
packages/pro/search/src/types/searchFields.ts
packages/pro/search/src/types/segment.ts
packages/pro/search/style/panel.less

IxProSearch 组件，为 `'dateRangePicker'` 类型的field 增加 `shortcuts` 配置

feat(pro:search): add shortcut support for dateRangePicker field

---

packages/components/_private/overlay/__tests__/overlay.spec.ts
packages/components/_private/overlay/src/Content.tsx
packages/components/_private/overlay/src/Overlay.tsx
packages/components/_private/overlay/src/composables/useMergedEvents.ts
packages/components/_private/overlay/src/composables/useOverlayState.ts
packages/components/_private/overlay/src/composables/usePopperOptions.ts
packages/components/_private/overlay/src/composables/useVisible.ts
packages/components/_private/overlay/src/token.ts
packages/components/dropdown/demo/Button.vue
packages/components/popover/demo/Nested.md
packages/components/popover/demo/Nested.vue
packages/components/tooltip/__tests__/tooltip.spec.ts

浮层组件不支持嵌套
新增嵌套浮层组件的显示隐藏控制和加锁
例如：两个嵌套的trigger为 hover 的浮层，内层的浮层鼠标悬浮之后，外层的不会收起。

feat(comp:*): overlay supports nested control

---

packages/pro/search/docs/Api.zh.md
packages/pro/search/src/ProSearch.tsx
packages/pro/search/src/types/proSearch.ts

feat(pro:search): expose `clear` methods

---

packages/components/button/docs/Theme.zh.md

docs(comp:button): correct markdown syntax

---

packages/components/breadcrumb/docs/Theme.zh.md
packages/components/card/docs/Theme.zh.md
packages/components/cascader/docs/Theme.zh.md
packages/components/checkbox/docs/Theme.zh.md
packages/components/date-picker/docs/Theme.zh.md
packages/components/dropdown/docs/Theme.zh.md
packages/components/form/docs/Theme.zh.md
packages/components/image/docs/Theme.zh.md
packages/components/message/docs/Theme.zh.md
packages/components/notification/docs/Theme.zh.md
packages/components/pagination/docs/Theme.zh.md
packages/components/progress/docs/Theme.zh.md
packages/components/radio/docs/Theme.zh.md
packages/components/result/docs/Theme.zh.md
packages/components/select/docs/Theme.zh.md
packages/components/stepper/docs/Theme.zh.md
packages/components/tabs/docs/Theme.zh.md
packages/components/time-picker/docs/Theme.zh.md
packages/components/transfer/docs/Theme.zh.md
packages/components/tree-select/docs/Theme.zh.md
packages/components/tree/docs/Theme.zh.md
packages/components/upload/docs/Theme.zh.md
packages/pro/search/docs/Theme.zh.md
packages/pro/transfer/docs/Theme.zh.md
packages/site/src/docs/CustomizeTheme.zh.md
scripts/gen/theme/updateDoc.ts

docs: theme doc type intersection error
