IDuxFE/idux

- .ls-lint.yml
- docs/i18n.zh.md
- packages/components/core/logger/index.ts
- packages/components/core/utils/installComponent.ts
- packages/components/i18n/__tests__/useI18n.spec.ts
- packages/components/i18n/index.ts
- packages/components/i18n/languages/en_US.ts
- packages/components/i18n/languages/es_ES.ts
- packages/components/i18n/languages/index.ts
- packages/components/i18n/languages/zh_CN.ts
- packages/components/i18n/languages/zh_TW.ts
- packages/components/i18n/types.ts
- packages/components/i18n/useI18n.ts
- packages/components/icon/__tests__/__snapshots__/icon.spec.ts.snap
- packages/components/icon/src/utils.ts
- packages/components/index.ts
> feat(comp:i18n): support i18n

- packages/components/components.less
- packages/components/core/config/types.ts
- packages/components/core/config/useGlobalConfig.ts
- packages/components/core/types/index.ts
- packages/components/divider/__tests__/__snapshots__/divider.spec.ts.snap
- packages/components/divider/__tests__/divider.spec.ts
- packages/components/divider/demo/horizontal.md
- packages/components/divider/demo/plain.md
- packages/components/divider/demo/vertical.md
- packages/components/divider/demo/with-text.md
- packages/components/divider/docs/index.zh.md
- packages/components/divider/index.ts
- packages/components/divider/src/Divider.vue
- packages/components/divider/src/types.ts
- packages/components/divider/style/index.less
- packages/components/index.ts
- tsconfig.json
> feat(comp: divider): add divider component

- packages/cdk/utils/__tests__/vNode.spec.ts
- packages/cdk/utils/vNode.ts
- packages/components/components.less
- packages/components/core/config/defaultConfig.ts
- packages/components/core/config/types.ts
- packages/components/core/types/index.ts
- packages/components/index.ts
- packages/components/space/__tests__/__snapshots__/space.spec.ts.snap
- packages/components/space/__tests__/space.spec.ts
- packages/components/space/demo/CustomSize.vue
- packages/components/space/demo/Size.vue
- packages/components/space/demo/Wrap.vue
- packages/components/space/demo/basic.md
- packages/components/space/demo/custom-size.md
- packages/components/space/demo/direction.md
- packages/components/space/demo/size.md
- packages/components/space/demo/split.md
- packages/components/space/demo/wrap.md
- packages/components/space/docs/index.zh.md
- packages/components/space/index.ts
- packages/components/space/src/Space.vue
- packages/components/space/src/types.ts
- packages/components/space/style/index.less
- packages/components/space/style/mixins.less
- packages/components/style/default.less
> feat(comp: space): add component space

- package.json
Add `engines` to `package.json`. The minimum version of the node is `v11.5.0`
none
> fix: add engines to package.json

- .eslintrc.js
- packages/cdk/utils/vNode.ts
- packages/components/badge/src/Badge.vue
- packages/components/space/src/Space.vue
fix #122
add brace eslint rules:
`'@typescript-eslint/brace-style': ['error', '1tbs']`
`curly: ['error', 'all']`
More content can be found on  [brace-style](https://eslint.org/docs/rules/brace-style#options) and [curly](https://eslint.org/docs/rules/curly#require-following-curly-brace-conventions-curly)
Example:
```javascript
// good
function foo() {
return true;
}
if (foo) {
bar();
}
if (foo) {
bar();
} else {
baz();
}
try {
somethingRisky();
} catch(e) {
handleError();
}
if (foo) {
foo++;
}
while (bar) {
baz();
}
if (foo) {
baz();
} else {
qux();
}
```
> style(scripts): add brace style eslint rule

- packages/components/badge/__tests__/badge.spec.ts
- packages/components/icon/src/Icon.vue
> test(comp:badge,icon): fix warning

- packages/components/components.less
- packages/components/core/config/defaultConfig.ts
- packages/components/core/config/types.ts
- packages/components/icon/src/icons.ts
- packages/components/index.ts
- packages/components/result/__tests__/__snapshots__/result.spec.ts.snap
- packages/components/result/__tests__/result.spec.ts
- packages/components/result/demo/error.md
- packages/components/result/demo/info.md
- packages/components/result/demo/success.md
- packages/components/result/demo/warning.md
- packages/components/result/docs/index.zh.md
- packages/components/result/index.ts
- packages/components/result/src/Result.vue
- packages/components/result/src/types.ts
- packages/components/result/style/index.less
- packages/components/result/style/mixins.less
- packages/components/style/default.less
> feat(comp: result): add result component

- packages/cdk/forms/__tests__/abstractControl.spec.ts
- packages/cdk/forms/__tests__/formControl.spec.ts
- packages/cdk/forms/__tests__/utils.spec.ts
- packages/cdk/forms/src/controls/abstractControl.ts
- packages/cdk/forms/src/controls/formArray.ts
- packages/cdk/forms/src/controls/formControl.ts
- packages/cdk/forms/src/controls/formGroup.ts
- packages/cdk/forms/src/utils.ts
> refactor(cdk:forms): `modelRef` renamed to `valueRef`

- packages/cdk/click-outside/__tests__/clickOutside.spec.ts
- packages/cdk/click-outside/demo/Basic.vue
- packages/cdk/click-outside/demo/basic.md
- packages/cdk/click-outside/docs/index.zh.md
- packages/cdk/click-outside/index.ts
- packages/cdk/click-outside/src/useClickOutside.ts
- packages/cdk/overlay/__tests__/overlay.spec.ts
- packages/cdk/overlay/demo/Basic.vue
- packages/cdk/overlay/demo/Portal.vue
- packages/cdk/overlay/docs/index.zh.md
- packages/cdk/overlay/src/useOverlay.ts
- packages/cdk/utils/dom.ts
> feat(cdk: click-outside): add click-outside

- packages/cdk/overlay/demo/Portal.vue
- packages/cdk/overlay/src/types.ts
- packages/cdk/overlay/src/useModifiers.ts
- packages/cdk/overlay/src/useOverlay.ts
- packages/cdk/overlay/src/usePopperOptions.ts
- packages/cdk/portal/src/useContainer.ts
> refactor(cdk:overlay): update types

- packages/cdk/click-outside/src/useClickOutside.ts
Fix overlay class components that use portal with `load` prop.
When `load = false` that directive `click-outside`'s exclude is recived null that throw erros.
> fix(cdk: click-outside): compatible with null exclude elements

- scripts/gen/generate.ts
- scripts/gen/template.ts
通过npm run gen 创建一个组件 xxx , npm run start 运行页面，发现无法进去新创建的组件demo展示页面
可以正常进去新组件demo页面
> fix: 通过npm run gen创建组件缺少style的入口文件

- packages/cdk/a11y/demo/FocusMonitor.md
- packages/cdk/a11y/demo/FocusMonitor.vue
- packages/cdk/a11y/docs/Index.zh.md
- packages/cdk/a11y/index.ts
- packages/cdk/a11y/src/fakeEventDetection.ts
- packages/cdk/a11y/src/focusMonitor.ts
- packages/cdk/a11y/src/inputModalityDetector.ts
- packages/cdk/platform/src/features/passiveListeners.ts
- packages/cdk/platform/src/features/shadowDom.ts
- packages/cdk/popper/src/hooks.ts
- packages/cdk/scroll/src/virtual/VirtualHolder.tsx
- packages/cdk/scroll/src/virtual/VirtualScroll.tsx
- packages/cdk/scroll/src/virtual/composables/useEvents.ts
- packages/cdk/scroll/src/virtual/types.ts
- packages/cdk/utils/index.ts
- packages/cdk/utils/src/composable.ts
- packages/cdk/utils/src/convert.ts
- packages/cdk/utils/src/vNode.ts
- packages/components/message/src/Message.tsx
- typings/global.d.ts
> feat(cdk:a11y): add focus monitor

- packages/components/input/docs/Index.zh.md
- packages/components/textarea/docs/Index.zh.md
fix #518
Fix typos in the IxInput and the IxTextare documentation
> docs(comp: input,textarea): fix typos in documentation

- packages/components/radio/style/index.less
style(comp:radio): modify the radio button's checked style to the radio group (#501)
buttonGroup不能直接在已有类上修改样式，那样会导致微元素颜色和原border重叠导致色差。
所以只修改了radioGroup下的样式问题，且发现一个ix-radio-group-no-gap的类，不知道是否是多余的，全局没有搜到相关用到的地方。
buttonGroup可以在button外部再套一层label然后将样式转移至外层上，可解决。但那样修改相关的地方有点多，就并没有做修改。
> style(comp:radio): modify the radio button's checked style to the radio group (#501)

- packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap
- packages/components/tree/__tests__/tree.spec.ts
- packages/components/tree/demo/Virtual.vue
- packages/components/tree/src/Tree.tsx
- packages/components/tree/src/composables/useExpandable.ts
- packages/components/tree/src/composables/useSearchable.ts
由于defaultExpandAll 没有抛出expandedChange事件，导致在受控模式下无效
```
<IxTree
:expandedKeys="expandedKeys"
:dataSource="treeData"
defaultExpandAll
@expandedChange="onExpandedChange"
>
</IxTree>
...
const expandedKeys = ref([])
const onExpandedChange = (keys: VKey[], nodes: TreeNode[]) => {
console.log('onExpandedChange', keys, nodes)
expandedKeys.value = keys
}
```
1. 同样的问题存在于受控模式下，进行搜索时也没有抛出onExpandedChange 事件 ，一并修复
2. 为了增加用户体验，优化了一下搜索和展开之间的联动，当搜索值为空字符串时（对应用户操作为删除搜索框的输入值），树会默认展开上一次有效搜索时的展开效果
> fix(comp:tree): defaultExpandAll is invalid in controlled mode

- packages/components/menu/__tests__/menu.spec.ts
- packages/components/menu/src/children/menu-sub/MenuSub.tsx
fix #636
https://github.com/IDuxFE/idux/issues/636
When vertical and horizontal, the initial setting expandedKeys does not expand IxMenuSub
> fix(comp:ixmenu): fix error when initialize settings expandKeys

- packages/components/drawer/__tests__/drawer.spec.ts
- packages/components/drawer/docs/Index.zh.md
- packages/components/drawer/src/Drawer.tsx
- packages/components/drawer/src/types.ts
- packages/components/modal/__tests__/modal.spec.ts
- packages/components/modal/docs/Index.zh.md
- packages/components/modal/src/Modal.tsx
- packages/components/modal/src/types.ts
BREAKING CHANGE: onBeforeClose is used instead of onClose
fix #645
> feat(comp:drawer,modal): add onBeforeClose event

- packages/components/select/__tests__/select.spec.ts
- packages/components/select/src/trigger/Input.tsx
- packages/components/select/src/trigger/Item.tsx
- packages/components/select/src/trigger/Selector.tsx
- packages/components/select/src/trigger/Trigger.tsx
- packages/components/tree-select/__tests__/treeSelect.spec.ts
- packages/components/tree-select/src/trigger/Input.tsx
- packages/components/tree-select/src/trigger/Item.tsx
- packages/components/tree-select/src/trigger/Selector.tsx
- packages/components/tree-select/src/trigger/Trigger.tsx
readonly 考虑场景不足
```
<IxSelect v-model:value="value" :options="options" multiple readonly clearable></IxSelect>
```
readonly状态下还能对数据进行删除，没有对`multiple ` 和 `clearable` 场景进行处理
同理tree-select也有此问题，一并修改
> fix(comp: select): incomplete readonly scenario

- packages/pro/index.ts
- packages/pro/layout/demo/Collapsed.md
- packages/pro/layout/demo/Collapsed.vue
- packages/pro/layout/style/sider.less
- packages/pro/layout/style/themes/default.less
- packages/pro/layout/style/themes/default.variable.less
- scripts/gen/generate.ts
- scripts/gen/template.ts
docs(pro:layout): add collapsed demo
> fix(pro:layout): fix sider border-right style

- packages/cdk/scroll/src/strategy/blockScrollStrategy.ts
- packages/components/style/core/default.less
> fix(cdk:scroll): update scroll blocked style

- packages/components/input-number/demo/Precision.vue
- packages/components/input-number/src/useInputNumber.ts
> fix(comp:input-number): decimal precision calculation error

- packages/components/checkbox/style/index.less
- packages/components/radio/style/index.less
- packages/components/select/demo/OverlayRender.vue
- packages/components/select/style/index.less
- packages/components/select/style/mixin.less
- packages/components/select/style/themes/default.variable.less
> fix(comp:select): fix option style

- packages/components/table/docs/Index.zh.md
- packages/components/table/src/token.ts
BREAKING CHANGE: `options` in `TableColumnSelectable` was deprecated, please use `menus` instead
> feat(comp:table): use `menus` instead of `options`

- packages/components/_private/footer/__tests__/footer.spec.ts
- packages/components/_private/footer/src/Footer.tsx
- packages/components/empty/style/index.less
- packages/components/empty/style/themes/default.variable.less
- packages/components/i18n/src/locales/zh-CN.ts
- packages/components/modal/src/ModalWrapper.tsx
- packages/components/modal/style/index.less
- packages/components/modal/style/themes/default.variable.less
add title and content color variables
feat(comp:empty): add color variables
BREAKING CHANGE: replaced empty-color variable with more specific ones
modal组件缺少title与content的具体颜色变量
modal组件在icon存在的前提下右侧的cotent缺少右边距
empty组件缺少具体的颜色变量
增加 modal组件的 title color 和 content color的变量
增加modal右侧content的右边距，与icon的左边距一致
empty将empty-color替换成3个具体的颜色变量
> feat(comp:modal): add padding to padding next icon

- packages/cdk/forms/__tests__/formControl.spec.ts
- packages/cdk/forms/docs/Index.zh.md
- packages/cdk/forms/src/controls.ts
- packages/cdk/forms/src/types.ts
Control 不支持配置去除首尾的空字符串
1. `ValidatorOptions` 增加多一个 `trim` 的配置控制是否去除首尾字符串
2. 默认配置不去除首尾字符串
> feat(cdk:forms): add option to remove space (#553)

- packages/components/tree/demo/Virtual.vue
- packages/components/tree/src/Tree.tsx
- packages/components/tree/src/composables/useDataSource.ts
- packages/components/tree/src/node/Checkbox.tsx
- packages/components/tree/src/node/TreeNode.tsx
- packages/components/tree/src/types.ts
测试：当拥有一万个数据节点，展开所有节点的情况下，哪怕开启了虚拟滚动，也会很卡，如tree的虚拟滚动Demo所示
优化项：
- 使用非递归的方式勾选所有的树的flattedNode数据结构，降低空间复杂度
- 使用Map寻找expandedNode的方式代替使用includes，降低时间复杂度
- 每次构造的数据沿时用mergeNode，而不是{...mergeNode}，使得Tree在展开节点重新渲染时只渲染新展开更新的节点，不会所有节点都更新
测试结果： 10万条数据在相同条件下，渲染速度由10S减少到1S
TODO： 二次构造数据时不用再重新循环所有数据构造flattedNode节点，即diff patch代替全量patch
> refactor(comp: tree): optimize rendering speed for big data

- packages/components/select/demo/CustomLabel.vue
- packages/components/select/demo/Searchable.vue
- packages/components/select/docs/Index.zh.md
- packages/components/select/src/content/Content.tsx
- packages/components/select/src/content/ListBox.tsx
- packages/components/select/src/content/Option.tsx
- packages/components/select/src/trigger/Input.tsx
- packages/components/select/src/trigger/Selector.tsx
- packages/components/select/src/trigger/Trigger.tsx
- packages/components/select/src/types.ts
- packages/components/select/src/utils/renderOptionLabel.ts
- packages/components/select/style/index.less
- packages/components/select/style/themes/default.variable.less
input is now rendered within overlay when searchable is 'overlay'
fix(comp:selectable): fix selected options render when using IxSelectOption
1. searchable 不支持 ’overlay‘
2. 使用 IxSelectOption渲染的option在选中时不显示
1. searchable支持 'overlay', 与 tree-select 保持一致
2. 使用 IxSelectOption渲染的option在选中时可以正常显示
抽离label渲染的工具函数 renderOptionLabel
> feat(comp:select): add 'overlay' to searchable

- packages/components/affix/src/Affix.tsx
1. 当isStickyRef.value为false时，没有清除为true时动态赋值的style
2. 当内容区宽高自适应，且target触发resize时，没有重新计算内容区的宽高，导致布局出现问题
> fix(comp: affix): style is not recalculated when resizing

- packages/components/radio/demo/Group.vue
- packages/components/radio/src/Radio.tsx
```
<template>
<IxRadio :checked="checked" @change="change">Checked: {{ checked }}</IxRadio>
</template>
const checked = ref(false)
const change = console.log
</script>
```
在受控模式下，当radio点击一次后，change事件不再触发；
原因：原生radio不是受控组件，所以当你点击一次之后，原生的input其实已经被选中，再次点击不会被触发
组件支持完全受控，当radio没有被选中时，change事件可以一直触发
> fix(comp: radio): incomplete consideration of controlled mode

- packages/components/radio/docs/Index.zh.md
- packages/components/select/__tests__/select.spec.ts
- packages/components/select/demo/AllowInput.vue
- packages/components/select/demo/Basic.vue
- packages/components/select/demo/Borderless.vue
- packages/components/select/demo/CompareWith.vue
- packages/components/select/demo/CustomLabel.vue
- packages/components/select/demo/Group.vue
- packages/components/select/demo/Key.vue
- packages/components/select/demo/Multiple.vue
- packages/components/select/demo/OverlayRender.vue
- packages/components/select/demo/Searchable.vue
- packages/components/select/demo/Server.vue
- packages/components/select/demo/Size.vue
- packages/components/select/demo/Virtual.vue
- packages/components/select/docs/Index.zh.md
- packages/components/select/src/composables/useActiveState.ts
- packages/components/select/src/composables/useOptions.ts
- packages/components/select/src/composables/useSelectedState.ts
- packages/components/select/src/content/ListBox.tsx
- packages/components/select/src/content/Option.tsx
- packages/components/select/src/trigger/Trigger.tsx
- packages/components/select/src/types.ts
- packages/site/src/styles/components.less
BREAKING CHANGE: `compareWith` was deprecated, please use `compareFn` instead, `options` was deprecated, please use `dataSource` instead, `searchFilter` was deprecated, please use `searchFn` instead.
> refactor(comp:select): api redesign

- packages/components/select/docs/Index.zh.md
- packages/components/style/mixins/reset.less
- packages/components/tabs/style/index.less
- packages/components/tabs/style/themes/default.variable.less
> feat(comp:tabs): add less variable

- packages/components/select/demo/Size.vue
- packages/components/select/index.ts
- packages/components/select/src/types.ts
- packages/components/table/__tests__/table.spec.ts
- packages/components/table/docs/Index.zh.md
- packages/components/table/src/composables/useColumns.ts
- packages/components/table/src/main/StickyScroll.tsx
- packages/components/table/src/main/body/BodyCell.tsx
- packages/components/table/src/main/head/HeadCell.tsx
- packages/components/table/src/types.ts
- packages/components/table/src/utils/index.ts
- packages/components/table/style/index.less
- packages/components/table/style/themes/default.variable.less
> feat(comp:table): add ellipsis and less variable

- packages/components/spin/docs/Index.zh.md
- packages/components/table/docs/Index.zh.md
- packages/components/tabs/docs/Index.zh.md
- scripts/gen/style-variable/update.ts
组件文档中如果less变量部分下方还有其他章节，如`components/form/docs/index.zh.md `会导致脚本执行卡死
即使有其他章节也能正常生成插入less变量
> refactor(scripts): fix script about update less variable

- packages/components/stepper/__tests__/steps.spec.ts
- packages/components/stepper/docs/Index.zh.md
- packages/components/stepper/src/Stepper.tsx
- packages/components/stepper/style/index.less
- packages/components/stepper/style/labelPlacement.less
- packages/components/stepper/style/mixin.less
- packages/components/stepper/style/size.less
- packages/components/stepper/style/themes/default.variable.less
- packages/components/tabs/docs/Index.zh.md
```
<template>
<IxStepper :activeKey="2" vertical>
<IxStepperItem status="finish" title="Finished" ></IxStepperItem>
<IxStepperItem title="In Progress"></IxStepperItem>
<IxStepperItem title="Waiting"></IxStepperItem>
</IxStepper>
</template>
```
1. 同时修复stepper组件全局的size配置对于内部的progress组件不生效
2. 丰富测试案例
> fix(comp: stepper): vertical style error without description

- packages/components/button/__tests__/buttonGroup.spec.ts
- packages/components/button/docs/Index.zh.md
- packages/components/button/src/Button.tsx
- packages/components/button/src/types.ts
- packages/components/button/style/index.less
- packages/components/button/style/mixin.less
- packages/components/button/style/themes/default.variable.less
- packages/components/config/src/defaultConfig.ts
- packages/components/config/src/types.ts
- packages/components/pagination/docs/Index.zh.md
- packages/components/pagination/style/themes/default.variable.less
- packages/components/style/variable/index.less
- packages/components/style/variable/width.less
The default size is changed to 'sm'
> feat(comp: button): add xs and lg sizes

- packages/components/_private/input/__tests__/input.spec.ts
- packages/components/_private/input/src/Input.tsx
- packages/components/config/src/defaultConfig.ts
- packages/components/config/src/types.ts
- packages/components/date-picker/docs/Index.zh.md
- packages/components/input/docs/Index.zh.md
- packages/components/select/__tests__/select.spec.ts
- packages/components/select/docs/Index.zh.md
- packages/components/select/src/trigger/Selector.tsx
- packages/components/select/src/types.ts
- packages/components/textarea/docs/Index.zh.md
- packages/components/textarea/src/Textarea.tsx
- packages/components/time-picker/src/trigger/BaseTrigger.tsx
> feat(comp:select): add clearIcon

- packages/components/config/src/defaultConfig.ts
- packages/components/config/src/types.ts
- packages/components/table/__tests__/table.spec.ts
- packages/components/table/demo/AutoHeight.md
- packages/components/table/demo/AutoHeight.vue
- packages/components/table/docs/Index.zh.md
- packages/components/table/src/Table.tsx
- packages/components/table/src/composables/useScroll.ts
- packages/components/table/src/main/FixedHolder.tsx
- packages/components/table/src/types.ts
- packages/components/table/style/index.less
- packages/components/table/style/themes/default.variable.less
> feat(comp:table): support autoHeight

- packages/components/timeline/__tests__/__snapshots__/timeline.spec.ts.snap
- packages/components/timeline/__tests__/timeline.spec.ts
- packages/components/timeline/demo/Label.vue
- packages/components/timeline/demo/Pending.vue
- packages/components/timeline/demo/PendingDot.vue
- packages/components/timeline/demo/Placement.vue
- packages/components/timeline/demo/Reverse.vue
- packages/components/timeline/docs/Index.zh.md
- packages/components/timeline/src/Timeline.tsx
- packages/components/timeline/src/TimelineItem.tsx
- packages/components/timeline/src/token.ts
- packages/components/timeline/style/index.less
- packages/components/timeline/style/mixin.less
- packages/components/timeline/style/themes/default.variable.less
- packages/components/transfer/docs/Index.zh.md
之前样式不具备扩展性
1. 样式整体全部优化，可以通过修改仅时间轴的点的大小，完全整体视觉修改
2. 通过nth-last-child来优化幽灵节点样式的实现，避免借助js实现
3. 通过background-size实现虚线来代替border，使得虚线视觉可以自己调整
> refactor(comp: timeline): optimize code and style

- packages/components/_private/time-panel/src/composables/useOptions.ts
- packages/components/_private/time-panel/src/utils.ts
- packages/components/_private/time-panel/style/index.less
- packages/components/_private/time-panel/style/themes/default.variable.less
- packages/components/time-picker/src/composables/useProps.ts
- packages/components/time-picker/src/overlay/RangeOverlay.tsx
- packages/components/time-picker/style/index.less
- packages/components/time-picker/style/range.less
- packages/components/time-picker/style/themes/default.variable.less
fix input size within overlay to 'sm'
remove padding of time-panel column
fix(comp:time-picker): fix get hour value when 'pm' is sepcified
1. 在'pm'下时间选择的hour取值不正确
2. 时间选择面板column的分布不美观
3. 时间选择面板的纵向横向padding不支持分开配置
> refactor(comp:time-picker): refactor style

- packages/components/checkbox/__tests__/checkboxGroup.spec.ts
- packages/components/checkbox/src/Checkbox.tsx
- packages/components/radio/__tests__/radioGroup.spec.ts
- packages/components/radio/src/Radio.tsx
```
<template>
<IxCheckboxGroup v-model:value="value" :dataSource="dataSource" buttoned  />
</template>
const value = ref(['beijing'])
const dataSource = [
{ label: 'Beijing', value: 'beijing', disabled: true },
{ label: 'Shanghai', value: 'shanghai' },
{ label: 'Guangzhou', value: 'guangzhou' },
{ label: 'Shenzhen', value: 'shenzhen' },
]
</script>
```
`disabled` 无效
> fix(comp: checkbox-group): invalid disabled in dataSource

- packages/components/anchor/__tests__/anchor.spec.ts
- packages/components/anchor/src/Anchor.tsx
- remove default link
- use first item as reduce start, ensure default first item active works
close #774
> fix(comp:anchor): should default active first item

- packages/components/table/src/main/MainTable.tsx
- packages/components/table/src/main/body/Body.tsx
1. 虚拟滚动场景下，延迟加载数据之后列宽计算不准确，整体表格宽度比预期多出一个滚动条宽度
2. 在提供高度时默认 overflow-y: scroll
1. 在有数据时再渲染measureRow，使得远程数据加载场景下的列宽计算没有问题
2. 修改overflow-y为auto
> fix(comp:table): fix table column width measure problem when data load is delayed

- packages/components/carousel/docs/Index.zh.md
- packages/components/carousel/src/composables/useWalk.ts
FIX #862 
onChange入参顺序是prevIndex，nextIndex
onChange入参顺序是nextIndex，prevIndex
> fix(comp:carousel): modify onChange params order

- packages/components/config/src/defaultConfig.ts
- packages/components/tree-select/docs/Index.zh.md
- packages/components/tree/style/index.less
BREAKING CHANGE:
- treeSelect overlayMatchWidth prop is changed to `true` by default
当内容过多时，未出现横向滚动条
修复样式，并且需要给tree的height赋值，才能开启cdkScroll的overflow:auto样式
> fix(comp: tree): the horizontal scroll bar does not appear

- packages/components/config/src/defaultConfig.ts
- packages/components/config/src/types.ts
- packages/components/dropdown/docs/Index.zh.md
- packages/components/dropdown/src/Dropdown.tsx
- packages/components/dropdown/src/types.ts
- packages/components/menu/__tests__/__snapshots__/menu.spec.ts.snap
- packages/components/menu/docs/Index.zh.md
- packages/components/menu/index.ts
- packages/components/menu/src/Menu.tsx
- packages/components/menu/src/contents/MenuDivider.tsx
- packages/components/menu/src/contents/MenuItem.tsx
- packages/components/menu/src/contents/MenuItemGroup.tsx
- packages/components/menu/src/contents/Utils.tsx
- packages/components/menu/src/contents/menu-sub/InlineContent.tsx
- packages/components/menu/src/contents/menu-sub/MenuSub.tsx
- packages/components/menu/src/token.ts
- packages/components/menu/src/types.ts
- packages/components/select/docs/Index.zh.md
- packages/pro/layout/__tests__/__snapshots__/layoutPro.spec.ts.snap
- packages/pro/layout/docs/Index.zh.md
- packages/pro/layout/src/contents/Header.tsx
- packages/pro/layout/src/contents/Sider.tsx
- packages/pro/layout/src/types.ts
BREAKING CHANGE: `dataSource.additional` was deprecated, please use `customAdditional` instead. `target` was deprecated, please use `overlayContainer` instead.
> feat(comp: menu): add customAdditional, getKey and overlayContainer

- packages/cdk/click-outside/src/useClickOutside.ts
click outside not working when click target has @click.stop
works fine even if there is @click.stop
-
> fix(cdk:click-outside):  not working when click target has @click.stop

- packages/components/tag/__tests__/tag.spec.ts
- packages/components/tag/src/Tag.tsx
This problem has not been fixed for a long time, so I raised a PR
fix #841
> fix(comp: tag): if value of number over 9 and show '9+'

- packages/components/icon/demo/All.vue
- packages/components/stepper/style/size.less
- packages/components/textarea/style/index.less
- packages/site/src/App.vue
style(comp:stepper): fix text vertical centered
style(comp:icon): set margin top to create a gap
style(pkg:site): make the menu width responsive
style(comp: textarea): update ix-textarea-suffix style
> update components style

- packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
- packages/components/table/demo/Bordered.md
- packages/components/table/demo/Bordered.vue
- packages/components/table/demo/ColSpanRowSpan.md
- packages/components/table/demo/CustomAdditional.md
- packages/components/table/demo/HeadGroup.vue
- packages/components/table/demo/Sticky.md
- packages/components/table/demo/Sticky.vue
- packages/components/table/demo/TreeTable.md
- packages/components/table/src/Table.tsx
- packages/components/table/src/main/FixedHolder.tsx
- packages/components/table/src/main/MainTable.tsx
- packages/components/table/style/border.less
- packages/components/table/style/size.less
- packages/site/src/styles/app.less
- 修复了开启 sticky 不生效的样式问题
- 修复了 `boderless=false` 时，表头分组的样式问题
> fix(comp: table): update style with sticky and bodered

- packages/components/select/src/types.ts
- packages/pro/tree/src/types.ts
> fix(comp: select): Add number to the type of label

- packages/components/tree-select/__tests__/treeSelect.spec.ts
- packages/components/tree-select/docs/Index.zh.md
- packages/components/tree-select/src/TreeSelect.tsx
- packages/components/tree-select/src/types.ts
- packages/components/tree/__tests__/tree.spec.ts
- packages/components/tree/docs/Index.en.md
- packages/components/tree/docs/Index.zh.md
- packages/components/tree/src/Tree.tsx
- packages/components/tree/src/types.ts
- packages/pro/tree/__tests__/proTree.spec.ts
- packages/pro/tree/docs/Index.zh.md
- packages/pro/tree/src/ProTree.tsx
- packages/pro/tree/src/types.ts
> feat(comp: tree,tree-select,pro-tree): add getNode method (#910)

- .eslintrc.js
- package.json
- packages/cdk/index.ts
- packages/components/card/style/index.ts
- packages/components/date-picker/style/themes/default.ts
- packages/components/index.ts
- packages/components/transfer/style/themes/default.ts
- packages/components/transfer/style/themes/seer.ts
- packages/components/upload/style/index.ts
- packages/pro/index.ts
- packages/pro/tree/style/themes/default.ts
- packages/pro/tree/style/themes/seer.ts
- packages/site/vite.config.ts
fix unresolved imports
eslint规则缺少Import检测，项目中存在部分不正确的import路径
新增eslint-plugin-import相关配置
> fix(comp:all,pro:all,cdk:all): add eslint import check

- .stylelintrc
- packages/components/table/demo/HeadGroup.vue
- packages/components/table/demo/Server.vue
- packages/components/table/index.ts
- packages/components/table/src/column.ts
- packages/components/table/src/composables/useColumns.ts
- packages/components/table/src/types.ts
- packages/components/table/src/utils/index.ts
- packages/components/time-picker/index.ts
- packages/components/tree/demo/DragDrop.md
- packages/components/tree/src/composables/useDragDrop.ts
- packages/components/tree/src/composables/useExpandable.ts
- packages/components/tree/src/composables/useSelectable.ts
- packages/components/types.d.ts
拖拽节点到一个为展开父级节点时，悬浮1秒后，没有正常展开
正常展开
> fix(comp: tree): expand the node being hover, when dragging

- packages/components/_private/selector/style/single.less
- packages/components/pagination/demo/Controlled.vue
- packages/components/pagination/style/index.less
- packages/components/select/style/index.less
分页组件的pageSizes下拉框宽度有问题，同时select组件option中宣示英文不全
> fix(comp: pagination): pageSizes input width error

- packages/components/header/__tests__/header.spec.ts
- packages/components/utils/src/convertVNode.ts
If prefix or suffix is empty string, still render corresponding vnode with empty content.
If prefix or suffix is empty string, expect no render corresponding vnode
> fix(comp:header): prefix or suffix is empty str, expect no render vnode

- packages/components/modal/src/Modal.tsx
确认按钮事件回调是一个 Promise,点击确认按钮后,按钮结束按钮加载状态再隐藏Modal, 在隐藏之前用户双击可能又触发了确认按钮的事件
先隐藏 Modal 再将结束按钮加载状态 或者等 Modal 隐藏的动画结束后再结束按钮加载状态
> fix(comp:modal): fix loading stop before hide

- packages/components/tabs/__tests__/tabs.spec.ts
- packages/components/tabs/docs/Index.zh.md
- packages/components/tabs/src/Tabs.tsx
- packages/components/tabs/src/tokens.ts
- packages/components/tabs/src/types.ts
| `onBeforeLeave` | 切换标签之前的钩子函数，返回 `false` 或 promise resolve `false` 或 promise reject 会阻止切换 | `(key: VKey, oldKey?: VKey) => boolean \| Promise<boolean>`| - | - | - |
> feat(comp:tabs): add onBeforeLeave prop

- packages/components/_private/footer/index.ts
- packages/components/_private/footer/src/types.ts
- packages/components/_private/header/__tests__/__snapshots__/header.spec.ts.snap
- packages/components/_private/header/src/Header.tsx
- packages/components/_private/header/src/types.ts
- packages/components/card/src/Card.tsx
- packages/components/date-picker/src/types.ts
- packages/components/drawer/src/DrawerWrapper.tsx
- packages/components/header/src/types.ts
- packages/components/modal/src/ModalWrapper.tsx
- packages/components/popover/src/Popover.tsx
- packages/components/table/__tests__/table.spec.ts
- packages/components/time-picker/src/types.ts
`header` 使用对象的方式去配置时尺寸大小变成 `sm`
默认的 header 的 size 为 `md`
> fix(comp:modal): the default header size should be 'md'

- packages/components/checkbox/docs/Index.zh.md
- packages/components/checkbox/src/CheckboxGroup.tsx
- packages/components/checkbox/src/types.ts
- packages/components/radio/demo/VerticalGroup.vue
- packages/components/radio/docs/Index.zh.md
- packages/components/radio/src/RadioGroup.tsx
- packages/components/radio/src/types.ts
refactor(comp:radio,checkbox): props replace to vue proptype
| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `vertical` | 设置组内排列方向 | `boolean` | - | - | 默认为水平排列方向，可设`true`为垂直排列 |
> feat(comp:checkbox,comp:radio): add group vertical props

- packages/components/modal/style/index.less
- packages/components/tree/src/composables/useCheckable.ts
- packages/components/tree/src/utils/index.ts
级联时，子选项选中，其父节点（key为0）无法被选中
```
<template>
<IxTree
v-model:checkedKeys="checkedKeys"
v-model:expandedKeys="expandedKeys"
v-model:selectedKeys="selectedKeys"
cascade
checkable
checkStrategy="parent"
:dataSource="treeData"
@check="onCheck"
@expand="onExpand"
@select="onSelect"
>
</IxTree>
</template>
import type { TreeNode } from '@idux/components/tree'
const treeData: TreeNode[] = [
{
label: 'Node 0',
key: 0,
children: [
{
label: 'Node 0-0',
key: '0-0',
children: [
{
label: 'Node 0-0-0',
key: '0-0-0',
},
{
label: 'Node 0-0-1',
key: '0-0-1',
},
],
},
{
label: 'Node 0-1',
key: '0-1',
children: [
{
label: 'Node 0-1-0',
key: '0-1-0',
},
{
label: 'Node 0-1-1',
key: '0-1-1',
},
],
},
], …
```
> fix(comp:tree): node cannot be checked when its key is 0(Number type)

- packages/components/carousel/src/Carousel.tsx
子元素的 `transitionend` 事件会影响到 `carousel` 的定位
> fix(comp:carousel): stop onTransitionend from bubbling

- packages/components/grid/docs/Index.zh.md
- packages/components/list/docs/Index.zh.md
- packages/components/list/src/types.ts
- ListGridProps 原来覆盖了 RowProps 的 gutter，导致只能写数字
- ColProps 复制过来没有进行同步
- ListGridProps 删除自定义的 gutter，改用继承的属于，同时修改List gutter API文档与 RowProps 保持一致 
- ColProps types也进行了同步
> fix(comp:list): remove the gutter of ListGridProps and extends RowProps

- packages/components/input-number/__tests__/__snapshots__/inputNumber.spec.ts.snap
- packages/components/input-number/demo/Basic.vue
- packages/components/input-number/src/InputNumber.tsx
- packages/components/input-number/src/useInputNumber.ts
- packages/components/input-number/style/index.less
原来左右加减，最小最大值时没有禁用，加减后失去了焦点，双击存在选中其他部分的内容
交互现在调整为右侧上下加减，最小最大值时有禁用提示，加减时自动获取焦点，双击取消文字选中
> feat(comp:input-number): replace old control (#970)

- packages/components/date-picker/demo/OverlayRender.md
- packages/components/date-picker/demo/OverlayRender.vue
- packages/components/date-picker/index.ts
- packages/components/date-picker/src/composables/useActiveValue.ts
- packages/components/date-picker/src/composables/usePickerState.ts
1. 切换日期选择器类型后，起止的面板activeValue出现异常（应该左边的面板比右边的面板小一个单位）
2. 缺少overlayRender示例
1. 修改以上问题
2. 补充demo
> fix(comp:date-picker): fix panel view display error when type changes

- packages/components/card/demo/Basic.vue
- packages/components/card/demo/Loading.vue
- packages/components/card/demo/Selectable.vue
- packages/components/card/src/Card.tsx
dev 模式下，手动修改Card组件中默认插槽中的字符串，页面不更新
```
<IxCard >
<p>Card content</p>
</IxCard>
```
热更新正常
下面通过这个例子具体解释一下实验发现
```
<IxCard >
<p>静态文本</p>
<p>{{text}}</p>
</IxCard>
const text = ref('动态文本')
```
操作1：手动修改静态文本，发现页面文本不更新
操作2：手动修改动态文本，发现页面文本更新
首先结论，slots本身不为响应式数据，所以无法这样使用
```
const children = computed(() => slots.default?.() || [])
```
热更新时即Card重新render时，无法触发computed的effect函数，所以children无法重新执行slots.default去获取最新的vnodes
此时computed的dirty为false，表示没有检测到数据被修改，还是用上一次缓存的值`this._value`
但是为什么操作2可以成功呢？
以下为猜测：
此图为模板编译后的render函数，vue3对于静态节点，在diff的时候不会比较更新，会直接拿初始化时的节点，而动态节点每次则会比较更新； 所以在生成Card组件children的vnode的时候，静态节点并没有被更新，只有动态节点被更新了，加上`this._value`返回的又是数组对象，由于首次执行时的数据引用关系，虽然没有执行effect函数，主动获取最新的slots.default，但是内部已经被更新，所以页面更新成功。
> fix(comp:card): hoisted vnode cannot be hot updated in dev mode

- packages/components/textarea/__tests__/textarea.spec.ts
- packages/components/textarea/src/Textarea.tsx
```
<ix-textarea
@blur="onBlur"
@focus="onFocus"
/>
```
手动触发blur和focus，回调函数会执行两次
> fix(comp:textarea): @focus and @blur will be triggered twice

- packages/components/transfer/demo/CustomHeaderFooter.vue
- packages/components/transfer/demo/CustomLabel.vue
- packages/components/transfer/docs/Index.zh.md
- packages/components/transfer/src/list/TransferListBody.tsx
- packages/components/transfer/src/types.ts
- packages/pro/transfer/demo/TableCustomLabel.md
- packages/pro/transfer/demo/TableCustomLabel.vue
- packages/pro/transfer/demo/TreeCustomLabel.md
- packages/pro/transfer/demo/TreeCustomLabel.vue
- packages/pro/transfer/docs/Index.zh.md
- packages/pro/transfer/src/content/ProTransferList.tsx
- packages/pro/transfer/src/content/ProTransferTable.tsx
- packages/pro/transfer/src/content/ProTransferTree.tsx
BREAKING CHANGE: label slot params change to { item, isSource }
穿梭框label插槽无法支持已选框和待选框分开渲染
label插槽的参数改成{ item, isSource }, 支持判断已选框和待选框
补充高级穿梭框自定义label的demo
> feat(comp:transfer): label slot renders source and target seperately

- packages/cdk/forms/__tests__/formArray.spec.ts
- packages/cdk/forms/__tests__/formGroup.spec.ts
- packages/cdk/forms/__tests__/useForms.spec.ts
- packages/cdk/forms/demo/Basic.vue
- packages/cdk/forms/docs/Index.zh.md
- packages/cdk/forms/docs/Overview.zh.md
- packages/cdk/forms/src/controls.ts
- packages/cdk/forms/src/types.ts
- packages/cdk/forms/src/useForms.ts
- packages/components/form/__tests__/form.spec.ts
- packages/components/form/demo/Basic.vue
- packages/components/form/demo/Coordinated.vue
- packages/components/form/demo/CustomizedValidation.vue
- packages/components/form/demo/DynamicItem.vue
- packages/components/form/demo/Layout.vue
- packages/components/form/demo/Message.vue
- packages/components/form/demo/Nest.vue
- packages/components/form/demo/Register.vue
- packages/components/form/demo/Search.vue
- packages/components/form/docs/Index.zh.md
- packages/components/form/src/FormItem.tsx
- packages/components/form/src/composables/useFormItem.ts
- packages/components/form/src/types.ts
- packages/components/form/style/index.less
```ts
const nameGroup = useFormGroup({
firstName: ['', required],
lastName: ['', required],
})
const addressGroup = useFormGroup({
city: ['', required],
street: ['', required],
zip: [''],
})
// 不支持直接嵌套 object
const formGroup = useFormGroup({
name: nameGroup,
address: addressGroup,
})
// 需要手动声明 string[]
const formArray = useFormArray<string[]>([['', required]])
```
```ts
// 直接嵌套使用
const formGroup = useFormGroup({
name: {
firstName: ['', required],
lastName: ['', required],
},
address: {
city: ['', required],
street: ['', required],
zip: [''],
},
})
// 只需要声明 string 
const formArray1 = useFormArray<string>([['', required]])
// 或者利用反向推导，直接得到对应类型
const formArray2 = useFormArray([['', required]])
```
> feat(cdk:forms): useFormGroup support nested objects

- packages/components/form/style/index.less
- packages/components/slider/style/index.less
The default form controls are all 32 px, and the switch is 28, so swtich is not vertically centered, and so are checkbox, radio, rate, and slider
the slider lose it width
add flex: 1; to solve
> fix(comp:form): repair the form-item-input-content centering（#1019）

- packages/pro/tree/__tests__/proTree.spec.ts
- packages/pro/tree/demo/Basic.vue
- packages/pro/tree/docs/Index.zh.md
- packages/pro/tree/src/ProTree.tsx
- packages/pro/tree/src/types.ts
当设置searchValue后，onSearch无法获取最新的输入值
获取正常
> fix(pro:tree): onSearch cannot get the latest searchValue value

- packages/components/date-picker/demo/Format.vue
- packages/components/date-picker/src/composables/useFormat.ts
- packages/components/date-picker/src/composables/useRangePanelState.ts
- packages/components/date-picker/src/composables/useTimePanelProps.ts
- packages/components/date-picker/src/content/Content.tsx
- packages/components/date-picker/src/content/RangeContent.tsx
feat(comp:date-picker): timeFormat is now infered from format by default
fix(comp:date-picker): time of Date value should be kept after range value selected
1. timeFormat不会根据format推断
2. 日期范围选择之后选择的时间会变成 00:00
1. timeFormat在不提供的时候默认根据format推断
2. 日期范围选择之后保留原有的时间
> feat(comp:date-picker): timeFormat is now infered from format by default；time of Date value should be kept after range value selected

- packages/components/notification/docs/Index.zh.md
- packages/components/notification/src/NotificationProvider.tsx
- packages/components/notification/src/types.ts
> feat(comp:notification): support contentProps (#1014)

- packages/components/transfer/docs/Index.zh.md
- packages/components/transfer/src/Transfer.tsx
- packages/components/transfer/src/composables/useTransferData.ts
- packages/components/transfer/src/composables/useTransferDataStrategies.ts
- packages/components/transfer/src/types.ts
- packages/pro/transfer/docs/Index.zh.md
- packages/pro/transfer/src/ProTransfer.tsx
feat(comp:transfer): add defaultTargetData prop
配置了getKey之后，删除初始不在datasource中的已选数据时，删除不成功
transfer不支持defaultTargetData
修复以上问题
基础穿梭框组件支持defaultTargetData配置初始已选数据
> fix(comp:transfer): removing items absent from datasource works now

- packages/components/tree-select/src/content/Content.tsx
- packages/components/tree/__tests__/tree.spec.ts
- packages/components/tree/src/composables/useSelectable.ts
- packages/components/tree/src/types.ts
reclick tree-select option will cancel the selected state
reclick tree-select option will not cancel the selected state
> fix(comp:tree-select): do not deselect when reclicked

- packages/cdk/forms/__tests__/abstractControl.spec.ts
- packages/cdk/forms/__tests__/formGroup.spec.ts
- packages/cdk/forms/src/controls.ts
> feat(cdk:forms): setError supports path param

- packages/cdk/forms/docs/Api.zh.md
- packages/pro/tree/docs/Api.zh.md
> docs: add some missing documents

- packages/components/table/style/border.less
```html
<IxTable :columns="columns" :dataSource="data" spin :borderless="false">
```
同时设置 spin=true, borderless=false 时，不显示边框。
> fix(comp:table): bordered not work with spin

- packages/cdk/utils/src/composable.ts
- packages/site/src/main.ts
修改 useControlledProp 方法 defaultValue 行为，即提供defaultValue时state不会是undefined
> fix(cdk:utils): fix useControlledProp defaultValue behavior

- packages/pro/search/src/composables/useSearchStates.ts
复合搜索 onItemRemove 事件参数 searchValue 是 undefined
复合搜索 onItemRemove 事件参数 searchValue 修复为删除的 value
> fix(pro:search): onItemRemove should emit searchValue

- packages/components/alert/__tests__/alert.spec.ts
- packages/components/alert/src/Alert.tsx
```
<template>
<IxAlert :pagination="pagination">
<div v-for="(item, index) in titles" :key="index">
{{ item }}
</div>
</IxAlert>
</template>
<script lang="ts" setup>
import { reactive } from 'vue'
const titles = ['上次看到这句话的时候还是上次。', '上次看到这么无语的话，还是在上次。', '上次看到这么的发言还是上次。']
const pagination = reactive({
pageIndex: 1,
onChange: (index: number) => {
pagination.pageIndex = index
},
})
</script>
```
当设置了`pagination.pageIndex`，无法通过分页按钮切换，并且无法触发`onChange`
修复正常
> fix(comp:alert): cannot change pagination.pageindex through button

- packages/components/textarea/__tests__/__snapshots__/textarea.spec.ts.snap
- packages/components/tree/src/composables/useExpandable.ts
树组件的搜索清空后，全部节点自动收起
树组件的搜索清空后，保留最初的展开展开状态
> fix(comp:tree):  keeps original expanded state after search clear now

- packages/components/_private/selector/style/multiple.less
sm尺寸下多选在已选为空的时候高度异常
去掉sm下 margin: 0, 使高度正常
> fix(comp:select): fix select height error with size 'sm'

- packages/components/_private/selector/src/Selector.tsx
- packages/components/_private/selector/style/index.less
- packages/components/_private/selector/style/multiple.less
- packages/components/tree-select/__tests__/__snapshots__/treeSelect.spec.ts.snap
focus on input should not be lost after clicking on the serchable select
多选select在同时有allowInput以及searchable的时候，出现点击selector时input失焦的问题
在allowInput或者searchable时，点击selector本身不失焦，点击后缀关闭浮层
> fix(comp:select): fix searchable select input focus error

- packages/components/_private/selector/style/single.less
单选select在已选为空的时候，包含它的容器高度多出了2px
修复以上问题
> fix(comp:select): fix select height error when empty

- packages/pro/tree/demo/Basic.vue
- packages/pro/tree/docs/Api.zh.md
- packages/pro/tree/src/ProTree.tsx
- packages/pro/tree/src/types.ts
- packages/pro/tree/style/index.less
- packages/pro/tree/style/themes/default.variable.less
1. proTree虚拟滚动容器高度不可控，会出现两个滚动条
2. proTree header 高度不符合视觉稿
1. 增加height prop控制虚拟滚动容器高度
2. 修改header样式实现，去掉不该有的padding
> fix(pro:tree): add height prop supports, update proTree header height and container padding

- packages/components/_private/selector/style/multiple.less
- packages/components/_private/selector/style/single.less
singled select item should show ellipsis when text overflowd
single multipled select item shouldn't shove following elements into a new line
1. 单选 selector item 文字溢出
2. 多选 selector item 文字溢出会导致出现空行撑开整体高度
1. 单选 selector item 文字溢出显示省略号
2. 多选 selector item 限制最大宽度使其不会导致换行
> fix(comp:select): fix selector item text overflowed style

- packages/cdk/utils/__tests__/vNode.spec.ts
- packages/cdk/utils/src/vNode.ts
fix: https://github.com/IDuxFE/idux/issues/1098
overlay 插槽中首个节点是注释节点时 组件不能正常渲染
overlay 插槽中首个节点是注释节点时 组件可以正常渲染
> fix(comp: overlay): first vnode is comment node

- packages/cdk/utils/src/vNode.ts
- packages/components/cascader/src/contents/OverlayContent.tsx
- packages/components/select/src/Select.tsx
- packages/components/tree-select/src/content/Content.tsx
- 设置  searchable='overlay' 的时候，onSearch 事件无法触发。
- 同时还有 tree-select， cascader 组件也有同样问题。
> fix(comp:select): onSearch not work with searchable='overlay'

- packages/cdk/scroll/src/virtual/composables/useScrollPlacement.ts
1. 虚拟滚动设置height且fullHeight为false时，会出现scollTop计算为负的情况，导致渲染数据计算异常
1. 修复以上问题
> fix(cdk:scroll): scrollTop error caused by miscalculation

- packages/components/tree-select/src/TreeSelect.tsx
```
<template>
<IxForm class="demo-form" :control="formGroup">
<IxFormItem>
<ix-tree-select
style="width: 300px"
v-bind="bindData"
control="treeSelect"
:dataSource="dataSouce"
ref="treeSelectRef"
>
<template #expandIcon="{ expanded }">
<ix-icon :name="expanded ? 'minus-square' : 'plus-square'" />
</template>
</ix-tree-select>
</IxFormItem>
<IxButton mode="primary" @click="onSubmit">Submit</IxButton>
</IxForm>
</template>
import { Validators, useFormGroup } from '@idux-vue2/cdk/forms'
import { ref } from '@idux-vue2/cdk/vue'
const { required } = Validators
const bindData = ref({
multiple: true,
showLine: true,
cascade: true,
checkable: true,
searchable: 'overlay',
labelKey: 'label',
getKey: 'value', …
```
> fix(comp:tree-select): cannot get node through getNode

- packages/components/_private/checkable-list/src/types.ts
- packages/components/cascader/src/types.ts
- packages/components/menu/src/types.ts
- packages/components/select/src/types.ts
- packages/components/transfer/src/types.ts
- packages/components/tree-select/src/types.ts
- packages/components/tree/src/types.ts
- packages/pro/tree/src/types.ts
> refactor(comp:*): fix the customAdditional type error

- .eslintrc.js
- packages/components/_private/overlay/__tests__/overlay.spec.ts
- packages/components/config/src/defaultConfig.ts
- packages/components/config/src/types.ts
- packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
- packages/components/table/__tests__/table.spec.ts
- packages/components/table/docs/Api.zh.md
- packages/components/table/index.ts
- packages/components/table/src/Table.tsx
- packages/components/table/src/main/body/BodyCell.tsx
- packages/components/table/src/token.ts
- packages/components/table/src/types.ts
- packages/components/tree-select/src/TreeSelect.tsx
- 单元格内容为空时，可以通过 `emptyCell` 来渲染默认内容。
> feat(comp:table): support for rendering empty cells

- packages/pro/search/src/searchItem/Segment.tsx
error when previousState doesn't exist
ProSearch 退格键删除上一个搜索项目时，在上一个搜索项不存在时报错
修复以上问题
> fix(pro:search):  error when deleting previsous item with backspace

- packages/cdk/click-outside/docs/Api.zh.md
- packages/cdk/popper/src/types.ts
- packages/components/cascader/src/Cascader.tsx
- packages/components/cascader/src/contents/OverlayContent.tsx
- packages/components/cascader/src/token.ts
- packages/components/select/src/composables/useOverlayState.ts
级联组件贴近浏览器边缘后，再打开下一级菜单，此时下一级菜单会到窗口外（看不见）。
每次打开下一级菜单的时候，会更新一下 overlay 的位置，避免上述情况的出现。
> fix(comp:cascader): update overlay position after edging

- packages/pro/search/src/ProSearch.tsx
proSearch clickoutside 没有过滤掉浮层点击
修复以上问题
> fix(pro:search): clickside should exclude overlay container

- packages/components/table/src/main/MainTable.tsx
- packages/components/table/style/fixed.less
- packages/pro/table/src/ProTableLayoutTool.tsx
> fix(comp:table): trigger scroll when column widths changes

- packages/pro/transfer/src/composables/useTransferTableProps.ts
- packages/pro/transfer/src/content/RenderRemovableLabel.tsx
- packages/pro/transfer/style/index.less
remove icon isn't displayed when table column ellipsis is set
表格穿梭框目标表格列配置 ellipsis时，删除图标不显示
修复以上问题
> fix(pro:transfer): remove icon isn't displayed

- packages/pro/transfer/docs/Api.zh.md
- packages/pro/transfer/src/types.ts
treeProps and tableProps type shoud be consistent with table and tree
treeProps和tableProps中的属性类型没有对应tree和table
修改类型，使用Pick与原类型一致
> fix(pro:transfer): modify treeProps and tableProps type

- packages/cdk/scroll/src/virtual/VirtualScroll.tsx
- packages/cdk/scroll/src/virtual/composables/useScrollPlacement.ts
- packages/cdk/scroll/src/virtual/composables/useScrollTo.ts
- packages/cdk/scroll/src/virtual/contents/Holder.tsx
- packages/cdk/scroll/src/virtual/token.ts
scrolledBottom event shouldn't trigger when maxheight change
虚拟滚动的scrolledBottom在初始化以及高度改变时异常触发
仅在滚动事件触发的前提下触发scrolledBottom事件
> fix(cdk:scroll): virtual scroll scrolledBottom event

- packages/pro/search/demo/ConvertToKeyword.vue
- packages/pro/search/docs/Api.zh.md
- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/composables/useActiveSegment.ts
- packages/pro/search/src/composables/useFocusedState.ts
- packages/pro/search/src/composables/useSegmentStates.ts
- packages/pro/search/src/searchItem/SearchItem.tsx
- packages/pro/search/src/searchItem/Segment.tsx
- packages/pro/search/src/types.ts
- packages/pro/search/style/index.less
proSearch 不支持 tab键 focus，不支持 onFocus、onBlur等
新增 onFocus、onBlur 事件，新增 focus、blur 方法
重构focus事件处理机制，放弃原有基于点击触发逻辑
> feat(pro:search): add focus and blur support

- packages/pro/transfer/src/composables/useTransferTreeProps.ts
tansfer tree should show scrollbar when scroll.height is set
树穿梭框，在不配置 virtual时配置scroll.height，滚动失效
修复以上问题
> fix(pro:transfer): transfer tree should show scrollbar

- packages/components/drawer/docs/Api.zh.md
- packages/components/drawer/src/Drawer.tsx
- packages/components/drawer/src/types.ts
- packages/components/modal/docs/Api.zh.md
- packages/components/modal/src/Modal.tsx
- packages/components/modal/src/types.ts
- packages/components/tooltip/docs/Api.zh.md
- packages/components/tooltip/src/types.ts
- packages/components/tooltip/src/useTooltipOverlay.ts
开启 Keep Alive 的时候，tooltip 等组件不会关闭，任然悬浮在界面中。
- 支持设置 closeOnDeactivated， 在 onDeactivated 关闭相关浮层组件。
- 支持的组件有：tooltip, popover, popconfirm, modal, drawer
> feat(comp:tooltip): supports closeOnDeactivated

- packages/components/upload/src/component/ImageCardList.tsx
- packages/components/upload/src/component/ImageList.tsx
- packages/components/upload/src/component/TextList.tsx
当文件没有状态status时，类名展示错误
当文件没有状态status时，不展示相应类名
> fix(comp:upload): fix incorrect class name when has not status

- packages/components/upload/src/composables/useRequest.ts
- packages/components/upload/src/types.ts
- packages/components/upload/src/util/request.ts
action和files必须
action和files非必须
> feat(comp:upload): actions and files are optional

- packages/pro/search/src/composables/useActiveSegment.ts
- packages/pro/search/src/composables/useFocusedState.ts
- packages/pro/search/src/composables/useSearchStates.ts
- packages/pro/search/src/composables/useSegmentStates.ts
- packages/pro/search/src/searchItem/SearchItem.tsx
- packages/pro/search/src/searchItem/Segment.tsx
- packages/pro/search/src/segments/CreateSelectSegment.tsx
1. 被激活的下一个segment触发onPanelVisibleChange时，触发了上一个segment的回调函数
2. select在多选时，取消全选应当设置值为undefined而非[]
3. 搜索项从激活到未激活后状态没有初始化
修复以上问题
> fix(pro:search): fix onVisibleChange and segment state initialization

- packages/components/_private/time-panel/index.ts
- packages/components/_private/time-panel/src/composables/useOptions.ts
- packages/components/_private/time-panel/src/types.ts
- packages/components/_private/time-panel/src/utils.ts
- packages/components/time-picker/demo/Disable.vue
- packages/components/time-picker/docs/Api.zh.md
- packages/components/time-picker/src/composables/usePanelProps.ts
- packages/components/time-picker/src/composables/usePickerState.ts
- packages/components/time-picker/src/content/Content.tsx
- packages/components/time-picker/src/utils.ts
> fix(comp:time-picker): inputs should check disabled time

- packages/components/textarea/docs/Api.zh.md
- packages/components/textarea/src/composables/useAutoRows.ts
- packages/components/textarea/src/types.ts
autoRows 不支持 minRows和 maxRows 单独配置
支持 单独配置 minRows和 maxRows
> feat(comp:textarea): autoRows supports setting min and max separately

- packages/cdk/popper/src/utils.ts
- packages/components/_private/overlay/style/index.less
overlay 在滚动到 滚动区域外之后依旧显示
overlay 在trigger滚动到 滚动区域外之后隐藏
> feat(comp:*): overlay is now hidden as trigger overflows scroll parents

- package.json
- packages/cdk/scroll/src/virtual/VirtualScroll.tsx
- packages/cdk/scroll/src/virtual/contents/Holder.tsx
- packages/components/table/docs/Api.zh.md
- packages/components/table/src/Table.tsx
- packages/components/table/src/composables/useScroll.ts
- packages/components/table/src/composables/useScrollOnChange.ts
- packages/components/table/src/main/MainTable.tsx
- packages/components/transfer/src/list/List.tsx
- packages/components/tree/src/Tree.tsx
表格开启 virtual 和 列固定后, 重新加载数据 fixed 效果没了, 要重新拖动滚动条才能重新出现
原因是因为开启虚拟滚动后，scroll body 拿错了。
> fix(comp:table): the scroll body is incorrect, when virtual enabled

- packages/components/table/src/main/head/HeadCell.tsx
> fix(comp:table): th with center align not work

- packages/components/modal/src/ModalWrapper.tsx
在关闭过渡动画期间点击确定或者取消，会重复触发确定和取消事件
修复以上问题
只有在visible为true时按钮点击触发对应回调
> fix(comp:modal): prevent ok & cancel from triggering while animating

- packages/cdk/popper/src/composables/useOptions.ts
> fix(cdk:popper): vue warning when watch on non-reactive options

- packages/components/_private/selector/style/index.less
selector的suffix始终居中展示
selector的suffix应当固定在顶部，撑开后不改变位置
视觉检视
> fix(comp:select): selector suffix should stay on top

- packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap
- packages/pro/transfer/src/composables/useTreeDataStrategy.ts
- packages/pro/transfer/src/composables/useTreeDataStrategyContext.ts
- packages/pro/transfer/src/wrapper/TreeTransferWrapper.tsx
cascaderStategy ‘parent’ 在 flat-target-data 下不正常
label的count计算不正确
修复以上问题
重构部分代码结构
> fix(pro:transfer): strategy parent with flat-target-data not working

- packages/components/table/src/main/head/triggers/FilterableTrigger.tsx
筛选下拉选择确定按钮尺寸为 'sm'
修改为 ‘xs’
视觉检视
> fix(comp:table): change filterable dropdown footer button size to xs

- packages/components/input/style/index.less
icon-size修改为16px后，当suffix仅是文字时，字体大小也是16px，看起来很突兀
修改，仅当suffix是icon时，font-size 为 icon-size
> fix(comp:input): input suffix is `icon size` only when it's icon

- packages/components/tabs/demo/Scroll.vue
- packages/components/tabs/src/InternalTabs.tsx
- packages/components/tabs/src/composables/useOffset.ts
- packages/components/tabs/src/composables/useSize.ts
当存在滚动条时，首次设置selectedKey，无法滚动到相应位置
功能正常
新增tabs时滚动位置由用户指定的selectedKey来决定偏移位置，内部不进行处理
> fix(comp:tabs): offset error when setting selectedKey

- packages/components/index.ts
- packages/components/spin/__tests__/__snapshots__/spinProvider.spec.ts.snap
- packages/components/spin/__tests__/spinProvider.spec.ts
- packages/components/spin/demo/Basic.vue
- packages/components/spin/demo/UseSpin.md
- packages/components/spin/demo/UseSpin.vue
- packages/components/spin/docs/Api.zh.md
- packages/components/spin/index.ts
- packages/components/spin/src/Spin.tsx
- packages/components/spin/src/SpinProvider.tsx
- packages/components/spin/src/token.ts
- packages/components/spin/src/types.ts
- packages/components/spin/src/useSpin.ts
- packages/components/spin/style/index.less
- packages/site/src/App.vue
| 名称 | 说明 | 参数类型 | 备注 |
| --- | --- | --- | --- |
| `open`   | 打开 | `(options: SpinOptions) => SpinRef` | `target`不传，默认为`target`为`body` |
| `update`  | 更新 | `(options: SpinOptions) => void` | `target`不传，默认为`target`为`body` |
| `destroy`  | 销毁 | `(target?: TargetType \| TargetType[]) => void` | `target`不传，默认为`target`为`body` |
| `destroyAll`  | 销毁全部 | `() => void` | - |
```ts
export type SpinOptions = Partial<
Omit<SpinProps, 'spinning'> & {
tip: string
target: string | HTMLElement | (() => string | HTMLElement)
zIndex: number
}
>
export interface SpinRef {
update: (options: SpinRefUpdateOptions) => void
destroy: () => void
}
```
> feat(comp:spin): add IxSpinProvider

- packages/components/date-picker/__tests__/dateRangePicker.spec.ts
- packages/components/date-picker/demo/AllowInput.md
- packages/components/date-picker/demo/Disabled.md
- packages/components/date-picker/demo/DisabledDate.md
- packages/components/date-picker/demo/Format.md
- packages/components/date-picker/demo/FormatCustom.md
- packages/components/date-picker/demo/OverlayRender.md
- packages/components/date-picker/demo/Range.md
- packages/components/date-picker/demo/SelectRangeIn7Days.md
- packages/components/date-picker/demo/SelectRangeIn7Days.vue
- packages/components/date-picker/docs/Api.zh.md
- packages/components/date-picker/src/composables/useRangePanelState.ts
- packages/components/date-picker/src/composables/useTimePanelProps.ts
- packages/components/date-picker/src/content/RangeContent.tsx
- packages/components/date-picker/src/types.ts
无法支持根据正在选择的日期范围动态计算应禁用的日期
增加 onSelect 事件，行为如下：
首次点击触发selecting状态，事件触发，参数为[date, undefined]
再次点击，解除selecting状态，事件触发，参数为[date, date]
补充单测以及选择7天内范围的demo
> feat(comp:date-picker): add dateRangePicker `onSelect` event

- packages/components/input-number/src/useInputNumber.ts
The value passed in from calling formGroup.setValue is not strictly checked.
Strictly check if value is a number when calling formControl.setValue function.
```
// value is empty(not a number, but can be covert to number), 
// don't throw any error, set the value to null.
formControl.setValue({ value: '' })
// value is not a number(NaN), throw the error when environment is 'development',
// and set the value to null.
formControl.setValue({ value: {} })
// value is a string, not empty and can be covert to number,
// so set the value to the converted number.
formControl.setValue({ value: '123' })
// value is a string, not empty and can't be covert to number,
// so set the value to null and throw the error when environment is …
```
> fix(comp:input-number): Strictly check whether value is a number

- packages/components/date-picker/src/composables/useRangePanelState.ts
- packages/components/date-picker/src/panel/RangePanel.tsx
日期范围面板反向选择日期范围会交换起始日期的时间，即结束日期的时间和开始日期的时间被互换了
修复以上问题
> fix(comp:date-picker): range panel date select shouldn't swap time

- packages/components/_private/selector/src/Selector.tsx
- packages/components/cascader/docs/Api.zh.md
- packages/components/select/demo/SelectAll.vue
- packages/components/select/docs/Api.zh.md
- packages/components/tree-select/docs/Api.zh.md
> feat(comp:select,comp:tree-select,comp:cascader): add selectedItem slot

- packages/components/slider/src/Thumb.tsx
鼠标移动到 slider thumb上触发mouseleave, tooltip关闭，接着触发mouseenter, tooltip开启，导致tooltip闪烁
将mouseenter、mouseleave事件同时绑定到thumb以及tooltip上，防止闪烁
> fix(comp:slider): slider thumb tooltip shouldn't blink

- packages/components/space/demo/Basic.vue
- packages/components/space/demo/CustomSize.vue
- packages/components/space/demo/Size.vue
- packages/components/space/demo/Vertical.vue
- packages/components/space/demo/Wrap.vue
- packages/components/space/docs/Api.zh.md
- packages/components/space/src/Space.tsx
- packages/components/space/style/index.less
- packages/site/src/styles/themes/index.less
- 空的子元素会产生多余的间隔。
通过 `:empty` 将 item 给隐藏掉。
> fix(comp:space): empty item should be hidden

- packages/pro/search/demo/MergeItems.vue
- packages/pro/search/src/composables/useActiveSegment.ts
- packages/pro/search/src/composables/useFocusedState.ts
- packages/pro/search/src/searchItem/SearchItem.tsx
- packages/pro/search/src/searchItem/Segment.tsx
- packages/pro/search/src/segments/CreateNameSegment.tsx
完成一个搜索项的确认之后会自动弹出搜索条件名称选择的面板
不再自动弹出该面板（搜索值和操作符的面板不变），在有键盘操作时再弹出，并按esc收回
搜索项名称选择面板在根据输入过滤结果为空时收起
> fix(pro:search): name segment overlay isn't automatically opened now

- packages/components/_private/selector/src/Selector.tsx
在overlay opend 的时候，点击selector，由于placeholder在上层，无法focus到input上
修复以上问题
> fix(comp:select): clicking selector when opened should trigger focus

- packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
- packages/components/table/demo/Fixed.vue
- packages/components/table/src/composables/useTableLayout.ts
- packages/components/table/src/main/ColGroup.tsx
- packages/components/table/src/main/head/triggers/SelectableTrigger.tsx
- packages/components/table/style/index.less
- packages/components/table/style/size.less
- packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap
- 设置 scroll.width 后，始终会出现滚动条
- 原因是 body 的 col 也都设置了 width, 由于计算 MeasureCol  的宽度并不精确，会存在四舍五入的情况。
- 导致 body 所有的列加起来的宽度超过了表格本身的宽度，然后出现滚动条。
> fix(comp:table): scrollbar always appear, when scroll.width is set

- packages/components/button/__tests__/button.spec.ts
- packages/components/button/src/Button.tsx
- packages/components/button/style/index.less
- packages/components/card/style/index.less
- packages/components/pagination/style/index.less
- packages/pro/table/style/index.less
- packages/pro/tree/style/index.less
- text 和 link 模式的时候，padding 设置为 0, 背景颜色为透明（禁用状态）
- link 模式的字体颜色为主色
- link 模式, 只有在设置了相关的 attrs 时，才渲染成 a 标签
- 移除 Pagination  组件的背景颜色，pagination-item 的 line-height 为 1
- 移除 Card 组件中 header 的无用样式
- 修复 ProTree 组件中 header 的异常样式
> fix(comp:button, card, pagination, pro:tree): style update

- packages/components/modal/src/ModalBody.tsx
- packages/components/modal/src/ModalProvider.tsx
- packages/components/modal/src/types.ts
调用 userModal 创建的 modalRef 的update 更新 content，无法触发更新
修复以上问题
添加私有属性 __content_prop用来传递content
> fix(comp:modal): update modal content with `update` doesn't work

- packages/cdk/utils/src/vNode.ts
- packages/components/transfer/src/content/Header.tsx
slot渲染的空suffix（包含Fragment、Comment、或者空数组等），没有被判空导致渲染了空的suffix节点占位置
修复以上问题
> fix(comp:transfer): empty suffix node shouldn't be rendered

- packages/components/table/src/Table.tsx
- packages/components/table/src/composables/useColumns.ts
- packages/components/table/src/composables/useTableLayout.ts
- packages/components/table/src/main/ColGroup.tsx
- packages/components/table/src/main/MainTable.tsx
- packages/pro/table/demo/Resizable.md
- packages/pro/table/demo/Resizable.vue
- packages/pro/table/src/ProTable.tsx
- packages/pro/table/style/index.less
- 可以通过配置 `resizable`，开启拖拽调整列宽，还可以配置 `maxWidth` `minWidth` 来限制列宽的范围。  
- 如果发现设置 `scroll.width` 后无法出现横向滚动条，拖拽一列后导致其他列变得过窄，请对未设置 `width` 的列设置一个 `minWidth`.
- 开启 autoHeight 或者存在 resizable 的列时，tableLayout 默认为 fixed
- 会将列配置中的 minWidth, maxWidth 设置到 col 上
- 开启 autoHeight 后，将始终渲染 FixedHolder
> fix(pro:table): resize one column to make the other columns too narrow

- packages/components/textarea/src/composables/useAutoRows.ts
- packages/pro/textarea/src/composables/useRowsCounts.ts
火狐浏览器下，对textarea的内容和属性变更之后立即获取scrollHeight，获取的还是变更前的高度
先通过对scrollHeight的引用强制触发变更，再次获取高度
> fix(comp:textarea,pro:textarea): scrollHeight miscalculated on firefox

- packages/components/button/__tests__/__snapshots__/buttonGroup.spec.ts.snap
- packages/components/button/__tests__/buttonGroup.spec.ts
- packages/components/button/demo/Group.vue
- packages/components/button/src/ButtonGroup.tsx
- packages/components/button/src/types.ts
- packages/components/button/style/index.less
- 在 ButtonGroup 中的 border radius 被全部干掉了
- border radius 正常显示
- class 名修改：ix-button-group-with-gap =>  ix-button-group-compact
> fix(comp:button): the radius of button group always hidden

- packages/components/_private/overlay/src/Overlay.tsx
overlay destroyOnHide 之后，popper不再计算位置
修复以上问题，在visible改变并且destroyOnHide 为true时重新初始化popper
> fix(comp:*): overlay destory on hide caused popper position error

- packages/components/_private/overlay/src/Overlay.tsx
整理overlay的popper初始化相关逻辑，不改变原有功能
> refactor(comp:*): refactor popper initialization logic of overlay

- packages/components/cascader/__tests__/cascader.spec.ts
- packages/components/cascader/src/Cascader.tsx
- packages/components/cascader/src/composables/useExpandable.ts
fix #1192
存在默认值的时候，打开面板没有展开对应的 option
> fix(comp:cascader): set expandedKeys with default value

- packages/components/cascader/style/themes/default.variable.less
- packages/components/checkbox/style/index.less
- packages/components/dropdown/style/index.less
- packages/components/header/demo/Basic.vue
- packages/components/header/demo/PrefixSuffix.vue
- packages/components/header/demo/SizeBar.vue
- packages/components/header/style/index.less
- packages/components/radio/style/index.less
- packages/components/select/style/index.less
- packages/components/select/style/themes/default.variable.less
- packages/components/table/style/index.less
- packages/components/tree-select/src/content/Content.tsx
- packages/components/tree-select/style/themes/default.variable.less
- packages/pro/table/src/ProTable.tsx
- packages/pro/table/src/ProTableLayoutTool.tsx
- packages/pro/table/style/index.less
- packages/pro/tree/__tests__/__snapshots__/proTree.spec.ts.snap
- packages/pro/tree/src/ProTree.tsx
- packages/site/src/styles/layout/header.less
- 更新了 header 组件的高度和 padding 计算方式
- 修复了 dorpdown 的背景颜色和阴影问题
- 修复了 tree-select，pro-tree 的搜索框样式问题。
> style: update style with design

- packages/components/_private/overlay/src/Overlay.tsx
受控模式下改变visible，内部调用show在初始化之前
调整初始化和show调用的内部顺序，保证show在初始化之后调用
> fix(comp:*): overlay should be initialized before calling show

- packages/pro/table/demo/Resizable.vue
- packages/pro/table/src/contents/ResizableHeadCell.tsx
- 同时开始 sortable, resizable, 在拖拽结束时会触发排序
> fix(pro:table): the sorter should not be triggered on resize end

- packages/cdk/popper/__tests__/__snapshots__/popper.spec.ts.snap
- packages/cdk/popper/src/convertOptions.ts
浮层组件不支持边界溢出自动修正位置
引入 floating-ui的shift插件，解决边界溢出问题
> fix(cdk:popper): use shift middleware to keep popper in view

- packages/components/button/docs/Theme.zh.md
- packages/components/button/style/index.less
- packages/components/button/style/themes/default.variable.less
- packages/components/header/style/index.less
- packages/site/src/styles/docs.less
```html
<IxHeader size="sm">
Title
<template #suffix>
<IxButtonGroup :gap="8" size="xs">
<IxButton icon="setting" @click="onSuffixClick" />
<IxButton icon="setting" @click="onSuffixClick" />
<IxButton icon="setting" @click="onSuffixClick" />
<IxButton icon="menu" @click="onSuffixClick" />
</IxButtonGroup>
</template>
</IxHeader>
```
上面这种情况会导致高度超过了 40px
- 移除了默认的 padding，依赖 display: flex, align-items: center 进行布局。
> fix(comp:header): remove the default padding

- packages/pro/search/src/ProSearch.tsx
overflowed tag shouldn't show when no segment is active under focused state
没有任何搜索项处于激活状态，且复合搜索组件处于聚焦状态时，溢出的标签没有展示
修复以上问题，即使没有任何搜索项处于激活状态，全部标签依然展示完全
> fix(pro:search): all tags should be displayed when focused

- packages/components/table/style/index.less
> fix(comp:table): align not work with selectable

- .eslintrc.js
- packages/components/_private/overlay/src/Overlay.tsx
- packages/components/config/src/types.ts
- packages/components/drawer/src/Drawer.tsx
- packages/components/image/src/ImageViewer.tsx
- packages/components/modal/src/Modal.tsx
- packages/components/tooltip/src/useTooltipOverlay.ts
- packages/components/utils/__test__/zIndex.spec.ts
- packages/components/utils/src/zIndex.ts
- packages/pro/search/src/ProSearch.tsx
- packages/site/src/docs/Faq.zh.md
如何自定义控制浮层的 `z-index`? 通常在与其他组件库混用，或者使用了微前端框架的情况下需要。
首先我们大多数浮层组件都提供了 `zIndex` 的配置（如果没有，可以给我们提供 issue 或者直接 PR），你可以精确的控制它们。  
如果你觉得控制每一个组件的 `zIndex` 比较麻烦，我们也提供了全局配置以便于你进行全局统一管理，例如：
```ts
const initZIndex = 1000
const indexCount = 0
const customGetZIndex = () => initZIndex + indexCount++
useGlobalConfig('common', { overlayZIndex: customGetZIndex })
```
> fix(comp:*): via getter to manage overlayZIndex

- packages/components/upload/docs/Api.zh.md
- packages/components/upload/src/composables/useRequest.ts
- packages/components/upload/src/types.ts
customRequest 不支持async，同时返回值类型强制要求包含`abort`，约束比较大
customRequest 支持async，返回值abort是可选的
@danranVm
> fix(comp:upload): customRequest allows optional and async

- packages/components/date-picker/src/DatePicker.tsx
- packages/components/date-picker/src/DateRangePicker.tsx
- packages/components/time-picker/src/TimePicker.tsx
- packages/components/time-picker/src/TimeRangePicker.tsx
当allowInput为overlay时， 打开浮层会将窗口滚动到顶部
修复以上问题
> fix(comp:date-picker,comp:time-picker): opening picker shouldn't scroll to window top

- packages/components/cascader/src/composables/useExpandable.ts
- packages/components/cascader/src/contents/OverlayContent.tsx
- packages/site/src/docs/Faq.zh.md
> fix(comp:cascader): when children changed,the scrollbar should be pinned

- packages/components/_private/overlay/src/Overlay.tsx
- packages/components/_private/overlay/src/types.ts
- packages/components/cascader/src/Cascader.tsx
- packages/components/date-picker/src/composables/useOverlayProps.ts
- packages/components/dropdown/src/Dropdown.tsx
- packages/components/menu/src/contents/menu-sub/MenuSub.tsx
- packages/components/popconfirm/src/Popconfirm.tsx
- packages/components/popover/src/Popover.tsx
- packages/components/select/src/Select.tsx
- packages/components/time-picker/src/composables/useOverlayProps.ts
- packages/components/tooltip/src/Tooltip.tsx
- packages/components/tooltip/src/useTooltipOverlay.ts
- packages/components/tree-select/src/TreeSelect.tsx
- packages/components/utils/src/portalTarget.ts
- packages/components/utils/src/zIndex.ts
- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/composables/useCommonOverlayProps.ts
- 打开一次浮层组件，会调用两次的 useZIndex
- 修复上面的问题，同时把浮层的 id 前缀从 `overlay` 改成了 `__IDUX_OVERLAY`
> fix(comp:*): opening overlay once triggers two zIndex changes

- packages/pro/search/demo/Basic.vue
- packages/pro/search/docs/Api.zh.md
- packages/pro/search/src/searchItem/Segment.tsx
- packages/pro/search/src/segments/CreateDatePickerSegment.tsx
- packages/pro/search/src/segments/CreateDateRangePickerSegment.tsx
- packages/pro/search/src/segments/CreateSelectSegment.tsx
- packages/pro/search/src/segments/createCustomSegment.ts
- packages/pro/search/src/segments/createInputSegment.ts
- packages/pro/search/style/index.less
搜索输入不支持placeholder
新增搜索输入placeholder属性配置
> feat(pro:search): support searchField placeholder

- packages/pro/search/src/ProSearch.tsx
proSearch的z-index计算不正确，应当只在focused（即激活）时更新zIndex
渲染时就默认更新了zIndex，引发了渲染在弹窗开启之后而导致的zIndex异常
> fix(pro:search): zIndex should be updated only when focused change

- packages/components/config/src/defaultConfig.ts
- packages/components/config/src/types.ts
- packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
- packages/components/table/demo/Selectable.md
- packages/components/table/demo/Selectable.vue
- packages/components/table/docs/Api.zh.md
- packages/components/table/src/composables/useColumns.ts
- packages/components/table/src/main/body/BodyCell.tsx
- packages/components/table/src/main/body/BodyRow.tsx
- packages/components/table/src/types.ts
- packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap
> feat(comp:table): selectable supports showIndex

- packages/components/radio/src/Radio.tsx
- packages/pro/table/demo/Basic.vue
- packages/pro/table/docs/Api.zh.md
- packages/pro/table/src/contents/LayoutToolTree.tsx
- packages/pro/table/src/types.ts
- scripts/gulp/build/less.ts
layoutable 为 `false` 时，将不在布局菜单中显示此列
> feat(pro:table): support layoutable

- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/composables/useFocusedState.ts
- packages/pro/search/src/searchItem/SearchItem.tsx
点击搜索项没有触发focus
overlayContainer的dom查找不正确
修复以上问题
display:none导致元素内的focus事件不能正常触发，隐藏样式修改为使用 `height:0;width:0;opacity:0` 实现
加入了overlayContainerFallback之后没有调整overlay容器Dom获取计算
> fix(pro:search): searchItem mousedown doesn't trigger focused

- packages/components/tree/src/composables/useCheckable.ts
树的半选状态在节点禁用状态下显示不正常
树的半选状态不应该和disabled相关联，无论是否禁用，半选状态都应该被计算
> fix(comp:tree): indeterminateKeys shouldn't check disabled state

- packages/components/textarea/__tests__/__snapshots__/textarea.spec.ts.snap
- packages/components/textarea/src/composables/useAutoRows.ts
- packages/components/textarea/src/composables/useLineHeight.ts
- packages/pro/textarea/src/token.ts
textarea元素如果在一开始未渲染，例如所属DOM树 display:none，lineheight计算为负数，且重新显示后不会重新计算
修复以上问题
> fix(comp:textarea):  lineheight error when not rendered initially

- packages/components/cascader/src/composables/useExpandable.ts
- packages/components/cascader/src/contents/OverlayOption.tsx
- strategy 为 parent 或者 child 的时候，选中状态展示不正确
- 当某一个一级节点为叶子节点时，选中此节点后，展开状态没有被重置
> fix(comp:cascader): selected and expanded status is display incorrectly

- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/searchItem/Segment.tsx
- packages/pro/search/src/token.ts
从非聚焦状态下直接点击搜索项，搜索项浮层的z-index计算会先于输入框，导致搜索项浮层被遮盖
修复以上问题
> fix(pro:search): overlay zIndex should be larger than container

- packages/components/tree-select/docs/Theme.zh.md
- packages/components/tree-select/style/themes/seer.variable.less
- packages/components/tree/demo/ShowLine.vue
- packages/components/tree/docs/Theme.zh.md
- packages/components/tree/style/index.less
- packages/components/tree/style/themes/default.variable.less
- packages/components/tree/style/themes/seer.variable.less
- packages/pro/tree/docs/Theme.zh.md
- packages/pro/tree/style/themes/seer.variable.less
> fix(comp:tree): lines are not aligned

- packages/components/badge/__tests__/badge.spec.ts
- packages/components/badge/src/Badge.tsx
- packages/components/badge/src/BadgeSub.tsx
- packages/components/badge/src/types.ts
- packages/components/badge/style/index.less
- 新版本的 badge 不兼容之前 count 传一个非数字的字符串类型。
- 兼容之前的用法。
> fix(comp:badge): the count should support non-numeric types

- packages/components/stepper/__tests__/steps.spec.ts
- packages/components/stepper/demo/Dot.md
- packages/components/stepper/demo/Dot.vue
- packages/components/stepper/docs/Api.zh.md
- packages/components/stepper/src/StepperItem.tsx
- packages/components/stepper/src/types.ts
- packages/components/stepper/style/index.less
- packages/components/stepper/style/mixin.less
> feat(comp:stepper): add dot prop

- packages/components/tree/src/composables/useCheckable.ts
`checked` should  be the state of check operation instead of state of node
节点处于半选状态时，onCheck 的 `checked` 参数 始终是 true
onCheck 的 `checked` 参数应当为当前操作的状态，即使节点处于半选状态, `checked` 也应当变化
> fix(comp:tree): correct param `checked` of `onCheck`

- packages/pro/transfer/style/index.less
树穿梭框的节点选中之后（不是勾选，是点击）背景颜色不正常
内部覆盖掉选中样式解决以上问题
右边的删除图标背景是必须的，在存在横向滚动时删除图标固定在右边，需要背景颜色遮挡下方文字
> fix(pro:transfer): overide transfer tree node selected bg color

- packages/pro/transfer/src/composables/useTreeExpandedKeys.ts
removed targert expaneded keys shouldn't be synced to source
树穿梭框，收起目标列表的某个节点之后，删除该节点， 源列表对应的节点也被收起来
expandedKeys 从目标列表到源列表的同步仅仅同步添加的key, 删除的key不同步
> fix(pro:transfer): optimize tree expanded keys sync logic

- packages/pro/search/demo/Basic.vue
- packages/pro/search/docs/Api.zh.md
- packages/pro/search/src/composables/useActiveSegment.ts
- packages/pro/search/src/composables/useFocusedState.ts
- packages/pro/search/src/composables/useSearchItem.ts
- packages/pro/search/src/panel/TreeSelectPanel.tsx
- packages/pro/search/src/searchItem/SearchItem.tsx
- packages/pro/search/src/searchItem/Segment.tsx
- packages/pro/search/src/segments/CreateTreeSelectSegment.tsx
- packages/pro/search/src/types/panels.ts
- packages/pro/search/src/types/searchFields.ts
- packages/pro/search/style/index.less
- packages/pro/search/style/themes/default.ts
- packages/pro/search/style/themes/default.variable.less
- packages/pro/search/style/themes/seer.ts
1. 从proTransfer的utils中抽离tree工具函数到cdk
2. 新增复合搜索treeSelect搜索项
> feat(cdk:utils, pro:search): add tree utils, add pro search `'treeSelect'` field

- packages/components/table/src/utils/index.ts
- packages/pro/table/demo/Resizable.md
- packages/pro/table/demo/Resizable.vue
- packages/pro/table/docs/Api.zh.md
- packages/pro/table/src/composables/useResizable.ts
- packages/pro/table/src/contents/ResizableHeadCell.tsx
- 在表格实际渲染宽度超过了 scroll.width 的时候，每一列都会被放大
- 例如本身设置的宽度是 80 ，实际渲染成了 200，缩放了 2.5 倍
- 如果此时通过拖拽拉到了 150px, 经过缩放后实际渲染成了 350px
- 就会出现用户拖拽缩小宽度，但是反而增大了的宽度的异常情况。
/**
* 拖拽宽度计算规则
*
* * 如果不存在原始的 column.width, 则直接将拖拽后的宽度赋值给 column.width
* * 如果存在原始的 column.width, 则需要按比例进行计算: (原始宽度 * 拖拽后段都) / 当前真实渲染的宽度
* * * 同时需要判断是否存在 minWidth, maxWidth，应满足 minWidth < 计算后的宽度 < maxWidth
*/
> fix(pro:table): width calculation problem after resize

- packages/components/_private/selector/src/composables/useInputState.ts
- packages/components/select/src/Select.tsx
fix #1431
正常显示：
错误显示：
可以发现，错误显示的原因就是没有渲染 ix-selector-item 这个盒子
错误情况下丢失焦点，inputValue.value 是有的，所以 !inputValue.value 就为 false，导致 item 没有渲染
> fix(comp:select): blur event make span render bad

- packages/components/tree/src/Tree.tsx
- packages/components/tree/src/types.ts
- packages/pro/tree/src/ProTree.tsx
展开/收起按钮的状态内部是写死的，没有根据当前节点的展开状态实时变化
只要当存在一个展开节点时，按钮的状态为收起全部
> fix(pro:tree): expandAll button state is wrong

- packages/components/select/src/Select.tsx
- packages/components/select/src/composables/useKeyboardEvents.ts
- 在可输入模式下，输入内容后，按下回车键，会保存输入的内容。
- 再一次按下回车键，会把内容重置为第一个选项的值。
- 单选模式下，按下回车后，触发 blur 事件，来规避上面的问题。
> fix(comp:select): call blur after 'enter' envent

- packages/components/transfer/src/composables/useTransferSelectState.ts
`getAllSelectedKeys` in dataStrategy should be used to calculate select all status
级联策略为 `'children'` 时，全选之后勾选状态还是半选
修复以上问题
> fix(comp:transfer): select all status error

- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/composables/useCommonOverlayProps.ts
由于复合搜索的某一个输入框在非激活状态时会隐藏，转换为标签显示，浮层对应的trigger位置会有改变，这时浮层收起的动画显示位置会不正确
暂时去掉复合搜索的浮层动画
> fix(pro:search): remove transition for overlay

- packages/components/carousel/src/composables/useStrategy.ts
当组件scale（大于1 或者 小于1）后，组件布局错误
```
<template>
<IxCarousel class="wrapper">
<div class="card-item">远看泰山黑糊糊</div>
<div class="card-item">上头细来下头粗</div>
<div class="card-item">如把泰山倒过来</div>
<div class="card-item">下头细来上头粗</div>
</IxCarousel>
</template>
<style lang="less" scoped>
.wrapper {
transform: scale(1.5);
}
.card-item {
height: 160px;
line-height: 160px;
background-color: #364d79;
text-align: center;
font-size: 16px;
color: #fff;
}
</style>
```
组件可以正常显示
> fix(comp:carousel): when scaled, the component layout error

- packages/pro/search/src/panel/TreeSelectPanel.tsx
add `height` prop and fix it to `256` so that `treeSelect` panel wont be too high
`treeSelect` 类型面板没有设置高度，会导致超长
暂时固定高度为 `256px`，和目前的 `select` 面板一致，后续考虑是否要增加可配置
> fix(pro:search): `treeSelect` panel height is unset

- packages/cdk/utils/src/dom.ts
- packages/components/carousel/__tests__/carousel.spec.ts
- packages/components/carousel/src/composables/useStrategy.ts
```
<template>
<IxCarousel>
<div v-for="page in pageSizes">
<div class="card-item">远看泰山黑糊糊</div>
</div>
</IxCarousel>
<IxButton @click="pageSizes = 1">减少数量</IxButton>
</template>
<script lang="ts" setup>
const pageSizes = ref(3)
</script>
<style lang="less" scoped>
.card-item {
height: 160px;
line-height: 160px;
background-color: #364d79;
text-align: center;
font-size: 16px;
color: #fff;
}
</style>
```
新增`getCssDimensions`精确获取元素宽高
> fix(comp:carousel): when items is dynamically reduced to 1, layout error

- packages/components/upload/demo/Dragable.vue
- packages/components/upload/style/list.less
1. 上传列表卡片的文字不居中
2. 上传列表卡片的进度条margin关键字错误
3. 拖拽上传的demo不符合规范
修复以上问题
> fix(comp:upload): upload list card status text isn't centered

- packages/components/select/demo/Loading.md
- packages/components/select/demo/Loading.vue
- packages/components/select/docs/Api.zh.md
- packages/components/select/src/Select.tsx
- packages/components/select/src/composables/usePanelProps.ts
- packages/components/select/src/types.ts
> feat(comp:select): add `loading` prop for select component

- packages/pro/search/demo/RemoteSearch.md
- packages/pro/search/demo/RemoteSearch.vue
- packages/pro/search/docs/Api.zh.md
- packages/pro/search/src/composables/useSearchItem.ts
- packages/pro/search/src/composables/useSegmentStates.ts
- packages/pro/search/src/panel/SelectPanel.tsx
- packages/pro/search/src/panel/TreeSelectPanel.tsx
- packages/pro/search/src/searchItem/SearchItem.tsx
- packages/pro/search/src/segments/CreateNameSegment.tsx
- packages/pro/search/src/segments/CreateSelectSegment.tsx
- packages/pro/search/src/segments/CreateTreeSelectSegment.tsx
- packages/pro/search/src/types/panels.ts
- packages/pro/search/src/types/searchFields.ts
- packages/pro/search/src/types/searchItem.ts
- packages/pro/search/src/utils/selectData.ts
add `onSearch` for to make server-side searching possible
当前复合搜索的 `select` 和 `treeSelect` 无法实现服务端搜索
增加 fieldConfig 中的 `onSearch` 属性，支持搜索值改变后修改dataSource，以支持服务端搜索
增加相关 demo
> feat(pro:search): `select` and `treeSelect` support `onSearch` now

- packages/components/collapse/docs/Theme.zh.md
- packages/components/collapse/src/CollapsePanel.tsx
- packages/components/collapse/style/index.less
- packages/components/collapse/style/themes/default.variable.less
add class to expand icon and modify its font-size for all sizes
折叠面板展开收起按钮大小同header的前后缀大小一致为16px
修改为：
md: 24px
sm: 20px
展开收起按钮图标新添加 class，修改为display：fix，解决居中问题
> style(comp:collapse): modify expand icon size

- packages/components/slider/demo/Marks.vue
- packages/components/slider/docs/Theme.zh.md
- packages/components/slider/style/index.less
- packages/components/slider/style/themes/default.variable.less
- packages/components/slider/style/themes/seer.variable.less
激活状态的 mark，在禁用状态下仍然是蓝色
修改样式，使mark在禁用状态下展示灰色
视觉检视问题
> fix(comp:slider): slider marker color error when disabled

- packages/pro/search/src/composables/useCommonOverlayProps.ts
修改浮层垂直offset为 8px， 使最下方的浮层会落在输入框的下面，不覆盖
视觉检视问题
> fix(pro:search): change proSearch overlay vertical offset to 8px

- packages/components/spin/style/index.less
加载中的容器透明度为0.7
应当是不透明度是0.7，即透明度0.3
> fix(comp:spin): spin container blured opacity should be 0.3

- packages/pro/tree/style/index.less
- packages/pro/tree/style/themes/default.variable.less
tree content horizontal padding should be consistent with header and customizable
ProTree的内容区域padding和头部不一致，导致后缀和悬浮背景边界没有和头部文字对齐
添加内容区域padding样式
> fix(pro:tree): tree content horizontal padding

- packages/components/rate/src/types.ts
> fix(comp:rate): control not work

- packages/components/alert/style/index.less
alert 的 title 超长换行之后，icon垂直居中展示
icon应当始终在顶部
取消min-height，并且调整组件的上下padding始终为4px，此时单行文字高度为32px
> fix(comp:alert): alert icon should always be aligned top

- packages/pro/search/src/composables/useSearchStates.ts
当searchField允许重复，即配置了multiple时，第一个之后的搜索项合法性判断不正确
例如：第一个关键字会校验非空，空的会被删除掉，第二个关键字没有校验
修复以上问题
> fix(pro:search): mutiple search filed validation error

- packages/pro/search/src/searchItem/Segment.tsx
复合搜索，在面板浮层关闭的时候，面板自身绑定的键盘事件处理函数依然会被触发
在浮层关闭，即面板隐藏的时候，面板的键盘事件不应该触发，键盘操作应当唤起面板显示
> fix(pro:search): panel onkeydown should only be called when opened

- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/composables/useActiveSegment.ts
- packages/pro/search/src/composables/useControl.ts
- packages/pro/search/src/composables/useFocusedState.ts
- packages/pro/search/src/composables/useSegmentStates.ts
- packages/pro/search/src/searchItem/Segment.tsx
extract active segment control from focus state logic create `useControl` hook to control component root element interactions
focus blur 管理和组件的交互耦合在一起，不方便交互行为的优化，改动容易出问题
将交互逻辑和组件的focus管理拆分开
将组件根节点元素上的交互逻辑聚合到一个hook中，方便后续优化鼠标键盘操作等
> refactor(pro:search): refactor focus state logic

- packages/pro/search/demo/Basic.vue
- packages/pro/search/demo/RemoteSearch.vue
- packages/pro/search/docs/Api.zh.md
- packages/pro/search/src/composables/useSearchItem.ts
- packages/pro/search/src/panel/CascaderPanel.tsx
- packages/pro/search/src/panel/DatePickerPanel.tsx
- packages/pro/search/src/panel/PanelFooter.tsx
- packages/pro/search/src/panel/SelectPanel.tsx
- packages/pro/search/src/panel/TreeSelectPanel.tsx
- packages/pro/search/src/segments/CreateCascaderSegment.tsx
- packages/pro/search/src/segments/CreateSelectSegment.tsx
- packages/pro/search/src/segments/CreateTreeSelectSegment.tsx
- packages/pro/search/src/types/panels.ts
- packages/pro/search/src/types/searchFields.ts
- packages/pro/search/src/utils/getSelectableCommonParams.ts
- packages/pro/search/src/utils/index.ts
- packages/pro/search/style/index.less
- packages/pro/search/style/themes/default.variable.less
> feat(pro:search): add `'cascader'` searchField

- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/composables/useSearchStateWatcher.ts
- packages/pro/search/src/composables/useSearchStates.ts
- packages/pro/search/src/composables/useSegmentStates.ts
- packages/pro/search/src/searchItem/Segment.tsx
- packages/pro/search/src/token.ts
add watcher logics to watch inner searchStates changes more percisely
当前的逻辑并不能准确监听数据 `searchStates` 的变化以及变化内容，搜索项的状态也不能精确响应变化
增加 `useSearchStateWatcher` 逻辑，在searchState变化后通知变更，更精确得处理组件状态变化
> refactor(pro:search): add searchState watcher logic

- packages/components/cascader/src/Cascader.tsx
- packages/components/cascader/src/composables/usePanelProps.ts
- packages/components/cascader/src/types.ts
after adding `IxCascaderPanel`, searching isn't working
新增 `IxCascaderPanel` 之后，搜索不起作用了
修复以上问题
> fix(comp:cascader): searchValue not working after CascaderPanel added

- packages/pro/config/src/defaultConfig.ts
- packages/pro/config/src/types.ts
- packages/pro/table/docs/Api.zh.md
- packages/pro/table/src/ProTable.tsx
- packages/pro/table/src/ProTableLayoutTool.tsx
- packages/pro/table/src/contents/LayoutToolContent.tsx
- packages/pro/table/src/token.ts
- packages/pro/table/src/types.ts
布局设置面板新增功能
- 双向绑定 visible
- 隐藏修改大小的图标: changeSize
- 自定义面板样式: className
- 隐藏重置按钮: resetable
- 重置按钮被点击后的回调: onReset
> feat(pro:table): the layout tool support visible, changeSize, resetable

- packages/cdk/forms/__tests__/formArray.spec.ts
- packages/cdk/forms/docs/Api.zh.md
- packages/cdk/forms/src/models/formArray.ts
> feat(cdk:forms): formArray supports clearControls

- packages/components/textarea/src/utils/measureTextarea.ts
removeChild 调用时，clonedTextarea 并不是其子元素
增加判断，解决以上问题
> fix(comp:textarea): measureTextarea removeChild error

- packages/pro/search/src/segments/createInputSegment.ts
input类型搜索项，先输入，再退格清除，此时空的输入会被校验为合法
修复以上问题，空字符串一律返回 undefined
> fix(pro:search): empty input segment should be invalid

- packages/pro/search/demo/RemoteSearch.md
- packages/pro/search/src/segments/CreateNameSegment.tsx
> fix(pro:search): name select label not rendering

- packages/components/cascader/docs/Api.zh.md
- packages/components/cascader/src/types.ts
- packages/components/checkbox/docs/Api.zh.md
- packages/components/checkbox/src/types.ts
- packages/components/date-picker/docs/Api.zh.md
- packages/components/date-picker/src/types.ts
- packages/components/form/docs/Api.zh.md
- packages/components/form/src/types.ts
- packages/components/input-number/docs/Api.zh.md
- packages/components/input-number/src/types.ts
- packages/components/input/docs/Api.zh.md
- packages/components/input/src/types.ts
- packages/components/radio/docs/Api.zh.md
- packages/components/radio/src/types.ts
- packages/components/rate/docs/Api.zh.md
- packages/components/rate/src/types.ts
- packages/components/select/docs/Api.zh.md
- packages/components/select/src/types.ts
- packages/components/slider/docs/Api.zh.md
- packages/components/slider/src/types.ts
- packages/components/switch/docs/Api.zh.md
- packages/components/switch/src/types.ts
- packages/components/textarea/docs/Api.zh.md
- packages/components/time-picker/src/types.ts
- packages/components/tree-select/docs/Api.zh.md
- packages/components/tree-select/src/types.ts
- packages/pro/textarea/docs/Api.zh.md
> fix(comp:*): the control type of all form components is incomplete

- packages/pro/search/src/composables/useSegmentStates.ts
searchItem的内容变化后，输入状态内容被初始化
仅当searchItem的key变化后才初始化输入状态，并建立对该key对应的searchState的监听
> fix(pro:search): segmentState should init only when item key changes

- packages/components/spin/style/index.less
因为 ix-spin 的 `pointer-events` 属性为 none，所以后面的输入框和按钮都能被操作。所以我们应该给他设置成 `auto`。
> fix(comp:spin): btn under `ix-spin` can be clicked

- packages/components/cascader/style/index.less
子面板group数据量比较多，撑开整体面板高度时，父级面板高度没有占满整体面板高度，导致右border高度不对
修复以上问题
> fix(comp:cascader): group height should be same as panel height

- packages/pro/search/docs/Api.zh.md
- packages/pro/search/src/panel/SelectPanel.tsx
- packages/pro/search/src/types/searchFields.ts
fix(pro:search): remove unused select field option
高级搜索的selectField, 虚拟滚动不生效
修复以上问题
去掉未使用的 overlayItemWidth 配置（下个feature版本用overlayClassName统一解决）
> fix(pro:search): select panel virtual not working

- package.json
发布的npm包，@idux/* 相关依赖没有固定而使用 `'^'` ，导致依赖树中存在多个不同版本时实际依赖版本错误
lerna version 命令中 增加 --exact 参数，固定相关依赖版本
> fix: lock @idux dependencies' version to exact versions

- packages/cdk/forms/__tests__/abstractControl.spec.ts
> test(cdk:forms): update disabled case

- packages/components/button/src/Button.tsx
https://playground.idux.site/#eyJQbGF5Z3JvdW5kQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPEl4RHJhd2VyUHJvdmlkZXI+XG4gICAgPEl4Tm90aWZpY2F0aW9uUHJvdmlkZXI+XG4gICAgICA8SXhNb2RhbFByb3ZpZGVyPlxuICAgICAgICA8SXhNZXNzYWdlUHJvdmlkZXI+XG4gICAgICAgICAgPEFwcCAvPlxuICAgICAgICA8L0l4TWVzc2FnZVByb3ZpZGVyPlxuICAgICAgPC9JeE1vZGFsUHJvdmlkZXI+XG4gICAgPC9JeE5vdGlmaWNhdGlvblByb3ZpZGVyPlxuICA8L0l4RHJhd2VyUHJvdmlkZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgc2V0dXBJZHV4IH0gZnJvbSAnLi9zZXR1cElkdXguanMnXG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbnNldHVwSWR1eCgpXG48L3NjcmlwdD5cbiIsIkFwcC52dWUiOiI8dGVtcGxhdGU+XG4gIDxJeEJ1dHRvbkdyb3VwIDpkaXNhYmxlZD1cIiFlbmFibGVkU3RhdHVzXCIgOmdhcD1cIjE2XCI+XG4gICAgPEl4QnV0dG9uIG1vZGU9XCJwcmltYXJ5XCIgQGNsaWNrP …
> fix(comp:button): disabled btn when group's `disabled` is true

- packages/components/_private/selector/src/Selector.tsx
- packages/components/_private/selector/src/composables/useInputState.ts
- packages/components/_private/selector/src/contents/Input.tsx
- packages/components/_private/selector/src/token.ts
fix #1474 
input 添加了 compostionStart 事件和 compositionEnd 事件，但是由于中文输入法的原因 compositionEnd 事件不能被正常触发
就会导致 isComposing 一直为 true，从而下面的 inputValue change 等一系列事件不会运行。
> fix(comp:select):  compositionEnd can't trigger

- packages/components/timeline/__tests__/__snapshots__/timeline.spec.ts.snap
- packages/components/timeline/src/TimelineItem.tsx
- packages/components/timeline/style/index.less
- packages/components/timeline/style/mixin.less
- packages/components/timeline/style/themes/default.variable.less
- packages/components/timeline/style/themes/seer.variable.less
时间线组件样式不符合设计规范
根据seer规范修改组件样式
API没有变，组件样式有改变，dom结构有轻微变动，看是否需要改成feature
> fix(comp:timeline): modify timeline style according to design

- packages/pro/table/style/index.less
出现滚动的时候，最后一列的头部按钮（筛选，排序等）被布局按钮遮挡
修改以上问题
修改样式实现为，在最后一列的 triggers 容器中补充右边距
> fix(pro:table): triggers of last column is covered by layout tool

- packages/components/_private/overlay/style/index.less
> fix(comp:date-picker): prevent elements with class name `ix-overlay`'s `box-sizing` set to `content-box`

- packages/components/_private/date-panel/__tests__/__snapshots__/datePanel.spec.ts.snap
- packages/components/_private/date-panel/__tests__/datePanel.spec.ts
- packages/components/_private/date-panel/src/panel-body/PanelCell.tsx
- packages/components/_private/date-panel/src/utils.ts
disabledDate 禁用一个月中的部分日期，整个月或者年都被禁用
重构 disabledDate 算法，计算月、年、季度时，应当考虑中间所有日期的禁用情况
> fix(comp:date-picker): disabledDate error on year and month panel

- packages/components/_private/overlay/src/Overlay.tsx
- packages/components/_private/overlay/style/index.less
正在执行动画的浮层，也会受到 reference hidden 影响
正在执行动画的浮层不会因为 reference hidden 被隐藏
> fix(comp:*): animating overlay are not hidden anymore

- packages/cdk/popper/__tests__/__snapshots__/popper.spec.ts.snap
- packages/cdk/popper/src/composables/useInstance.ts
- packages/cdk/popper/src/middlewares/refenceHidden.ts
- packages/cdk/popper/src/usePopper.ts
reference hidden 的 popper，位置依然会被计算，此时会把浮层的位置计算到左上角
1. reference hidden 的 popper，位置不会再更新
2. reference hidden 的规则，严格限定为 溢出大于0，等于0不当作被隐藏，排除了 reference display: none 的情况
3. reference display: none 的时候，浮层不再会自动隐藏
> fix(cdk:popper): reference hidden popper are no longer updated

- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/composables/useCommonOverlayProps.ts
之前由于浮层的trigger会在非激活状态隐藏，导致浮层触发reference hidden并且位置计算到了左上角，动画出现问题，因而去掉了动画
以上诱发动画问题的原因已提pr修复，可以重新加回动画
> fix(pro:search): add animation to overlay

- packages/pro/tree/__tests__/__snapshots__/proTree.spec.ts.snap
- packages/pro/tree/__tests__/proTree.spec.ts
- packages/pro/tree/src/ProTree.tsx
> fix(pro:tree): the header don't render when it is empty

- packages/cdk/drag-drop/src/utils.ts
- 挂载在 document 的 context 初始化的逻辑不正确
- 导致了 #1436 的 bug
- 正确使用 createSharedComposable， 保证全局共享的 context 的唯一性
> fix(cdk:drag-drop): the shard context was not initalized correctly

- packages/cdk/portal/src/Portal.tsx
- packages/cdk/utils/src/tryOnScopeDispose.ts
- packages/components/_private/empty/__tests__/__snapshots__/empty.spec.ts.snap
- packages/components/empty/__tests__/__snapshots__/empty.spec.ts.snap
- packages/components/empty/src/Images.tsx
- packages/site/vite.config.ts
- scripts/gulp/build/rollup.ts
- typings/global.d.ts
- vitest.config.ts
> fix(comp:empty): the ids in svg should be only

- packages/components/tree-select/src/content/Content.tsx
当设置了getKey，异步加载数据后，无法触发onLoaded函数，且新加载的数据选中后无法显示
```
<template>
<IxTreeSelect placeholder="异步加载" :dataSource="treeData" :loadChildren="loadChildren" :onLoaded="onLoaded"  getKey="id" />
</template>
import type { VKey } from '@idux/cdk/utils'
import type { TreeSelectNode } from '@idux/components/tree-select'
const treeData: TreeSelectNode[] = [
{
label: 'Parent 0',
id: '0',
},
{
label: 'Parent 1',
id: '1',
},
{
label: 'Tree Node ',
id: '2',
},
]
const loadChildren = (node: TreeSelectNode) => {
return new Promise<TreeSelectNode[]>(resolve => {
setTimeout(() => {
const parentKey = node.idas string
const children = [
{
label: `Child ${parentKey}-0 `,
id: `${parentKey}-0`,
},
{
label: `Child ${parentKey}-1 `, …
```
> fix(comp:tree-select): async loading is invalid when getKey is set

- packages/components/upload/src/util/fileHandle.ts
`accept` 没有区分大小写，导致`onBeforeUpload`未触发
正常触发
> fix(comp:upload): accept does not ignore case

- packages/components/button/style/index.less
- packages/components/button/style/mixin.less
- packages/components/drawer/style/index.less
- packages/components/modal/style/index.less
按钮中的图标没办法居中对齐
使用flex居中对齐
此修改会影响到：带图标和没带图标按钮同时存在时的垂直对齐，请使用`IxButtonGroup` 或者 `IxSpace` ，或者`flex`样式包裹即可
> fix(comp:button): fix icon not vertically centered

- packages/components/_private/overlay/src/Overlay.tsx
```
<template>
<IxTooltip title="prompt text" trigger="manual" :visible="visible" destroyOnHide>
<IxButton @click="visible = !visible">Manual</IxButton>
</IxTooltip>
</template>
<script lang="ts">
import { defineComponent, ref } from 'vue'
export default defineComponent({
setup() {
const visible = ref(false)
return { visible }
},
})
</script>
```
点击button，无法显示tooltip
正常显示
> fix(comp:tooltip): visible is not work when destroyOnHide is true

- packages/components/_private/overlay/src/Overlay.tsx
- packages/components/_private/overlay/style/index.less
trigger隐藏的情况下，正在进行动画过渡的浮层还会显示
修复以上问题
最初是为了解决高级搜索中失焦之后输入框隐藏导致动画不生效的问题，现在由于修改了实现方式输入框不会隐藏，直接去掉动画的判断会更符合逻辑
> fix(comp:*): overlay animating cls should be set only at leaving

- packages/pro/search/src/composables/useSegmentStates.ts
segment states need to be reset after blur when its not confirmed
修改搜索项标签内容不回车确认，在失焦后搜索项标签内容不会重置
在搜索项没有确认的情况下失焦，即激活状态改变为非激活，标签内容应当重置
> fix(pro:search): segment states should be reset after blur

- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/composables/useSegmentStates.ts
点击搜索按钮会重置正在编辑的标签
不应当重置，应当保存当前状态并触发值的修改
问题在于按钮的mousedown没有阻止冒泡，导致触发了useControl中的全局mousedown，导致了激活状态的变化
> fix(pro:search): clicking search button should trigger value change

- packages/pro/search/src/components/quickSelect/QuickSelectItem.tsx
- packages/pro/search/src/components/quickSelect/QuickSelectShortcut.tsx
item created by shortcut shoule be set active after created and onItemCreate should be called
通过快捷选择面板的shortcut创建标签后没有将焦点移动到新创建的标签上
应当在创建后立即设置新标签为激活状态，并展开对应的面板
> fix(pro:search): item created by shortcut shoule be set active

- packages/components/config/src/defaultConfig.ts
- packages/components/config/src/types.ts
- packages/components/modal/src/ModalWrapper.tsx
- packages/components/modal/src/types.ts
modal的animatable不支持全局配置
新增modal的animatable全局配置
> feat(comp:modal): add `animatable` global config

- packages/pro/search/src/segments/createInputSegment.ts
input 类型的搜索项，trim在输入的时候不起作用
修复以上问题
> fix(pro:search): input searchField trim not working

- packages/pro/search/style/quick-select.less
间距使用了margin-left，导致换行后左边会不对齐
改用margin-right
> style(pro:search): shortcuts in quickselect use margin-right instead

- packages/pro/search/docs/Api.zh.md
- packages/pro/search/src/panel/CascaderPanel.tsx
- packages/pro/search/src/panel/TreeSelectPanel.tsx
- packages/pro/search/src/segments/CreateCascaderSegment.tsx
- packages/pro/search/src/segments/CreateTreeSelectSegment.tsx
- packages/pro/search/src/types/searchFields.ts
treeSelect field 新增  `customExpandIcon` 以及 `expandIcon` 配置，支持展开收起按钮自定义渲染
treeSelect field 新增 `customDragableIcon`，支持拖拽按钮自定义渲染
cascader field 新增 `customExpandIcon` ，支持展开收起按钮自定义渲染
> feat(pro:search): add custom icon renderer for treeSelect and cascader

- packages/components/table/demo/NestedTable.md
- packages/components/table/demo/NestedTable.vue
- packages/components/table/style/index.less
- packages/components/table/style/size.less
- packages/components/table/style/themes/default.variable.less
- packages/pro/table/src/contents/LayoutToolTree.tsx
- 配置了 layoutable=false 的列，且为固定列的时候，布局设置面板会出现空状态
- 修复了在小号表格场景下的分页器高度问题
- 修复了嵌套子表格的边距问题
- 请注意样式的改动，子表格多了一个 `  margin: -4px 28px;` 的样式
> fix(pro:table): the empty is not rendered in the layout tool

- packages/components/config/src/dateConfig.ts
- packages/components/dropdown/demo/Basic.vue
- packages/site/src/iduxInstall.ts
> fix(comp:config): the weekStartsOn does not work in the enUS locale

- packages/components/select/src/Select.tsx
- packages/components/select/src/types.ts
- packages/components/table/style/index.less
- 设置 searchable=‘false’ 的时候，不能设置面板中搜索框的 placeholder
> fix(comp:select): the placeholder in overlay can't setting

- packages/components/_private/selector/src/Selector.tsx
- packages/components/cascader/src/Cascader.tsx
- packages/components/notification/src/types.ts
- packages/components/select/src/Select.tsx
- packages/components/tree-select/src/composables/useSelectedState.ts
- packages/components/tree-select/src/content/Content.tsx
- 设置 searchable = true 时，点击输入框的清除图标，不会触发 onSearch 事件，仅触发 onClear 事件
- 设置 searchable = ’overlay‘ 时，点击浮层中输入框的清除图标，不会触发任何事件
- 现在都会触发 onSearch 事件，参数为 '' 空字符。
- 受影响的组件有：Cascader， Select, TreeSelect
> fix(comp:select): the onSearch should be called when the intput is clear

- packages/components/tree/style/index.less
change drop target node box-shadow to inset to prevent overflow
第一个和最后一个节点作为拖动目标的时候，box-shadow不会显示，因为容器配置了 overflow: auto
修改box-shadow为inset，调整样式
如果是inside，则由原先的两条线变成完整的线框
> style(comp:tree): change drop target node box-shadow to inset

- packages/components/modal/src/ModalWrapper.tsx
- Seer 主题下，Modal 的按钮默认为 ’sm‘
- 改为 `md`
> fix(comp:modal): the size of button should be 'md'

- packages/components/_private/date-panel/src/panel-body/PanelCell.tsx
时间日期范围的开始和结束cell，计算时使用的判断基准类型不正确，导致年、月面板中计算错误
修复以上问题，根据不同的面板类型使用不同的比对基准
> fix(comp:date-picker): start and end cell calculation error

- packages/components/menu/style/themes/seer.variable.less
seer主题的menu item高度不符合设计
普通高度和default一样是32px，1级高度为40
> style(comp:menu): modify menu item height for seer

- packages/pro/table/src/contents/LayoutToolContent.tsx
- packages/pro/table/src/contents/LayoutToolTree.tsx
布局设置中的树勾选逻辑错误，对于禁用的列是不允许通过父级修改的
将树的勾选策略改为child，只需要收集子节点勾选项即可，具体禁用和勾选的联动通过tree内部去实现
> fix(pro:table): the checkbox logic in the layout tool tree is incorrect

- packages/components/config/src/types.ts
- packages/components/tree-select/docs/Api.zh.md
- packages/components/tree-select/src/types.ts
- packages/components/tree/docs/Api.zh.md
- packages/components/tree/index.ts
- packages/components/tree/src/composables/useExpandable.ts
- packages/components/tree/src/node/Expand.tsx
- packages/components/tree/src/types.ts
- packages/pro/search/docs/Api.zh.md
- packages/pro/tree/__tests__/__snapshots__/proTree.spec.ts.snap
- packages/pro/tree/docs/Api.zh.md
- packages/pro/tree/src/types.ts
Tree `expandIcon` prop 支持传入渲染函数，全局配置同样支持，方便全局自定义子组件库或主题的展开图标
> feat(comp:tree): expandIcon prop supports render function now

- packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap
- packages/pro/transfer/demo/TableLayoutTool.md
- packages/pro/transfer/demo/TableLayoutTool.vue
- packages/pro/transfer/docs/Api.zh.md
- packages/pro/transfer/src/composables/useTransferTableProps.ts
- packages/pro/transfer/src/content/ProTransferTable.tsx
- packages/pro/transfer/src/types.ts
表格穿梭框中，替换基础表格为proTable，新增布局工具配置
> feat(pro:transfer): add layoutTool support to table transfer

- packages/pro/search/src/components/quickSelect/QuickSelectShortcut.tsx
IxProSearchShortcut 没有 name
修复以上问题
> fix(pro:search): shortcut compont should provide comp name

- packages/components/textarea/src/utils/getBoxSizingData.ts
boxsizing data got from computed style is empty string in firefox, causing paseFloat to return NaN
火狐浏览器下，没有提供样式的属性，getComputedStyle计算出来的是空字符串，导致计算结果为NaN
修复以上问题
> fix(comp:textarea): boxsizing data parse error in firefox

- packages/cdk/resize/docs/Api.zh.md
开发套件中resize套件文档中api错误
fix #1606
> docs(cdk:resize): api docs is incorrect

- packages/components/_private/selector/src/composables/useInputState.ts
- packages/components/select/src/composables/usePanelActiveState.ts
unexpected selection created after pressing enter key when input is in chinese and allowInput is enabled
allowInput开启时， 中文输入法下，直接按回车，有几率直接触发选择项的创建，此时输入的怕拼音字母内容会被保留显示，但实际为空
修复以上问题
> fix(comp:select): pressing enter after chinese input

- packages/pro/search/src/components/segment/Segment.tsx
- packages/pro/search/src/composables/useActiveSegment.ts
- packages/pro/search/src/composables/useSegmentStates.ts
通过左键将光标移动到输入的起始位置之后，鼠标点击到其他地方，退格键不起作用
原因是mouseDown事件回调没有同步光标位置的数据
修复以上问题
> fix(pro:search): segment input mousedown doesn't change selection

- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/composables/useSearchValues.ts
存在临时标签但value是空的时候，placeholder异常显示
高级搜索的标签渲染直接与searchStates数据相关，空状态也应当根据searchStates判断
> fix(pro:search): empty state should be determined by search states

- packages/pro/search/src/components/SearchItem.tsx
- packages/pro/search/src/composables/useSearchStates.ts
- packages/pro/search/src/composables/useSegmentStates.ts
所有的搜索项必须回车确认或者点击面板的确认按钮才会触发value的更新，对于没有面板的搜索项，体验不友好
修改为，如果某个搜索项正在操作的输入段不存在面板，且在输入之后搜索项合法可更新，则在blur的时候更新value
修改之后回车确认会同时触发blur，导致重复更新，因此在updateSearchValue的原基础上加上执行队列并在宏任务的粒度上串行执行，保证单词操作不会重复触发更新
> feat(pro:search): bluring segment with no panel triggers update now

- packages/pro/search/style/quick-select.less
select面板在快捷搜索面板中没有最小高度，导致只有select时会没有高度
设置最小高度 230px
> fix(pro:search): add min-height to select panel in quickselect

- packages/components/style/core/reset.less
在edge浏览器中，password类型的Input会显示小眼睛
覆盖掉该行为
> fix(comp:*): hide password input eye in edge with reset style

- packages/components/_private/overlay/src/Overlay.tsx
overlay在内容为空时，再次渲染之后arrow的尺寸获取不正确，导致浮层位置没有计算arrow的尺寸而错位
修复以上问题
> fix(comp:*): overlay arrow size misculated after rendered null

- packages/components/tour/__tests__/tour.spec.ts
- packages/components/tour/src/Tour.tsx
- packages/components/tour/src/composables/useActiveStep.ts
- packages/components/tour/src/composables/useMask.ts
- packages/components/tour/src/composables/useOverlayProps.ts
- packages/components/tour/src/composables/useStepChange.ts
- packages/components/tour/src/composables/useTarget.ts
- packages/components/tour/src/types.ts
在asnyc模式下，即是用了beforeEnter，在进入下一步之前滚动鼠标，会导致当前的step计算不正确
修复以上问题
> fix(comp:tour): active step incorrect when async

- packages/components/seer.less
- packages/components/tour/src/types.ts
seer.less 中引入了错误的default样式
TourStep中的title应当是可选的
修复以上问题
> fix(comp:tour): step title should be optional

- packages/components/modal/src/ModalWrapper.tsx
对话框header的尺寸不符合设计规范
在header有内容的时候尺寸为md，无内容时尺寸为sm
> fix(comp:modal): header size should be sm when header has no content

- packages/components/select/demo/Group.vue
- packages/components/select/src/composables/useOptions.ts
- packages/components/select/style/index.less
- packages/components/select/style/themes/default.variable.less
分组的选项的缩进不生效
1. 修复以上问题
2. 区分单选和多选的缩进变量
> fix(comp:select): select grouped options indent not working

- packages/components/dropdown/style/index.less
dropdown由于内容会溢出overlay，其圆角会被遮挡不生效
增加overflow: hidden 设置，修复以上问题
> fix(comp:dropdown): dropdown border-radius not working

- packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
- packages/components/table/src/main/body/BodyCell.tsx
- packages/components/table/style/index.less
- packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap
当展开图标右侧只有文字内容而非html元素时，间距失效
修复以上问题
> fix(comp:table): gap between expand trigger and text not working

- packages/components/date-picker/style/panel.less
> fix(comp:date-picker): panel header font-size not right

- packages/components/drawer/__tests__/drawer.spec.ts
- packages/components/drawer/src/Drawer.tsx
- packages/components/drawer/src/token.ts
- packages/components/drawer/style/index.less
当配置了自定义container，首次渲染的时候，由于cdkPortal加载是懒加载，wrapper和内容的渲染和动画同时进行，导致translate动画效果不正常
修复以上问题，在首次visible改变为true的时候，等待nextTick之后再显示，即等待渲染完成
> fix(comp:drawer): translate transition error when container is set

- packages/cdk/forms/src/models/abstractControl.ts
- 使用异步验证器的时候，验证通过后，状态没有被正确的设置，会始终是 ’validating‘
> fix(cdk:forms): the status of control is incorrect with async validators

- packages/pro/search/src/components/quickSelect/QuickSelectItem.tsx
- packages/pro/search/src/components/segment/SegmentInput.tsx
高级搜索，多选在快捷面板中触发取消选择使值为空，没有反应
为空的值应当被移除
> fix(pro:search): empty value set by quick select should be removed

- packages/components/tag/style/index.less
在内容宽度小于最小宽度时，tag标签内容未居中
修复以上问题
> fix(comp:tag): tag content not aligned center

- packages/components/_private/overlay/src/Overlay.tsx
overlay的props更新，popper的options有概率不更新
props的监听应当watch deep
> fix(comp:*): overlay options update should watch deep

- packages/cdk/popper/__tests__/__snapshots__/popper.spec.ts.snap
- packages/cdk/popper/src/middlewares/refenceHidden.ts
当父元素被隐藏，popper不会消失
当父元素被隐藏时，referenceHidden应当是true
> fix(cdk:popper): reference is hidden when ancestors are not visible

- packages/cdk/popper/src/middlewares/arrow.ts
- packages/cdk/popper/src/middlewares/refenceHidden.ts
- packages/cdk/popper/src/middlewares/updatePlacement.ts
当 reference 为dispaly:none 隐藏时，虽然位置不会更新，但箭头位置和placement还是会更新，导致隐藏场景下显示不正常
在reference 为 display:none时，不再更新Placement以及arrow位置
隐藏时不更新是为了解决例如reference是hover才显示的场景
> fix(cdk:popper): popper shouldn't update if reference is display none

- packages/pro/search/src/components/NameSelectOverlay.tsx
- packages/pro/search/src/components/quickSelect/QuickSelectShortcut.tsx
创建搜索项时，默认将第一个输入段置为激活状态
应当将第一个无默认值，即非空的输入段置为激活状态
> fix(pro:search): segment with default value shouldn't be set active

- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/composables/useSearchStates.ts
- packages/pro/search/src/composables/useSegmentStates.ts
高级搜索，当激活的segment发生变化时，所有的segment都会被初始化一遍
仅当激活状态的segment被置于非激活状态，类似于blur的时候，才对其进行单独初始化。
> fix(pro:search): segment should init only when it's set inactive

- packages/components/alert/style/index.less
pagnination的高度和line-height比alert的内容高，导致其于内容不对齐
修复以上问题
> fix(comp:alert): alert content not aligined with pagination

- packages/cdk/popper/src/middlewares/refenceHidden.ts
为了适应一些refernece是鼠标浮动上去才显示的场景，display: none以及display: contents且第一个元素为display: none的元素，如果祖先节点不存在隐藏的节点，则不应当被视为reference hidden使浮层被隐藏，
> fix(cdk:popper): `display: none` reference is not treat as hidden

- packages/components/card/src/Card.tsx
- packages/components/card/style/index.less
card的footer样式是特殊处理的，并且是直接引用的button的样式，导致自己写的button样式被影响
给footer中的button加上class，不影响用户自定义的button
> fix(comp:card): add css class to footer button

- packages/components/drawer/__tests__/drawer.spec.ts
- packages/components/drawer/src/Drawer.tsx
- packages/components/drawer/src/DrawerWrapper.tsx
- packages/components/drawer/src/token.ts
Drawer的内容渲染应当延迟到首次visible之后，否则会导致内容内的组件mounted的时候实际上时隐藏的状态，尺寸获取不正确
修复以上问题
> fix(comp:drawer): content first render should be delayed till visible

- packages/pro/search/src/composables/useSegmentStates.ts
高级搜索，由于搜索项非法而在确认时被删除，onItemConfirm的参数为空
修复以上问题
> fix(pro:search): onItemConfirm value is empty when item is removed

- packages/pro/search/src/composables/useSegmentStates.ts
高级搜索的searchField内容更新，比如远程数据请求之后更新datasource之后，搜索项的状态没有更新
修复以上问题
> fix(pro:search): search states should update when field changes

- packages/components/input/style/index.less
在addon-before中的下拉选择，当Input是invalid时，box-shadow还是蓝色的
取消在invalid时select的box-shadow
> fix(comp:input): addon select should remove box-shadow when invalid

- packages/components/tree/src/composables/useDataSource.ts
树 select 的禁用拼写错误，导致实际收到 drag的禁用影响
修复以上问题
> fix(comp:tree): tree select disabled not right

- packages/components/card/style/index.less
card组件中，.card-size使用了 button 指定元素样式，导致污染到内部自定义的button样式
使用class而非button
> fix(comp:card): footer button style should use class but not button

- packages/pro/search/docs/Api.zh.md
> docs(pro:search): add `size` description to documentation

- packages/pro/search/src/components/segment/Segment.tsx
在safari 下，初始渲染之后高级搜索框被异常自动触发focus
修复以上问题
safari下的input.setSelectionRange会自动触发focus，且没有用户操作的focus没有被拦截
> fix(pro:search): proSearch input shouldn't be auto focused in safari

- packages/pro/search/src/components/NameSelectOverlay.tsx
- packages/pro/search/src/components/segment/TempSegment.tsx
- packages/pro/search/src/composables/useActiveSegment.ts
- packages/pro/search/src/composables/useControl.ts
在有输入过滤的情况下，高级搜索框的搜索项选择浮层中的数据会在关闭的时候闪烁一下
修复以上问题
只在浮层显示的时候更新浮层的数据，避免关闭动画在运行的时候数据被更新
> fix(pro:search): name select overlay data blinks after closed

- packages/pro/search/style/index.less
高级搜索的搜索项选择的input输入会超出容器长度
修复以上问题，增加max-width
> fix(pro:search): name input width shouldn't exceeds container

- packages/components/text/__tests__/text.spec.ts
- packages/components/text/src/Text.tsx
在文字没有被省略的时候，展开收起按钮依然会被渲染
修复以上问题
> fix(comp:text): expand icon shouldn't render when not ellipsised

- packages/components/card/docs/Api.zh.md
- packages/components/card/src/Card.tsx
- packages/components/card/src/types.ts
- packages/components/config/src/defaultConfig.ts
- packages/components/config/src/types.ts
> feat(comp:card): `shadow` supports global config now

- packages/pro/search/demo/CustomShortcuts.vue
- packages/pro/search/demo/QuickSelect.vue
- packages/pro/search/docs/Api.zh.md
- packages/pro/search/src/components/quickSelect/QuickSelectItem.tsx
- packages/pro/search/src/types/searchFields.ts
quickSelectSearchable is deprecated now
将 quickSelectSearchable 合并到 quickSelect 选项，提供对象属性配置，
即：
```ts
{ searchable: boolean }
```
废弃quickSelectSearchable，2.0移除
> feat(pro:search): quickSelect prop supports object option

- packages/pro/textarea/src/content/Content.tsx
IxProTextarea的readonly不生效
修复以上问题
> fix(pro:textarea): readonly not working

- packages/components/text/__tests__/__snapshots__/text.spec.ts.snap
- packages/components/text/src/Text.tsx
- packages/components/text/src/composables/useEllipsis.ts
- packages/components/text/style/index.less
IxText组件在单页面内大量使用会导致内容出现卡顿问题
在简单场景下，即只有单行且没有不可展开收起时，不再使用动态渲染模式，改用css的ellipsis
> fix(comp:text): use css ellipsis at one row to improve performance

- packages/pro/search/src/composables/useSearchStates.ts
高级搜索，当存在未确认的临时创建的搜索项时，外部受控修改value触发初始化后，会出现key重复的问题
重新初始化时，重新计算未确认的已创建搜索项的key，避免key重复
> fix(pro:search): key duplication after controlled value change

- packages/components/text/src/composables/useEllipsis.ts
配置ellipsis.row为1，且文字的长度不足以撑满父容器时，会不停渲染，造成闪烁
修复以上问题，在初始计算内容高度是否超过一行，没有超过则不再进行动态渲染计算
> fix(comp:text): text blinks when content doesn't exceed one row

- packages/components/text/__tests__/__snapshots__/text.spec.ts.snap
- packages/components/text/demo/Tooltip.vue
- packages/components/text/src/Text.tsx
IxText配置了natvie的tooltip时，文字没有省略也显示了tooltip
再没有文字省略时不显示tooltip
> fix(comp:text): native tooltip should show when not ellipsised

- packages/pro/search/src/panel/SelectPanel.tsx
- packages/pro/search/src/segments/CreateSelectSegment.tsx
- packages/pro/search/src/types/panels.ts
高级搜索的select面板当鼠标移开之后激活状态的选项被清空，导致回车无法正常触发
修复以上问题，仅在快捷面板中才会在鼠标移出之后清楚激活状态，
> fix(pro:search): select activeValue shouldn't change on mouse leave

- packages/components/upload/demo/Controlled.md
- packages/components/upload/demo/Controlled.vue
- packages/components/upload/src/composables/useFilesData.ts
- packages/components/upload/src/composables/useRequest.ts
- packages/components/upload/src/composables/useUploadControl.ts
- packages/components/upload/src/types.ts
受控修改 files 不会自动触发上传和终止
修复以上问题，并补充受控操作的demo
> fix(comp:upload): controlled update should trigger upload and abort

- packages/pro/search/src/components/segment/Segment.tsx
高级搜索，在用鼠标点击拖动，双击，或ctrl + A 选中段输入框中的内容后，backspace删除不起作用
> fix(pro:search): segment input delete doesn't work after selecting all

- packages/pro/search/src/composables/useSearchStates.ts
新创建但未确认的搜索项，在其他搜索项被修改之后，顺序会发生变化，导致操作不友好
修复以上问题
每次在值更新后初始化时，会用两个指针分别遍历已经确认的搜索值和未确认的搜索值，根据更新前记录的顺序将连续的未确认的搜索项插入，保证其在原有的位置
受控使用场景的出现频率明显低于这种场景，因此优先保证未确认搜索项的顺序
> fix(pro:search): unconfirmed item sequence should change when update

- packages/pro/search/src/composables/useSearchStates.ts
- packages/pro/search/src/composables/useSegmentStates.ts
远程搜索场景下，当field的配置修改之后，搜索项的输入被强行重置，导致无法实现远程搜索
修复以上问题
> fix(pro:search): remote search not working

- packages/pro/search/demo/Basic.vue
- packages/pro/search/docs/Api.zh.md
- packages/pro/search/src/panel/TreeSelectPanel.tsx
- packages/pro/search/src/segments/CreateTreeSelectSegment.tsx
- packages/pro/search/src/types/panels.ts
- packages/pro/search/src/types/searchFields.ts
高级搜索，树选择搜索项，支持配置 `defaultExpandedKeys` 设置初始默认展开的节点
> feat(pro:search): tree field supports `defaultExpandedKeys`

- packages/pro/search/src/panel/SelectPanel.tsx
- packages/pro/search/src/segments/CreateSelectSegment.tsx
- packages/pro/search/src/types/panels.ts
高级搜索的快捷选择面板中的select组件，也会在选项为空时默认使第一个选项处于激活状态
在快捷选择面板中的select不应当有默认的激活状态选项，保持面板整洁
> fix(pro:search): select in quickselect panel should have active value

- packages/components/text/demo/Lines.md
- packages/components/text/demo/Lines.vue
- packages/components/text/src/Text.tsx
IxText组件，当存在换行的时候，ellipsis不生效
修复以上问题
> fix(comp:text): ellipsis doesn't work when there're line breaks

- packages/components/text/demo/Maxheight.md
- packages/components/text/demo/Maxheight.vue
- packages/components/text/src/Text.tsx
text 组件没有继承属性到根节点，导致无法覆盖修改样式
修复以上问题
补充最大高度的demo
> fix(comp:text): text component should inherit attrs

- packages/components/_private/overflow/src/Item.tsx
- packages/components/_private/overflow/src/Overflow.tsx
- packages/components/_private/overflow/src/types.ts
- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/components/segment/SegmentInput.tsx
当没有任何搜索项溢出容器时，异常展示 +0 
没有任何搜索项溢出时，不应当展示 rest
> fix(pro:search): rest count should hide when no item is overflowed

- packages/components/radio/src/RadioGroup.tsx
fix #1684 
- [-] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [-] Tests for the changes have been added/updated or not needed
- [-] Docs and demo have been added/updated or not needed
IxRadioGroup的gap配置，对字符串和数字的处理不一致 
IxRadioGroup的gap配置为0px时与配置为0表现一致
> fix(comp:radio): gap behaves abnormally when configured without 0px

- packages/pro/table/src/contents/LayoutToolTree.tsx
proTable layout tool禁用时可点击
proTable layout tool禁用时不可点击
> fix(pro:table): layoutool Clickable when disabled

- packages/pro/search/src/components/quickSelect/QuickSelectItem.tsx
fix #1746
searchFileds的key值是0或false，第一次点击选项会清空，第二次点击才能选中
searchFileds的key值是0或false能选中
> fix(pro:search): click is correct when key is zero

- packages/components/_private/mask/style/index.less
- packages/components/badge/demo/Basic.vue
- packages/components/badge/demo/Count.vue
- packages/components/badge/demo/OverflowCount.vue
- packages/components/badge/demo/Processing.vue
- packages/components/badge/demo/Status.vue
- packages/components/badge/demo/Title.vue
- packages/components/date-picker/style/index.ts
- packages/components/drawer/style/index.less
- packages/components/drawer/style/index.ts
- packages/components/image/src/Image.tsx
- packages/components/image/src/ImageViewer.tsx
- packages/components/image/style/index.less
- packages/components/image/style/index.ts
- packages/components/notification/src/NotificationProvider.tsx
- packages/components/popover/style/index.ts
- packages/components/radio/src/Radio.tsx
- packages/components/select/style/index.ts
- packages/components/slider/style/index.ts
- packages/components/tabs/style/index.ts
- packages/components/tour/src/Mask.tsx
- packages/components/tour/style/index.less
- packages/components/tour/style/index.ts
- packages/components/tree-select/style/index.ts
- packages/pro/search/style/index.ts
- packages/pro/textarea/style/index.ts
- packages/pro/transfer/style/index.ts
- packages/pro/tree/style/index.ts
多个组件的样式入口缺少了依赖的组件样式或动效样式
个别组件没有注册主题token
修复以上问题
> fix: style dependencies missing in on-demand import entries

- scripts/gulp/build/less.ts
- scripts/gulp/gulpConfig.ts
打包产物中在组件的 theme 目录下 新增 default.js 和 dark.js 作为主题变量的引用入口
> feat: add theme entries for on-demand import

- packages/pro/layout/style/light.less
proLayout logo 的标题颜色变量使用不正确
修复以上问题
> fix(pro:layout): logo title color theme var reference error

- packages/components/pagination/theme/default.ts
- packages/components/pagination/theme/tokens.ts
分页器的lg尺寸字体大小不符合设计规范
修改lg尺寸的字体大小为fontSizeSm
> fix(comp:pagination): change lg size font size to fontSizeSm

- packages/components/config/src/defaultConfig.ts
- packages/components/config/src/types.ts
- packages/components/theme/docs/Api.zh.md
- packages/components/theme/src/ThemeProvider.tsx
- packages/components/theme/src/composables/useThemeProvider.ts
- packages/components/theme/src/composables/useTokenMerge.ts
- packages/components/theme/src/composables/useTokenRegister.ts
- packages/components/theme/src/types/themeProvider.ts
- packages/components/theme/src/useThemeToken.ts
- packages/components/theme/src/utils/createTokensHash.ts
- packages/site/src/docs/CustomizeTheme.zh.md
- packages/site/src/docs/GettingStarted.zh.md
- tests/setup.ts
用户必须在根组件外部包裹 `IxThemeProvider`，侵入性较强
在没有提供根 provider 时，默认创建并使用全局的 provider context。
提供 injectTheme 配置，支持全局配置，可以手动控制不注入样式
> feat(comp:theme): root level IxThemeProvider is no longer needed

- packages/components/config/src/defaultConfig.ts
- packages/components/config/src/types.ts
- packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
- packages/components/table/demo/AutoHeight.vue
- packages/components/table/docs/Api.zh.md
- packages/components/table/src/Table.tsx
- packages/components/table/src/composables/useScroll.ts
- packages/components/table/src/main/MainTable.tsx
- packages/components/table/src/token.ts
- packages/components/table/src/types.ts
- packages/components/table/style/fixed.less
- packages/components/table/style/index.less
- packages/components/table/style/shadow.less
- packages/components/table/theme/dark.ts
- packages/components/table/theme/default.ts
- packages/components/table/theme/index.ts
- packages/components/table/theme/tokens.ts
- packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap
给横向滚动溢出的表格容器左右增加内嵌阴影
新增 `insetShadow` 配置，可配置开启或关闭内嵌阴影
> feat(comp:table): add insetShadow to horizontal overlowed container

- packages/components/menu/style/mixins.less
- packages/components/menu/theme/dark.ts
- packages/components/menu/theme/index.ts
- packages/pro/layout/src/contents/Header.tsx
- packages/pro/layout/src/contents/Sider.tsx
- packages/pro/layout/style/dark.less
- packages/pro/layout/style/light.less
1. 去掉proLayout的themeProvider嵌套之后浮层内的菜单样式不正常
2. menu组件的暗黑模式主题token不正确，dark模式的样式应该和light保持一致
修复以上问题
> fix(pro:layout): dark theme overlay menu style error

- packages/components/cascader/__tests__/cascader.spec.ts
- packages/components/cascader/src/composables/useSelectedState.ts
- 在单选，并且开启 fullPath 的条件下，点击清空图标，值设置错误。
- 会错误的设置成 [undefined]
- 正确设置成空数组 []
> fix(comp:cascader): the value is incorrect after clicking the clear icon

- packages/components/_private/date-panel/__tests__/__snapshots__/datePanel.spec.ts.snap
- packages/pro/search/demo/Parser.vue
- packages/pro/search/src/composables/useSearchStates.ts
新创建未确认的非multile搜索项，在value受控更新添加相同的filed的搜索项时，不会被覆盖
如果一个搜索项是非multiple，即只允许存在一个，则在value受控更新，添加新的搜索项时，原先未确认的搜索项应当被新搜索项覆盖
> fix(pro:search): non-multiple field created state should be overwritten by new state

- packages/components/tag/demo/GroupedTag.md
- packages/components/tag/demo/GroupedTag.vue
- packages/components/tag/docs/Theme.zh.md
- packages/components/tag/src/TagGroup.tsx
- packages/components/tag/style/index.less
- packages/components/tag/theme/tokens.ts
新增组合标签，IxTagGroup当gap为0时，标签组为组合标签
> feat(comp:tag): support compact group tags

- packages/components/popover/style/index.less
- packages/components/tooltip/style/index.less
> fix(comp:popover,tooltip): replace paddings with theme variables

- packages/components/collapse/style/index.less
- packages/components/collapse/theme/default.ts
折叠面板的头部字体大小为 fontSizeSm，且字体大小样式不生效
修改为 fontSizeHeaderSm，并修复样式不生效的问题
> fix(comp:collapse): modify header font-size to fontSizeHeaderSm

- packages/components/table/src/composables/useColumns.ts
- packages/components/table/src/main/FixedHolder.tsx
- packages/components/table/src/main/MainTable.tsx
1. 表格列宽度会在列数变化后清空，并没有重新计算
2. 表头在列没有计算的时候不显示
1. 不应该清空，在resize之后重新计算即可
2. 表格列宽默认会使用配置的宽度，如果列宽没有计算并不会导致表头闪烁，因此不需要隐藏
> fix(comp:table): table header not visible when width not collected

- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/style/index.less
高级搜索的z-index会在focus之后绑定并且不会消失，导致遮挡其他页面元素
高级搜索的z-inde只需要在focus的时候设置，其他情况下应当视为页面的内联元素，不赋以z-index
> fix(pro:search): container zIndex shouldn't be set when not focused

- packages/components/table/src/main/MainTable.tsx
scroll-horizontal 和 scroll-vertical 的class是由 scrollWidth和scrollHeight判断的，并不是由是否真的由滚动判断
修改以上问题，改为由 scrollHorizontalOverflowed和scrollVerticalOverflowed判断
> fix(comp:table): scroll classes is determined by scroll overflowed

- packages/components/alert/style/index.less
> fix(comp:alert): change alert marigin-right to 4px

- packages/cdk/popper/src/convertOptions.ts
popper的箭头尺寸计算不正常
将 flip 和 shift 中间件放在 arrow 之后执行
> fix(cdk:popper): arrow size not properly calculated

- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/components/nameSelectOverlay/KeywordFallbackPanel.tsx
- packages/pro/search/src/components/quickSelect/QuickSelectItem.tsx
- packages/pro/search/src/components/segment/Segment.tsx
- packages/pro/search/src/composables/useCacheData.ts
- packages/pro/search/src/composables/useResolvedSearchFields.ts
- packages/pro/search/src/composables/useSearchStates.ts
- packages/pro/search/src/segments/CreateSelectSegment.tsx
- packages/pro/search/src/segments/createCustomSegment.ts
- packages/pro/search/src/token.ts
- packages/pro/search/src/types/searchItem.ts
- packages/pro/search/src/types/segment.ts
- packages/pro/search/src/utils/generateSegmentStates.ts
高级搜索的 select field 在远程搜索的场景下，选中的数据没有缓存，导致搜索之后原本选中的数据被清除
缓存已选的数据，即使搜索过后改变了源数据也不会导致选中的数据不存在
> feat(pro:search): select field supports caching selected data

- packages/components/tag/style/index.less
改为用 box-shadow 实现 bordered 效果后，数字标签的边框会有锯齿
改回之前用border实现
> fix(comp:tag): reset bordered style from box-shadow to border

- packages/components/popover/style/index.less
pop 组件的内容区有一个4px的上边距，导致header部分视觉高度不为40px
pop 组件的内容区有一个8px的下边距，导popConfirm 的content部分与footer间距过大
pop 组件header部分视觉高度为40px
popConfirm 的content部分与footer间距为8px
> fix(comp:popover): the header slot height is 40px

- packages/components/button/style/index.less
多个按钮，如果部分有icon部分没有icon，在父级没有配置dispaly：flex时会无法对齐
可以对齐
> fix(comp:button): button is not vertical center when it has icon

- packages/components/cascader/src/composables/useSearchable.ts
远程搜索后动态修改dataSource
直接搜索会显示空，失焦后再触发才会显示最新的数据
动态修改dataSource后，会直接显示出来
```javascript
<template>
<IxCascader placeholder="Please search" :dataSource="dataSource" searchable :search-fn="false" @search="handler" />
</template>
import { type CascaderData } from '@idux/components/cascader'
import { type RadioData } from '@idux/components/radio'
const searchable = ref(true)
const searchableData = [
{ key: true, label: 'true' },
{ key: 'overlay', label: 'overlay' },
{ key: false, label: 'false' },
] as RadioData[]
const dataSource = ref([
{
key: 'components',
label: 'Components',
children: [
{
key: 'general',
label: 'General',
children: [
{
key: 'button',
label: 'Button',
},
{
key: …
```
> fix(comp:cascader): remote search data is alaways empty

- packages/cdk/scroll/__tests__/__snapshots__/virtualScroll.spec.ts.snap
- packages/cdk/scroll/__tests__/virtualScroll.spec.ts
- packages/cdk/scroll/demo/Basic.vue
- packages/cdk/scroll/demo/Both.vue
- packages/cdk/scroll/src/virtual/VirtualScroll.tsx
- packages/cdk/scroll/src/virtual/composables/useScrollTo.ts
- packages/cdk/scroll/src/virtual/types.ts
- packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap
BREAKING CHANGE: scrollTo option index is deprecated, use rowIndex instead
BREAKING CHANGE: scrollTo option offset is deprecated, use verticalOffset instead
BREAKING CHANGE: scrollTo option key is deprecated, use rowKey instead
BREAKING CHANGE: scrollTo option align is deprecated, use verticalAlign instead
虚拟滚动 scrollTo 支持设置横向滚动位置
新增 rowKey, colKey 参数
新增 rowIndex, colIndex 参数
新增 verticalOffset, horizontalOffset 参数
新增 verticalAlign, horizontalAlign 参数
> feat(cdk:scroll): virtual scrollTo supports horizontal target

- packages/components/table/src/composables/useColumns.ts
不连续的固定列，固定的位置计算不正确
例如：1，3列固定，则第3列的固定位置计算不正确，导致第3列没有固定
修复以上问题，固定列的index应当保留原始数据的Index
> fix(comp:table): inconsecutive fixed columns are not fixed

- packages/components/drawer/src/Drawer.tsx
- packages/components/drawer/src/DrawerWrapper.tsx
- packages/components/drawer/src/token.ts
当IxDrawer配置了destroyOnHide的时候，打开抽屉之后立刻关闭，会导致drawer没有被正常清除，遮挡住页面无法操作
修复以上问题
> fix(comp:drawer): destroyOnHide drawer doesn't destroy if visible is set false before enter transition

- packages/pro/table/style/index.less
ProTable的 layoutTool 的 trigger，当其刚好滚动到列的分割线上面的时候，悬浮会出现resize的handle
修改 z-index，使trigger位于handle上方
> fix(pro:table): hovering layout tool trigger shouldn't show resize handle

- packages/cdk/scroll/src/virtual/composables/useRenderPool.ts
- packages/components/table/src/utils/index.ts
虚拟滚动渲染池的复用没有规则，仅仅会从池里面找到第一个可用的元素，在渲染数据整体变更后，重新生成的渲染视图不能保证完全复用上次渲染的dom或组件，即使复用了也不能保证和上次渲染的顺序一致，导致性能问题
在从渲染池中拿元素时，优先获取和当前需要渲染的数据的key相同的渲染池元素，最大可能保证两次渲染的稳定性
> fix(cdk:scroll): optimize virtual scroll render pool resuage

- packages/components/alert/theme/default.ts
- packages/components/tag/theme/default.ts
- packages/components/theme/src/themeTokens/shared/color/getAlphaColor.ts
mix color with alpha with container bg color to get a bg color with no alpha
由于tag和alert的背景颜色是有透明度的，在有颜色的背景上展示的颜色会透出底部背景色
先获取有透明度的颜色，再获取该颜色在默认容器背景色上的颜色，去掉alpha通道值
> fix(comp:alert,tag): replace rgba bg color with color with no alpha

- packages/components/alert/theme/dark.css
- packages/components/alert/theme/default.css
- packages/components/dark.full.css
- packages/components/default.full.css
- packages/components/tag/docs/Theme.zh.md
- packages/components/tag/theme/dark.css
- packages/components/tag/theme/default.css
- packages/components/tree-select/docs/Theme.zh.md
- packages/components/tree-select/theme/dark.css
- packages/components/tree-select/theme/default.css
- packages/components/tree/docs/Theme.zh.md
- packages/components/tree/style/index.less
- packages/components/tree/theme/dark.css
- packages/components/tree/theme/default.css
- packages/pro/tree/style/variables.less
> docs: update theme doc

- packages/components/config/src/dateConfig.ts
startOf function should support TimeConfigType
endOf function should support TimeConfigType
1. dateConifg 的  TimeConfigType 不支持 `millisecond`
2. startOf 方法不支持 TimeConfigType
3. endOf 方法不支持 TimeConfigType
1. TimeConfigType 新增 `millisecond`
2. startOf 方法支持获取 hour, minute, second 的起点
3. endOf 方法支持获取 hour, minute, second 的终点
> fix(comp:config): `millisecond` should be included in TimeConfigType

- packages/components/date-picker/src/DateRangePicker.tsx
- packages/components/date-picker/src/composables/useRangeControl.ts
- packages/components/date-picker/src/composables/useRangePanelState.ts
- packages/components/date-picker/src/panel/Panel.tsx
- packages/components/date-picker/src/panel/RangePanel.tsx
- packages/components/date-picker/src/utils.ts
选择时间范围，起始的date均指向了0点0分0秒
选择时间范围，开始时间应该指向日期的0点0分0秒，结束时间应当指向23点59分59秒999毫秒，覆盖完整的范围
针对月、周、年、季度的选择，同样覆盖完整的范围
选择具体的时间时，应当精确到时间的最小单位，例如面板中只支持选择小时和分钟，那要精确到分钟的起始，即开始时间应该是0秒0毫秒，结束时间应该是59秒999毫秒
> fix(comp:date-picker): range start and and date cover full range

- packages/cdk/scroll/demo/SimulatedScroll.vue
- packages/components/theme/src/composables/useThemeProvider.ts
- packages/components/theme/src/composables/useTokenRegister.ts
after global token update, all registered tokens should be updated, and global token key should be excluded
reset tokens shouldn't be explicitly updated because updating global tokens will trigger all token updates
全局token更新时，会触发所有的token更新，但是没有把global排除掉导致重复的计算
reset tokens 会在全局token更新后自动更新，但是也被显式重复更新了
优化以上逻辑
> fix(comp:theme): optimize global token update logic

- packages/components/select/src/Select.tsx
当配置了getKey，且数据的key并不是'key'，点击面板选项会选择空
修复以上问题
> fix(comp:select): clicking an option created by input selects undefind

- packages/components/date-picker/src/composables/useRangePanelState.ts
文档中只能选择7天内的demo，选择开始时间之后，关闭面板，会导致面板上日期的禁用状态不正常
以上问题的原因是面板收起时没有触发onSelect，因此在visible变更后新增onSelect的触发
> fix(date-picker): range panel onSelect should be triggered when panel not visible

- packages/components/checkbox/style/index.less
- packages/components/table/src/main/body/BodyCell.tsx
- packages/components/table/style/index.less
- packages/components/table/style/indexable.less
table的selectable列，showIndex不生效
1. 修复以上问题
2. 修改checkbox的vertical-align，使其在表格中的高度正常
> fix(comp:table): selectable column showIndex doesn't work

- packages/components/radio/style/index.less
- packages/components/table/__tests__/__snapshots__/table.spec.ts.snap
- packages/components/table/demo/Selectable.vue
- packages/components/table/src/main/body/BodyCell.tsx
- packages/components/table/style/indexable.less
- packages/components/table/style/selectable.less
- packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap
表格的 selectable 列，checkbox和radio的高度不正常，导致showIndex开启之后，悬浮上去高度抖动
将checkbox和radio的vertical-align设置为middle，并且在table-cell上加上类型相关的class，selectable column下的checkbox和radio的line-height均设置为1
> fix(comp:table): height of checkbox or radio in selectable column cell isn't right

- packages/components/textarea/style/index.less
textarea组件的文字颜色在dark主题下不正常
修复以上问题
> fix(comp:textarea): textarea color isn't correct under dark theme

- packages/components/tour/demo/CustomMask.md
- packages/components/tour/demo/CustomMask.vue
- packages/components/tour/demo/Outline.md
- packages/components/tour/demo/Outline.vue
- packages/components/tour/src/Mask.tsx
- packages/components/tour/src/composables/useActiveStep.ts
- packages/components/tour/src/composables/useMask.ts
- packages/components/tour/src/composables/useMergedProps.ts
- packages/components/tour/src/composables/useStepChange.ts
- packages/components/tour/src/composables/useTarget.ts
- packages/components/tour/src/types.ts
- packages/components/tour/style/index.less
- packages/components/tour/theme/default.ts
- packages/components/tour/theme/tokens.ts
1. 支持通过 `mask.container` 配置遮罩的渲染位置
2. 支持通过 `gap.outline` 以及 `mask.outlineColor` 配置目标元素的外轮廓
> feat(comp:tour): supports outline and mask container

- packages/components/carousel/__tests__/carousel.spec.ts
- packages/components/carousel/src/Carousel.tsx
- packages/components/carousel/src/composables/useStrategy.ts
Carousel的item 数量只有一个的时候，next,pre,goto的跳转调用，会触发切换动画，但实际上没有可切换的内容
1. 当item数量只有一个的时候，切换的调用不应该执行
2. 当item数量只有一个的时候，切换的箭头按钮不应该显示
> fix(comp:carousel): pre and next arrow should hide when item count is 0

- packages/components/collapse/style/index.less
- packages/components/empty/style/index.less
margin 的 css 变量引用错误，引用了不存在的css变量
修复以上问题
> fix(comp:collapse,empty): margin size css var reference error

- packages/components/table/src/main/body/BodyCell.tsx
表格展开按钮的点击会触发行的选中
阻止点击事件冒泡和默认行为触发，修复以上问题
> fix(comp:table): clicking expand icon shouldn't trigger row select

- packages/components/tooltip/docs/Theme.zh.md
- packages/components/tooltip/style/index.less
- packages/components/tooltip/theme/dark.css
- packages/components/tooltip/theme/default.css
- packages/components/tooltip/theme/default.ts
- packages/components/tooltip/theme/tokens.ts
tooltip 组件内容的white-space不允许换行
1. 提供 whiteSpace 主题变量，可以配置内容是否可以换行
2. 默认的 whiteSpace 为 pre-wrap
如果这个修改对业务有影响，自定义主题变量可以解决
> fix(comp:tooltip): tooltip content should wrap on line break

- packages/cdk/utils/src/tree.ts
- packages/components/tree-select/src/TreeSelect.tsx
- packages/components/tree-select/src/composables/useSelectedState.ts
- packages/components/tree/__tests__/tree.spec.ts
- packages/components/tree/src/Tree.tsx
- packages/components/tree/src/composables/useCheckable.ts
- packages/components/tree/src/composables/useDataSource.ts
- packages/components/tree/src/composables/useExpandable.ts
- packages/components/tree/src/node/Checkbox.tsx
- packages/components/tree/src/types.ts
- packages/components/utils/src/useTreeCheckStateResolver.ts
从选择框中移除已选项，不会同步取消树的勾选
1. 使用 components/utils 中的 useTreeCheckStateResolver 重构 tree 组件的勾选计算逻辑
2. 在从选择框中移除选项后，应该调用树的勾选触发函数，根据级联策略计算取消该项勾选后的value
> fix(comp:tree-select): removing item from selector doesn't uncheck tree node

- packages/components/control-trigger/src/ControlTrigger.tsx
- packages/components/control-trigger/src/composables/useOverlayState.ts
- packages/pro/dark.full.css
- packages/pro/default.full.css
- packages/pro/tag-select/docs/Theme.zh.md
- packages/pro/tag-select/src/content/TagSelectOption.tsx
- packages/pro/tag-select/style/index.less
- packages/pro/tag-select/theme/dark.css
- packages/pro/tag-select/theme/default.css
- packages/pro/tag-select/theme/default.ts
1. 选择框中的tag文字会溢出标签
2. 当overlayMatchWidth 为true 时，面板内选择的标签长度不应该无限制变长，溢出的文字应该显示省略并悬浮展示所有内容
修复以上问题
> fix(pro:tag-select): tag text shouldn't overflow when overlayMatchWidth is true

- packages/pro/tag-select/src/composables/useTagData.ts
当搜索输入的内容严格匹配到了一个标签的label，创建标签的选项依然存在
在严格匹配到一个搜索到的标签的label时，不应该显示创建标签的选项
> fix(pro:tag-select): tag creation option should hide when input fully matched

- packages/pro/tag-select/docs/Api.zh.md
- packages/pro/tag-select/src/ProTagSelect.tsx
- packages/pro/tag-select/src/composables/useRemoveConfirm.ts
- packages/pro/tag-select/src/composables/useSelectConfirm.ts
- packages/pro/tag-select/src/content/SelectedTag.tsx
- packages/pro/tag-select/src/token.ts
- packages/pro/tag-select/src/types.ts
新增支持 beforeRemoveConfirm 和 beforeSelectConfirm，用来判断在移除和选择标签数据时是否可以确认
> fix(pro:tag-select): supports beforeRemoveConfirm and beforeSelectConfirm

- packages/pro/tag-select/src/composables/useSelectedState.ts
移除一个没有被选中的标签数据，同样触发了 onTagRemove 事件
不应该触发，修复以上问题
> fix(pro:tag-select): removing unselected tag data shouldn't emit tagRemove

- packages/pro/search/src/components/quickSelect/QuickSelectItem.tsx
- packages/pro/search/src/components/quickSelect/QuickSelectPanel.tsx
- packages/pro/search/src/types/quickSelectPanel.ts
在快捷面板的搜索项搜索输入框输入内容后，选中下方的选项，输入框被收起并清空
不应该收起并清空
> fix(pro:search): quickselect search input shouldn't hide when option selected

- packages/components/tree-select/src/TreeSelect.tsx
> fix(comp:tree-select): search input shouldn't be cleared after option checked

- packages/components/tree/src/composables/useCheckable.ts
当级联策略变化之后，checkedChange不会触发
级联策略变化之后，勾选的key会被重新计算，应该触发checkedChange通知外部更新数据
> fix(comp:tree): checkedChange should be called after cascaderStrategy change

- packages/cdk/resize/src/resizable/useResizable.ts
1. 拖动开始的时候没有设置position，这期间如果元素的尺寸发生变化，之前记录的position并不会更新，如果仅仅点击边界不拖动，会让缩放异常进行
2. 只有在拖动的时候才设置resizing为true
拖动开始的时候就设置position，并设置 resizing 为 true
> fix(cdk:resizable): position should be set at start of resizing

- packages/components/table/style/border.less
配置了 borderless 为 false 后，当某个单元格的上一行的下一个列的单元格配置了 row-span 并覆盖了其所在的行，刚好在其后，此时该单元格应该有有边框，但目前有边框不会显示
修复以上问题
> fix(comp:table): table cell border missing when row span included

- packages/pro/table/src/composables/useColumns.ts
- packages/pro/table/src/contents/LayoutToolContent.tsx
- packages/pro/table/src/contents/LayoutToolTree.tsx
- packages/pro/table/src/types.ts
- packages/pro/table/src/utils/index.ts
布局工具中，当同时有固定列和普通列时，搜索内容为空会出现多个空状态
不应当展示多个空状态，只展示一个空状态
> fix(pro:table): layout tool tree shouldn't show empty

- packages/components/table/style/fixed.less
固定列尾的列和固定在列首的列z-index一致，在表头分组的场景下，滚动之后列首的固定列可能会盖住列尾的固定列
修改以上问题
> fix(comp:table): fixed end column z-index should be above fixed start columns

- packages/pro/textarea/demo/Basic.vue
- packages/pro/textarea/src/ProTextarea.tsx
- packages/pro/textarea/src/composables/useErrorLines.ts
- packages/pro/textarea/src/composables/useRowsCounts.ts
配置了 rows 之后，高度不正确，没有任何输入依然会出现滚动条
> fix(pro:textarea): height isn't correct when rows is set

- packages/components/table/src/Table.tsx
- packages/components/table/src/composables/useColumnOffsets.ts
- packages/components/table/src/composables/useColumnWidthMeasure.ts
- packages/components/table/src/composables/useColumns.ts
- packages/components/table/src/main/ColGroup.tsx
- packages/components/table/src/main/MainTable.tsx
- packages/components/table/src/main/body/BodyRowSingle.tsx
- packages/components/table/src/token.ts
1. measured width should be used in table header fix holder
2. column width is evenly aligned when scroll.width is provided
3. table content colgroup width is set using width config in columns
表头的colgroup也优先使用了column中给定的width，导致表头会有错位
重构宽度测量和计算逻辑，在表格体的colgroup中仅使用配置的宽度，而在固定的表头中和固定列的offset计算中使用测量得到的宽度
> fix(comp:table): refactor table column width measure logic

- packages/pro/search/src/segments/CreateSelectSegment.tsx
高级搜索，select类型的field，如果先设置了 value， 之后才加载select的选项数据，会报错
修复以上问题
format的时候会设置缓存，但设置缓存的时候没有过滤掉空数据
> fix(pro:search): setting value before select option loaded throws error

- packages/cdk/scroll/src/virtual/composables/useRenderPool.ts
虚拟滚动下，列表或表格的dom或组件应该在离屏后被回收，并在新数据渲染时被复用，但并没有生效
修复以上问题
renderPool的 getPoolItem 在找到可复用的item后没有返回，每次都重新创建了
> fix(cdk:virtual): render pool item reuse doesn't take effect

- packages/pro/tag-select/style/index.less
标签创建选项中的输入文字 font-weight 为 lg （500），效果不明显
修改为 xl （600）
> fix(pro:tag-select): change creation option input font-weight to xl

- packages/pro/tag-select/style/index.less
标签选择，面板选项中的标签以及选中的标签，都有一个最小宽度
取消最小宽度，配置 min-width: auto
> fix(pro:tag-select): tag min width should be auto

- packages/pro/tag-select/docs/Api.zh.md
- packages/pro/tag-select/src/composables/useRemoveConfirm.ts
- packages/pro/tag-select/src/types.ts
新增 confirmBeforeDataRemove， 可以配置使标签数据的删除不需要弹窗确认
> fix(pro:tag-select): tag data remove confirm should be configuarable

- packages/components/theme/src/composables/useDynamicCss.ts
- packages/components/theme/src/utils/dynamicCss.ts
在微前端框架中，如果存在了两个版本的idux，子应用的themeProvider上下文销毁时，会清除掉全局的主题变量style元素
修复以上问题，将style元素的引用次数绑定在style元素上
> fix(comp:theme): store theme style reference count on style element

- packages/cdk/scroll/src/virtual/composables/useRenderPool.ts
- packages/components/table/src/main/body/RenderBodyCells.tsx
when all data is re-rendered, pooled items were asigned to data with different item key
在全部数据被重新渲染之后，所有的渲染池元素被回收并重新分配，当新添加的数据在上次渲染的数据前面时，会将已经回收的元素先分配给新数据，导致老数据在渲染时视图的key与上次渲染不一致。
修复以上问题
会进行两次遍历，第一次筛选出上一次渲染的数据并分配原本的渲染池元素，第二次遍历剩余的新数据元素从渲染池中按顺序分配元素
> fix(cdk:virtual): render pool item with same item key is not reused

- packages/pro/search/src/segments/CreateTreeSelectSegment.tsx
tree-select 类型的搜索项，当取消勾选一个叶子节点后，搜索输入的解析不正确，被取消勾选的节点label被当作了搜索输入
修复以上问题
> fix(pro:search): input is formatted incorrectly after tree select leaf option unchecked

- packages/components/_private/overlay/src/Overlay.tsx
- packages/components/_private/overlay/src/types.ts
- packages/components/control-trigger/src/ControlTrigger.tsx
- packages/components/control-trigger/src/ControlTriggerOverlay.tsx
- packages/components/control-trigger/src/types.ts
- packages/components/tree-select/__tests__/__snapshots__/treeSelect.spec.ts.snap
- packages/components/tree-select/src/TreeSelect.tsx
when tree in overlay isn't rendered yet, removing item in selector doesn't work
在tree-select的浮层还没有渲染时，点击删除选择框中的选中标签不会生效
修复以上问题
overlay增加了lazy配置，可以配置是否懒渲染浮层内容
> fix(comp:tree-select): removing item in selector doesn't work

- packages/pro/table/src/contents/LayoutToolTree.tsx
布局工具中，在搜索之后，勾选或者取消勾选搜索到的列，会使表格的列显示异常变化
修复以上问题
> fix(pro:table): check in layout tool after search doesn't work

- packages/cdk/scroll/src/virtual/composables/useRenderPool.ts
在下一次渲染时，在上一次渲染过程中已经存在的元素不会被更新，导致其index没有变化
proTable中，勾选某一个默认隐藏的列，在开启虚拟滚动的情况下，向下滚动会导致列的渲染顺序不正常
即使是重复渲染的元素，也应该重新赋值index和数据，因为其顺序和渲染的数据可能会发生变化
> fix(cdk:scroll): pool item not recycled index isn't right

- packages/components/tabs/src/composables/useSelectedNav.ts
- packages/components/tabs/src/contents/TabNavWrapper.tsx
tabs的title在更新的时候，有可能会导致整体tabs导航栏的尺寸发生变化，此时在 line 类型下，下方的横线位置计算不正确
修复以上问题
> fix(comp:tabs): line type bar offset error after tab title updates

- packages/components/popconfirm/src/PopconfirmContent.tsx
- packages/components/popconfirm/style/index.less
popconfim 的header 中没有渲染图标或者没有header的时候，内容区域的左padding依然留出了图标的位置
在没有图标或者没有header的时候，内容区域的左padding不应该留出图标的位置
> fix(comp:popconfirm): content padding should be different when no header icon rendered

- packages/pro/search/src/segments/CreateSelectSegment.tsx
高级搜索组件，select 搜索项在使用远程搜索时，选中新的选项会覆盖掉之前的选中项
修复以上问题
> fix(pro:search): selecting option after remote search overides value

- packages/components/table/demo/Server.vue
- packages/components/table/src/composables/useSelectable.ts
- packages/components/utils/src/useTreeCheckState.ts
- packages/components/utils/src/useTreeCheckStateResolver.ts
表格在dataSource改变后（远程搜索或分页的场景），原本选中的项目被清空了
修改以上问题
在 useTreeCheckState 中，每当选中的key变化后，缓存当前选中的数据，避免在下次处理选中项时数据不存在
> fix(comp:table): selection should not be emptied after dataSource change

- packages/components/utils/src/useTreeCheckState.ts
当datasource改变之后，选中某一行（非全选），会导致之前的选中的行数据被清空
修复以上问题
> fix(comp:table): table selection emptyed after data change and select

- packages/components/select/src/Select.tsx
- packages/components/selector/src/contents/Input.tsx
单选场景下，在配置了searchable之后，在选择框中输入搜索内容，失焦之后输入的内容没有清空并且input元素遮挡了选中的内容
修复以上问题
在失焦之后清空输入，并且仅在input不处于可输入状态且没有输入内容时才隐藏，并且仅当可输入（allowInput, searchable）时才设置输入内容
> fix(comp:select): selector input value should be emptied after blur

- packages/components/table/src/Table.tsx
- packages/components/table/src/other/Pagination.tsx
当数据为空时，默认不渲染分页，导致数据改变后分页组件的事件没有正常触发
修复以上问题
依然渲染分页，但是通过 v-show 隐藏
> fix(comp:table): pagination should render but hide when empty

- packages/components/tree-select/src/types.ts
- packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap
- packages/components/tree/src/types.ts
tree-select在开了虚拟滚动时，在滚动到底部会导致面板内抖动
修复以上问题
修改默认的virtualItemHeight为32
> fix(comp:tree-select): panel shakes after scrolling at bottom

- packages/cdk/scroll/src/scrollbar/composables/useScrollbarState.ts
- packages/cdk/scroll/src/useScroll/useScroll.ts
- packages/cdk/scroll/src/virtual/VirtualScroll.tsx
- packages/cdk/scroll/style/index.less
- packages/cdk/utils/src/dom.ts
- packages/components/table/src/main/body/BodyCell.tsx
- packages/components/table/src/main/head/HeadCell.tsx
- packages/components/table/style/size.less
模拟的滚动条，在虚拟滚动数据变更之后，如果内容宽高处于容器宽高附近，横向纵向的溢出状态计算会无限循环，导致滚动条闪烁
修复以上问题
1. 重写实现溢出状态的计算判断逻辑，不再使用计算属性根据渲染的宽高实时判断，而是在更新滚动容器信息时统一根据预先获取的滚动条宽高一次计算，避免渲染后无限触发计算
2. 滚动溢出的计算内置在 `useScroll` API 内部，update 之后自动计算，外部不再计算
> fix(cdk:scroll): simulated scrollbar blinks after data change

- packages/cdk/scroll/__tests__/__snapshots__/virtualScroll.spec.ts.snap
- packages/cdk/scroll/src/useScroll/useScroll.ts
- packages/cdk/scroll/src/useScroll/useWheel.ts
- packages/cdk/scroll/src/virtual/VirtualScroll.tsx
- packages/cdk/scroll/src/virtual/contents/Holder.tsx
- packages/components/tree/__tests__/__snapshots__/tree.spec.ts.snap
1. 虚拟滚动容器，在firefox中，滚轮滚动失效
2. 横向的虚拟滚动，在firefox中，横向滚动条的宽度不正确
修复以上问题
在firefox下，添加一个height: 0 的元素并不能真正撑开容器的scrollHeight，需要设置 height 1px
> fix(cdk:scroll): virtual scroll couldn't scroll under firefox

- packages/cdk/scroll/src/virtual/composables/useRenderPool.ts
- packages/cdk/scroll/src/virtual/composables/useScrollState.ts
虚拟滚动，当数据更新时，有几率导致某行的列数据渲染没有正常更新到新的数据
出现于：proTable 开启双向虚拟滚动，并取消勾选某几列的显示（无横向滚动条状态），向下滚动，会出现某行的列并没有改变，而导致整个表格的列错位
修复以上问题
问题原因：
在渲染池计算的过程中，如果有某行的渲染池元素被回收且没有被立刻复用，其中的列就并不会在数据更新的时候全回收，导致该元素被复用的时候列数据出现错误
修改方法：
在一次行更新的过程中，找到没有被当次更新直接复用并退回到渲染池中的元素，回收该元素中所有的列数据
> fix(cdk:scroll): virtual list render error after dataSource change

- packages/cdk/scroll/src/virtual/VirtualScroll.tsx
- packages/cdk/scroll/src/virtual/composables/useRenderPool.ts
- packages/cdk/scroll/src/virtual/contents/Holder.tsx
- packages/cdk/scroll/src/virtual/token.ts
当虚拟滚动传入了 colModifier 和 rowModifier 时，滚动的offset值应当加上被添加到行首或者列首的元素尺寸，保证滚动的内容区的offset正确，否则会造成滚动位置跳跃的情况
修复以上问题
> fix(cdk:scroll): virtual scroll start offset should add size of prepended items

- packages/components/utils/src/useOverlayFocusMonitor.ts
- packages/pro/search/src/composables/useFocusedState.ts
在火狐浏览器下，控件（包括proSearch）的浮层中触发了聚焦，会有概率导致浮层关闭
修复以上问题
内部逻辑，判断浮层以及关联元素中，当blur触发之后，如果在一个setTimeout之后存在这些元素中的一个focus事件并且事件触发的时间在blur之后，则认为是组件内部的焦点转移
原本逻辑，认为后触发的focus事件的触发时间一定晚于blur事件，而实际在火狐浏览器中两个时间戳可能完全相等
另外，使用统一的 useOverlayFocusMonitor 重构 proSearch 中的 useFocusState，所有组件内部相关的逻辑全部统一处理
> fix(comp:*): focusing in control overlay causes it to close unexpectedly

- packages/components/select/demo/DndSortable.md
- packages/components/select/demo/DndSortable.vue
- packages/components/select/docs/Api.zh.md
- packages/components/select/src/Select.tsx
- packages/components/select/src/composables/useOptions.ts
- packages/components/select/src/composables/usePanelProps.ts
- packages/components/select/src/panel/Option.tsx
- packages/components/select/src/panel/Panel.tsx
- packages/components/select/src/token.ts
- packages/components/select/src/types.ts
- packages/components/select/src/utils/flattenOptions.ts
- packages/components/select/style/index.less
为 `IxSelect` 以及 `IxSelectPanel` 新增拖拽排序功能
> feat(comp:select): add support for dnd sortable

- packages/components/tabs/demo/DndSortable.md
- packages/components/tabs/demo/DndSortable.vue
- packages/components/tabs/docs/Api.zh.md
- packages/components/tabs/src/Tabs.tsx
- packages/components/tabs/src/contents/MoreSelectPane.tsx
- packages/components/tabs/src/contents/TabNav.tsx
- packages/components/tabs/src/contents/TabNavWrapper.tsx
- packages/components/tabs/src/tokens.ts
- packages/components/tabs/src/types.ts
> feat(comp:tabs): add dnd sortable support for tabs

- packages/components/table/src/main/body/Body.tsx
- packages/components/table/src/types.ts
- packages/pro/table/demo/DndSortable.md
- packages/pro/table/demo/DndSortable.vue
- packages/pro/table/docs/Api.zh.md
- packages/pro/table/index.ts
- packages/pro/table/src/ProTable.tsx
- packages/pro/table/src/composables/useColumns.ts
- packages/pro/table/src/contents/SortableBody.tsx
- packages/pro/table/src/contents/SortableBodyRow.tsx
- packages/pro/table/src/token.ts
- packages/pro/table/src/types.ts
- packages/pro/table/style/index.less
新增 `IxProTable` 的拖拽排序功能
基础表格支持配置 customTag.body
> feat(pro:table): add dnd sortable support for proTable

- packages/components/config/src/defaultConfig.ts
- packages/components/config/src/types.ts
- packages/components/popover/docs/Api.zh.md
- packages/components/popover/src/types.ts
- packages/components/tooltip/docs/Api.zh.md
- packages/components/tooltip/src/types.ts
- packages/components/tooltip/src/useTooltipOverlay.ts
popover 的 showArrow 全局配置不生效
1. 修改以上问题
2.  tooltip 和 popconfirm 的 showArrow 支持全局配置
> feat(comp:popconfirm): popconfirm supports showArrow global config

- packages/pro/table/style/index.less
proTable 在表格存在竖向滚动，且最后一列存在筛选或者排序时，布局工具的按钮会遮盖住筛选或者排序的触发按钮
修复以上问题
> fix(pro:table): layout tool btn covers column trigger when has scroll

- packages/cdk/dnd/src/composables/useDndSortable/createTreeStrategyContext.ts
- packages/cdk/dnd/src/composables/useDndSortable/useDndSortable.ts
- packages/cdk/scroll/src/virtual/composables/useSizeCollect.ts
- packages/cdk/utils/src/convert.ts
- packages/components/breadcrumb/src/BreadcrumbItem.tsx
- packages/components/select/src/composables/usePanelActiveState.ts
- packages/components/table/src/composables/useSelectable.ts
- packages/components/table/src/main/ColGroup.tsx
- packages/components/table/src/main/body/BodyCell.tsx
- packages/components/table/src/main/head/HeadCell.tsx
- packages/components/theme/src/composables/useTokenMerge.ts
- packages/components/theme/src/composables/useTokenRegister.ts
- packages/components/theme/src/useThemeToken.ts
- packages/components/tree/demo/CascaderStrategy.vue
- packages/components/tree/demo/Virtual.vue
- packages/components/tree/src/Tree.tsx
- packages/components/tree/src/composables/useDataSource.ts
- packages/components/tree/src/node/TreeNode.tsx
- packages/components/tree/src/token.ts
- packages/components/upload/src/component/Selector.tsx
- packages/components/upload/src/composables/useRequest.ts
- packages/components/utils/src/useTreeCheckState.ts
- packages/components/utils/src/useTreeCheckStateResolver.ts
- packages/pro/search/src/components/segment/Segment.tsx
- packages/pro/search/src/segments/CreateCascaderSegment.tsx
- packages/pro/search/src/segments/CreateSelectSegment.tsx
- packages/pro/search/src/segments/CreateTreeSelectSegment.tsx
- packages/pro/search/src/utils/getSelectableCommonParams.ts
- packages/pro/tag-select/src/composables/usePanelActiveState.ts
- packages/pro/tag-select/src/composables/useTagData.ts
大数据量下（1w+），树在开启虚拟滚动是，滚动后的渲染卡顿，勾选卡顿
大幅度优化以上场景，提升90%
1. 修改虚拟滚动的元素尺寸收集和获取逻辑，在内部将响应式变量缓存不可响应的简单变量，减少不必要的响应式变量get的性能消耗
2. 原先树节点的渲染逻辑中存在一个遍历当前数据的过程，消耗了大量的性能，将该遍历提前
3. 优化通用的树勾选状态逻辑，减少不必要的响应式更新频率，尽量将耗时的计算聚合
4. 优化树勾选处理方法，减少不必要的循环
5. 由于这部分逻辑同时影响了表格的勾选，同步修改表格引用树勾选逻辑的代码，将缓存节点数据的逻辑去掉，改由通用的树勾选逻辑统一处理
> fix(comp:tree): optimize tree performance with large data (over 1w)

- packages/pro/search/src/segments/CreateSelectSegment.tsx
当取消选择select field 中 Input 的最后一个选项，input 解析异常，导致选项被异常过滤
修复以上问题
> fix(pro:search): input is formatted incorrectly after deselecting last option

- packages/pro/textarea/src/IndexColumn.tsx
- packages/pro/textarea/src/ProTextarea.tsx
- packages/pro/textarea/src/composables/useErrorLines.ts
- packages/pro/textarea/src/composables/useLineRender.ts
- packages/pro/textarea/src/composables/useRowsCounts.ts
- packages/pro/textarea/src/content/Content.tsx
- packages/pro/textarea/src/token.ts
1. 输入行过多时，错误行的标红元素dom太多，影响性能
2. 输入行过多时，行号的dom元素太多，影响性能
3. 输入行过多时，每次输入变化都会触发所有行的分割和计算，导致卡顿
1. 根据行高和滚动事件的触发，采用虚拟列表的方式优化渲染，只渲染滚动范围内的错误行和行号元素
2. 缓存每行的计算结果，在某一行的输入没有变化时，使用上次的计算结果，不重复计算
> fix(pro:textarea): optimize performance

- packages/components/_private/header/src/Header.tsx
- packages/pro/transfer/__tests__/__snapshots__/proTransfer.spec.ts.snap
具有 header 插槽的modal 组件，开启 draggable，拖拽不生效
修复以上问题
1. 私有的 header 组件返回的vnode可能不是最终渲染的vnode，改用 getFirstValidVnode 获取第一个可用的vnode
2. header 组件的 header 插槽不再支持多节点组件
> fix(comp:modal): draggable of modal with custom header slot doesn't work

- packages/pro/textarea/src/composables/useLineRender.ts
- packages/pro/textarea/src/composables/useRowsCounts.ts
每次输入内容导致内容的高度撑开时，都会触发所有行的重新计算
只有当内容区域的宽度变化时，才应该重新计算所有行的高度，仅仅高度变化时不重新计算
> fix(pro:textarea): optimize performance of row height collecting

- packages/components/_private/trigger/src/Trigger.tsx
- packages/components/_private/trigger/style/index.less
- packages/components/cascader/__tests__/__snapshots__/cascader.spec.ts.snap
- packages/components/date-picker/__tests__/__snapshots__/datePicker.spec.ts.snap
- packages/components/date-picker/__tests__/__snapshots__/dateRangePicker.spec.ts.snap
- packages/components/pagination/__tests__/__snapshots__/pagination.spec.ts.snap
- packages/components/select/__tests__/__snapshots__/select.spec.ts.snap
- packages/components/time-picker/__tests__/__snapshots__/timePicker.spec.ts.snap
- packages/components/time-picker/__tests__/__snapshots__/timeRangePicker.spec.ts.snap
- packages/components/tree-select/__tests__/__snapshots__/treeSelect.spec.ts.snap
时间选择，日期选择等具有后缀的控件，padding没有遮住后缀图标，显示的文字和图标重合了
修复以上问题，对有后缀的trigger，padding-right 增加一个图标的尺寸
> fix(comp:control-trigger): add suffix size to padding right

- packages/components/control-trigger/src/ControlTriggerOverlay.tsx
- packages/pro/tag-select/src/content/TagDataEditPanel.tsx
当控件的浮层中有虚拟滚动时，聚焦到虚拟滚动中渲染的选择后，滚动面板使聚焦的选项不再被渲染，会导致浮层失焦从而浮层异常关闭
修复以上问题
影响组件：control-trigger, select, cascader, tree-select, date-picker, time-picker, pro-tag-select
当聚焦在浮层中，并且触发了wheel事件后，将焦点重置到trigger上
> fix(comp:contro-trigger): overlay closes when scrolling with virtual scroll

- packages/pro/textarea/src/composables/useLineRender.ts
- packages/pro/textarea/src/composables/useRowsCounts.ts
当初始的value是undefined的时候，第一行的行号是0
修复以上问题，第一行的行号始终是1
> fix(pro:textarea): row number is `0` when value is undefined

- packages/pro/table/style/index.less
最后一列的筛选、排序触发按钮的右padding没有根据实际尺寸进行计算，而是写死了尺寸
修复以上问题
> fix(pro:table): modify trigger padding of last column

- packages/components/control-trigger/src/ControlTriggerOverlay.tsx
- packages/components/date-picker/src/content/Content.tsx
当contro-trigger的浮层中不存在任何一个可聚焦的元素时，在浮层上触发的 mousedown 会触发 blur 事件并使浮层关闭
修复以上问题
> fix(comp:control-trigger): mousedown on overlay triggers blur

- packages/pro/search/src/ProSearch.tsx
- packages/pro/search/src/composables/useActiveSegment.ts
- packages/pro/search/src/composables/useControl.ts
当 proSeaarch 被禁用的时候，组件依然可以操作，选择筛选条件
修复以上问题
1. 禁用的时候，阻止mousedown事件触发
2. 禁用的时候，不设置任何激活的segment，全部设置为undefined
> fix(pro:search): component still interactable when disabled

- packages/pro/search/src/components/segment/SegmentInput.tsx
搜索项的input宽度计算不准确
修复以上问题
计算的时候使用了input元素的父元素的样式，实际上应该使用input元素的样式进行计算
> fix(pro:search): segment input width measure is incorrect

- packages/components/_private/trigger/style/index.less
有后缀图表的 control-trigger 的右边距增加了一个 padding-size-xs 作为文字和图表的间距，实际上并不需要，而且会导致原组件中的比较短的控件文字位置不足
修复以上问题，去掉 padding-size-xs
> fix(comp:control-trigger): padding right wtih suffix is incorrect

- packages/pro/search/src/utils/measureTextWidth.ts
用于proSearch 的搜索项 Input 文字宽度测量的css属性名拼写不正确，导致测量结果不正确
修复以上问题
> fix(pro:search): search item input text width measure incorrect

- packages/components/utils/src/useTreeCheckState.ts
远程分页的场景下，切换页面之后，selectable column 的 onChange，不会抛出上一页的节点数据
> fix(comp:table): selectable onChange doesn't emit cached records

- packages/components/desc/style/index.less
如果 content 内容中有元素撑高了 content，例如图标设置比较大，或者有元素设置了 margin-top，都会使得 label 往下掉，这样就会跟其他的 desc-item 对不齐。
label 和 content 两个元素都能向上对齐。
> fix(comp:desc): ensure that the label and content are aligned at the top

- packages/cdk/popper/__tests__/__snapshots__/popper.spec.ts.snap
- packages/cdk/popper/__tests__/popper.spec.ts
- packages/cdk/popper/src/composables/useDelay.ts
- packages/cdk/popper/src/composables/useOptions.ts
- packages/cdk/popper/src/composables/usePlacement.ts
- packages/cdk/popper/src/composables/usePopperEvents.ts
- packages/cdk/popper/src/composables/useTriggerEvents.ts
- packages/cdk/popper/src/composables/useVisibility.ts
- packages/cdk/popper/src/types.ts
- packages/cdk/popper/src/usePopper.ts
1. popper的 visible 不支持受控
2. popper的所有配置不支持ref
1. 新增 onVisibleChange 属性，支持 visible 受控
2. 所有option，除onVisibleChange之外，支持传入Ref变量进行控制
当前暂时保留options本身的reactive监听支持，后续会去掉
> feat(cdk:popper): popper visible supports fully controlled

- packages/cdk/dnd/src/composables/useDndMovable/useMovablePosition.ts
useDndMovable 的初始化 init，调用之后不会重置移动的偏移量
修复以上问题
> fix(cdk:dnd): useDndMovable init doesn't work

- packages/components/dark.full.css
- packages/components/date-picker/docs/Theme.zh.md
- packages/components/date-picker/theme/dark.css
- packages/components/date-picker/theme/default.css
- packages/components/default.full.css
- packages/pro/dark.full.css
- packages/pro/default.full.css
- packages/pro/search/docs/Theme.zh.md
- packages/pro/search/style/quick-select.less
- packages/pro/search/theme/dark.css
- packages/pro/search/theme/default.css
- packages/pro/search/theme/default.ts
- packages/pro/search/theme/tokens.ts
新增IxProSearch组件的快捷搜索元素宽高相关的主题TOKEN
quickSelectItemMinWidth: 快捷搜索面板中搜索项的最小宽度
quickSelectItemMaxHeight: 快捷搜索面板中搜索项的最大高度
quickSelectSelectPanelMinHeight: 快捷搜索面板中select面板的最小高度
quickSelectTreeSelectPanelMinHeight: 快捷搜索面板中treeSelect面板的最小高度
> feat(pro:search): add quickSelect item size theme tokens

- packages/components/pagination/style/index.less
分页器在选择了每页100条时，size选择器出现了文字溢出
加宽size选择框的宽度到64，避免该问题
> fix(comp:pagination): size select text shouldn't overflow at 100

- packages/cdk/popper/src/composables/useVisibility.ts
- packages/components/_private/overlay/src/composables/useVisible.ts
当popper禁用时，触发相应的事件，依然会触发visible为true的更新，但是并不会触发visible为false的更新，导致嵌套的内层浮层如果是禁用的，可能造成上层浮层永远被锁不能触发更新
修复以上问题
> fix(cdk:popper): visible shouldn't be updated when disabled

- packages/components/table/src/main/MainTable.tsx
当alert插槽返回一个空节点时，表格内依然会渲染一个row
判断alert插槽是否是空节点，只有非空节点时才会渲染aler 行
> fix(comp:table): alert row shouldn't render when alert slot returns empty node

- packages/cdk/popper/src/composables/useVisibility.ts
- packages/cdk/popper/src/types.ts
当popper的visible被受控修改后，无法通过内部事件再次开启
> fix(cdk:popper): popper can't open when visible is updated by user

- packages/cdk/popper/demo/Controlled.md
- packages/cdk/popper/demo/Controlled.vue
- packages/cdk/popper/demo/Placement.vue
- packages/cdk/popper/demo/Trigger.vue
- packages/cdk/popper/docs/Api.zh.md
- packages/cdk/popper/src/composables/useOptions.ts
- packages/cdk/popper/src/composables/useTimer.ts
- packages/cdk/popper/src/convertOptions.ts
- packages/cdk/popper/src/types.ts
当初始的option传入了某项配置后，调用update方法对其进行修改，无法生效
如果传入的是ref变量，不支持update修改
如果传入的是非ref变量，可以通过update修改
已经不推荐使用update方法修改option，建议均使用ref变量，文档中已经去掉了对update的参数
> fix(cdk:popper): `update` shouldn't change ref option param
